// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

// Per-table generic type aliases used by the GraphQL wrapper's models: merge
// (envelope binding). gqlgen's `model:` path parser does not
// accept bracketed generic instantiation (`pkg.Connection[pkg.<T>]`) — its
// `internal/code/util.go::PkgAndType` splits on `.` and fails on the bracket
// form — so the wrapper binds the GraphQL envelope types to these alias
// names instead. gqlgen's binder calls `code.Unalias()` on resolved types
// so each alias resolves to its concrete `Connection[<T>]` / `Edge[<T>]` /
// `PaginateResult[<T>]` instantiation at zero cost.
//
// All three envelope levels are aliased so gqlgen reuses the runtime types
// throughout the connection traversal — `<T>Connection` for the top-level
// envelope, `<T>Edge` for the per-edge wrapper, `<T>ListResult` for offset
// pagination — leaving only the leaf scalar `PageInfo` (a non-generic
// concrete struct, bound directly by the wrapper). Without the `<T>Edge`
// alias gqlgen would autogenerate a `model.<T>Edge` and require a field
// resolver `Edges(ctx, *Connection[<T>]) ([]*model.<T>Edge, error)` per
// table; with the alias the runtime `Edge[<T>]` flows through the resolver
// unchanged and no `translate<T>Connection` / `translate<T>ListResult` /
// `translate<T>Edge` helpers are emitted (the runtime and schema
// envelope shapes are kept aligned field-for-field so the binding holds).

type APITokenConnection = Connection[APIToken]
type APITokenEdge = Edge[APIToken]
type APITokenListResult = PaginateResult[APIToken]

type ActivityConnection = Connection[Activity]
type ActivityEdge = Edge[Activity]
type ActivityListResult = PaginateResult[Activity]

type AttachmentConnection = Connection[Attachment]
type AttachmentEdge = Edge[Attachment]
type AttachmentListResult = PaginateResult[Attachment]

type CommentConnection = Connection[Comment]
type CommentEdge = Edge[Comment]
type CommentListResult = PaginateResult[Comment]

type CycleConnection = Connection[Cycle]
type CycleEdge = Edge[Cycle]
type CycleListResult = PaginateResult[Cycle]

type InvitationConnection = Connection[Invitation]
type InvitationEdge = Edge[Invitation]
type InvitationListResult = PaginateResult[Invitation]

type LabelConnection = Connection[Label]
type LabelEdge = Edge[Label]
type LabelListResult = PaginateResult[Label]

type MembershipConnection = Connection[Membership]
type MembershipEdge = Edge[Membership]
type MembershipListResult = PaginateResult[Membership]

type ProjectConnection = Connection[Project]
type ProjectEdge = Edge[Project]
type ProjectListResult = PaginateResult[Project]

type ProjectStatConnection = Connection[ProjectStat]
type ProjectStatEdge = Edge[ProjectStat]
type ProjectStatListResult = PaginateResult[ProjectStat]

type SsoConnectionConnection = Connection[SsoConnection]
type SsoConnectionEdge = Edge[SsoConnection]
type SsoConnectionListResult = PaginateResult[SsoConnection]

type TaskConnection = Connection[Task]
type TaskEdge = Edge[Task]
type TaskListResult = PaginateResult[Task]

type TaskAssigneeConnection = Connection[TaskAssignee]
type TaskAssigneeEdge = Edge[TaskAssignee]
type TaskAssigneeListResult = PaginateResult[TaskAssignee]

type TaskDependencyConnection = Connection[TaskDependency]
type TaskDependencyEdge = Edge[TaskDependency]
type TaskDependencyListResult = PaginateResult[TaskDependency]

type TaskLabelConnection = Connection[TaskLabel]
type TaskLabelEdge = Edge[TaskLabel]
type TaskLabelListResult = PaginateResult[TaskLabel]

type TaskWatcherConnection = Connection[TaskWatcher]
type TaskWatcherEdge = Edge[TaskWatcher]
type TaskWatcherListResult = PaginateResult[TaskWatcher]

type TeamConnection = Connection[Team]
type TeamEdge = Edge[Team]
type TeamListResult = PaginateResult[Team]

type TeamMemberConnection = Connection[TeamMember]
type TeamMemberEdge = Edge[TeamMember]
type TeamMemberListResult = PaginateResult[TeamMember]

type TimeEntryConnection = Connection[TimeEntry]
type TimeEntryEdge = Edge[TimeEntry]
type TimeEntryListResult = PaginateResult[TimeEntry]

type UserConnection = Connection[User]
type UserEdge = Edge[User]
type UserListResult = PaginateResult[User]

type WorkspaceConnection = Connection[Workspace]
type WorkspaceEdge = Edge[Workspace]
type WorkspaceListResult = PaginateResult[Workspace]

type WorkspaceSettingConnection = Connection[WorkspaceSetting]
type WorkspaceSettingEdge = Edge[WorkspaceSetting]
type WorkspaceSettingListResult = PaginateResult[WorkspaceSetting]
