// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"context"
	"errors"
	"io"
	"uuid"

	"github.com/teandresmith/sqlgen/database"
	"github.com/teandresmith/sqlgen/event"
	"github.com/teandresmith/sqlgen/hook"
	"github.com/teandresmith/sqlgen/tenancy"
)

// ClientOption configures the unified Client during construction.
type ClientOption func(*clientOptions)

// clientOptions holds configuration set via ClientOption functions.
type clientOptions struct {
	callbackMode   database.CallbackMode
	panicHandler   func(ctx context.Context, r any, table hook.TableName, op string) error
	mutationHooks  []hook.MutationHook
	queryHooks     []hook.QueryHook
	eventPublisher event.Publisher
	eventConfig    event.Config
	cache          *Cache
	tenantResolver tenancy.TenantResolver[uuid.UUID]
}

// WithCallbackMode sets the callback execution mode for transactions.
// Default is database.CallbackAsync.
func WithCallbackMode(mode database.CallbackMode) ClientOption {
	return func(o *clientOptions) {
		o.callbackMode = mode
	}
}

// WithPanicHandler sets a custom panic handler for all operations.
// The handler receives the recovered value, table name, and operation,
// and returns the error that the caller will see.
func WithPanicHandler(handler func(ctx context.Context, r any, table hook.TableName, op string) error) ClientOption {
	return func(o *clientOptions) {
		o.panicHandler = handler
	}
}

// WithMutationHook appends a mutation hook to the client's hook chain.
// Hooks execute in registration order (first registered = outermost).
func WithMutationHook(h hook.MutationHook) ClientOption {
	return func(o *clientOptions) {
		o.mutationHooks = append(o.mutationHooks, h)
	}
}

// WithQueryHook appends a query hook to the client's hook chain.
// Hooks execute in registration order (first registered = outermost).
func WithQueryHook(h hook.QueryHook) ClientOption {
	return func(o *clientOptions) {
		o.queryHooks = append(o.queryHooks, h)
	}
}

// WithCache wires a *Cache into the client — shorthand for registering both
// its QueryHook and MutationHook. Cache is the outermost hook in the chain so
// hits short-circuit before any user hook or event hook runs.
func WithCache(c *Cache) ClientOption {
	return func(o *clientOptions) {
		o.cache = c
	}
}

// WithTenantResolver wires the request-scoped tenant resolver into the client.
// All generated reads and mutations on tenanted tables call this resolver at
// method entry and apply the resolved tenant as a WHERE filter / INSERT value.
func WithTenantResolver(r tenancy.TenantResolver[uuid.UUID]) ClientOption {
	return func(o *clientOptions) {
		o.tenantResolver = r
	}
}

// Client is the unified entry point for all database operations.
// All entity clients share the same querier and configuration.
// The Client is safe for concurrent use after construction.
type Client struct {
	querier          database.Querier
	opts             clientOptions
	apiToken         *apiTokenClient
	activity         *activityClient
	attachment       *attachmentClient
	comment          *commentClient
	cycle            *cycleClient
	invitation       *invitationClient
	label            *labelClient
	membership       *membershipClient
	project          *projectClient
	projectStat      *projectStatClient
	ssoConnection    *ssoConnectionClient
	task             *taskClient
	taskAssignee     *taskAssigneeClient
	taskDependency   *taskDependencyClient
	taskLabel        *taskLabelClient
	taskWatcher      *taskWatcherClient
	team             *teamClient
	teamMember       *teamMemberClient
	timeEntry        *timeEntryClient
	user             *userClient
	workspace        *workspaceClient
	workspaceSetting *workspaceSettingClient
}

// New creates a new Client with the given querier and options.
// All entity clients are constructed internally with the shared querier.
func New(querier database.Querier, opts ...ClientOption) *Client {
	options := clientOptions{
		callbackMode: database.CallbackAsync,
	}
	for _, o := range opts {
		o(&options)
	}

	// Prepend event hooks as outermost hooks (before user hooks)
	if options.eventPublisher != nil {
		eventHooks := buildEventHooks(options.eventPublisher, options.eventConfig)
		options.mutationHooks = append(eventHooks, options.mutationHooks...)
	}

	// Prepend cache hooks as the outermost hooks so a hit short-circuits before
	// any event or user hook runs.
	if options.cache != nil {
		options.mutationHooks = append([]hook.MutationHook{options.cache.MutationHook()}, options.mutationHooks...)
		options.queryHooks = append([]hook.QueryHook{options.cache.QueryHook()}, options.queryHooks...)
	}

	c := &Client{
		querier:          querier,
		opts:             options,
		apiToken:         newAPITokenClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		activity:         newActivityClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		attachment:       newAttachmentClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		comment:          newCommentClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		cycle:            newCycleClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		invitation:       newInvitationClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		label:            newLabelClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		membership:       newMembershipClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		project:          newProjectClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		projectStat:      newProjectStatClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		ssoConnection:    newSsoConnectionClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		task:             newTaskClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		taskAssignee:     newTaskAssigneeClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		taskDependency:   newTaskDependencyClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		taskLabel:        newTaskLabelClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		taskWatcher:      newTaskWatcherClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		team:             newTeamClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		teamMember:       newTeamMemberClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		timeEntry:        newTimeEntryClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		user:             newUserClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		workspace:        newWorkspaceClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		workspaceSetting: newWorkspaceSettingClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
	}

	// Thread the tenant resolver into every entity client that needs one. That
	// is a UNION of four conditions, not just "detected as tenanted"
	// (TableContext.NeedsTenantResolver, resolved in finalizeTenancyWiring):
	// the entity is itself tenanted; it has a tenanted O2O child whose filter
	// the parent appends at GetMany time; one of its relationship filters can
	// reach a tenanted target, so compiling it into an EXISTS needs the
	// target's tenant predicate inside the subquery; or it carries a
	// nested-mutation edge writing through a tenanted client, and hoists that
	// write's single resolve.
	//
	// So a client for a NON-tenanted table can legitimately carry a
	// tenantResolver — the field on the entity client is gated on the same
	// union, so field and assignment cannot disagree. Carrying
	// it does not scope that table's own reads: the outer-query tenant filter
	// is emitted only under `and .Tenancy .Tenancy.Tenanted`.
	//
	// Nor does carrying it make such a client fail closed. filterOptions
	// resolves only when the filter it was handed actually sets a relationship
	// member, so a shared table stays readable before any tenant is selected
	// even against a resolver that reports a missing tenant as an error.
	// Past that gate, resolveTenant is emitted in its required:false form, so
	// a zero resolver return leaves the subquery unscoped rather than
	// erroring — a resolver error still propagates.
	c.activity.tenantResolver = options.tenantResolver
	c.apiToken.tenantResolver = options.tenantResolver
	c.attachment.tenantResolver = options.tenantResolver
	c.comment.tenantResolver = options.tenantResolver
	c.cycle.tenantResolver = options.tenantResolver
	c.invitation.tenantResolver = options.tenantResolver
	c.label.tenantResolver = options.tenantResolver
	c.membership.tenantResolver = options.tenantResolver
	c.project.tenantResolver = options.tenantResolver
	c.projectStat.tenantResolver = options.tenantResolver
	c.ssoConnection.tenantResolver = options.tenantResolver
	c.task.tenantResolver = options.tenantResolver
	c.team.tenantResolver = options.tenantResolver
	c.timeEntry.tenantResolver = options.tenantResolver
	c.user.tenantResolver = options.tenantResolver
	c.workspace.tenantResolver = options.tenantResolver
	c.workspaceSetting.tenantResolver = options.tenantResolver

	// Push the configured CallbackMode down to every entity client that can
	// carry a nested-mutation surface: the nested methods open the transaction
	// the whole nested write runs in and pass this mode to it, so
	// deferred events and cache invalidation flush the way the client was
	// configured rather than on NewTransaction's default.
	c.comment.callbackMode = options.callbackMode
	c.cycle.callbackMode = options.callbackMode
	c.label.callbackMode = options.callbackMode
	c.project.callbackMode = options.callbackMode
	c.task.callbackMode = options.callbackMode
	c.team.callbackMode = options.callbackMode
	c.user.callbackMode = options.callbackMode
	c.workspace.callbackMode = options.callbackMode

	// Wire up cross-client references for relationship loading and the clients
	// the nested-mutation executors write through
	c.comment.attachmentClient = c.attachment
	c.cycle.taskClient = c.task
	c.label.taskClient = c.task
	c.label.taskLabelClient = c.taskLabel
	c.project.taskClient = c.task
	c.task.attachmentClient = c.attachment
	c.task.taskClient = c.task
	c.task.commentClient = c.comment
	c.task.timeEntryClient = c.timeEntry
	c.task.userClient = c.user
	c.task.labelClient = c.label
	c.task.taskAssigneeClient = c.taskAssignee
	c.task.taskDependencyClient = c.taskDependency
	c.task.taskLabelClient = c.taskLabel
	c.task.taskWatcherClient = c.taskWatcher
	c.team.cycleClient = c.cycle
	c.team.projectClient = c.project
	c.team.userClient = c.user
	c.team.teamMemberClient = c.teamMember
	c.user.activityClient = c.activity
	c.user.apiTokenClient = c.apiToken
	c.user.attachmentClient = c.attachment
	c.user.commentClient = c.comment
	c.user.invitationClient = c.invitation
	c.user.taskClient = c.task
	c.user.timeEntryClient = c.timeEntry
	c.user.teamClient = c.team
	c.user.workspaceClient = c.workspace
	c.user.membershipClient = c.membership
	c.user.taskAssigneeClient = c.taskAssignee
	c.user.taskWatcherClient = c.taskWatcher
	c.user.teamMemberClient = c.teamMember
	c.workspace.activityClient = c.activity
	c.workspace.apiTokenClient = c.apiToken
	c.workspace.attachmentClient = c.attachment
	c.workspace.commentClient = c.comment
	c.workspace.cycleClient = c.cycle
	c.workspace.invitationClient = c.invitation
	c.workspace.labelClient = c.label
	c.workspace.projectClient = c.project
	c.workspace.ssoConnectionClient = c.ssoConnection
	c.workspace.taskClient = c.task
	c.workspace.teamClient = c.team
	c.workspace.timeEntryClient = c.timeEntry
	c.workspace.userClient = c.user
	c.workspace.membershipClient = c.membership

	return c
}

// APITokens returns the APITokenClient for APIToken operations.
func (c *Client) APITokens() APITokenClient {
	return c.apiToken
}

// Activities returns the ActivityClient for Activity operations.
func (c *Client) Activities() ActivityClient {
	return c.activity
}

// Attachments returns the AttachmentClient for Attachment operations.
func (c *Client) Attachments() AttachmentClient {
	return c.attachment
}

// Comments returns the CommentClient for Comment operations.
func (c *Client) Comments() CommentClient {
	return c.comment
}

// Cycles returns the CycleClient for Cycle operations.
func (c *Client) Cycles() CycleClient {
	return c.cycle
}

// Invitations returns the InvitationClient for Invitation operations.
func (c *Client) Invitations() InvitationClient {
	return c.invitation
}

// Labels returns the LabelClient for Label operations.
func (c *Client) Labels() LabelClient {
	return c.label
}

// Memberships returns the MembershipClient for Membership operations.
func (c *Client) Memberships() MembershipClient {
	return c.membership
}

// Projects returns the ProjectClient for Project operations.
func (c *Client) Projects() ProjectClient {
	return c.project
}

// ProjectStat returns the ProjectStatClient for ProjectStat operations.
func (c *Client) ProjectStat() ProjectStatClient {
	return c.projectStat
}

// SsoConnections returns the SsoConnectionClient for SsoConnection operations.
func (c *Client) SsoConnections() SsoConnectionClient {
	return c.ssoConnection
}

// Tasks returns the TaskClient for Task operations.
func (c *Client) Tasks() TaskClient {
	return c.task
}

// TaskAssignees returns the TaskAssigneeClient for TaskAssignee operations.
func (c *Client) TaskAssignees() TaskAssigneeClient {
	return c.taskAssignee
}

// TaskDependencies returns the TaskDependencyClient for TaskDependency operations.
func (c *Client) TaskDependencies() TaskDependencyClient {
	return c.taskDependency
}

// TaskLabels returns the TaskLabelClient for TaskLabel operations.
func (c *Client) TaskLabels() TaskLabelClient {
	return c.taskLabel
}

// TaskWatchers returns the TaskWatcherClient for TaskWatcher operations.
func (c *Client) TaskWatchers() TaskWatcherClient {
	return c.taskWatcher
}

// Teams returns the TeamClient for Team operations.
func (c *Client) Teams() TeamClient {
	return c.team
}

// TeamMembers returns the TeamMemberClient for TeamMember operations.
func (c *Client) TeamMembers() TeamMemberClient {
	return c.teamMember
}

// TimeEntries returns the TimeEntryClient for TimeEntry operations.
func (c *Client) TimeEntries() TimeEntryClient {
	return c.timeEntry
}

// Users returns the UserClient for User operations.
func (c *Client) Users() UserClient {
	return c.user
}

// Workspaces returns the WorkspaceClient for Workspace operations.
func (c *Client) Workspaces() WorkspaceClient {
	return c.workspace
}

// WorkspaceSettings returns the WorkspaceSettingClient for WorkspaceSetting operations.
func (c *Client) WorkspaceSettings() WorkspaceSettingClient {
	return c.workspaceSetting
}

// Begin starts a new transaction with the given name.
// Delegates to database.NewTransaction with the client's querier.
// The client's configured CallbackMode is applied when the caller does not
// specify one explicitly via TxOptions.
func (c *Client) Begin(ctx context.Context, name string, opts ...database.TxOptions) (context.Context, error) {
	return database.NewTransaction(ctx, c.querier, name, c.applyTxDefaults(opts)...)
}

// applyTxDefaults returns opts with the client's configured CallbackMode
// filled in when the caller did not specify one. A caller-supplied mode
// always wins. Length >1 is passed through so NewTransaction returns its
// normal "at most one TxOptions" error.
func (c *Client) applyTxDefaults(opts []database.TxOptions) []database.TxOptions {
	if len(opts) == 0 {
		return []database.TxOptions{{CallbackMode: c.opts.callbackMode}}
	}
	if len(opts) == 1 && opts[0].CallbackMode == "" {
		merged := opts[0]
		merged.CallbackMode = c.opts.callbackMode
		return []database.TxOptions{merged}
	}
	return opts
}

// Commit commits the active transaction in the context.
// Delegates to database.Commit.
func (c *Client) Commit(ctx context.Context) error {
	return database.Commit(ctx)
}

// Rollback rolls back the active transaction in the context.
// Delegates to database.Rollback.
func (c *Client) Rollback(ctx context.Context) error {
	return database.Rollback(ctx)
}

// WithTx executes fn within a transaction. If fn returns nil, the
// transaction is committed; otherwise it is rolled back.
// Delegates to database.WithTransaction with the client's querier.
// The client's configured CallbackMode is applied when the caller does not
// specify one explicitly via TxOptions.
func (c *Client) WithTx(ctx context.Context, name string, fn func(context.Context) error, opts ...database.TxOptions) error {
	return database.WithTransaction(ctx, c.querier, name, fn, c.applyTxDefaults(opts)...)
}

// Querier returns the active transaction from the context if one exists,
// otherwise the original querier. This is an escape hatch that bypasses
// all hooks.
//
// Inside a transaction the returned Querier is the *database.Tx, so every
// statement through it takes the transaction's connection reservation and
// concurrent use is as safe as through the generated methods. What the
// reservation cannot enforce is the one rule that remains the caller's: drain
// or close a result set before issuing the next statement on that txCtx. A
// caller who holds rows open and then issues another statement is waiting on a
// reservation it holds itself, which surfaces as a wait bounded only by ctx or
// TxOptions.Timeout — neither is set by default — rather than as an immediate
// driver error. database.QueryFunc and database.QueryRowFunc are the spellings
// that cannot leak a result set.
func (c *Client) Querier(ctx context.Context) database.Querier {
	return database.Conn(ctx, c.querier)
}

// sqlgen: raw query bypasses tenancy
// Raw executes a raw query and passes the result set to fn. The rows are
// closed when fn returns, so fn must finish reading them before it does.
// Raw does not wrap an error returned by fn, though a global hook may.
// Pass nil args when there are none.
// Global hooks (tracing, auth) are applied; entity-specific hooks are not.
// Panic recovery always wraps the call, fn included.
//
// fn runs inside the hook chain, so the result set cannot outlive the call:
// inside a transaction, the rows give the connection back before Raw returns,
// and concurrent Raw calls on one transactional ctx serialize. A query hook
// therefore spans the scan, and cannot intercept the rows. When ctx carries a
// transaction, fn is still bound by the one rule that remains the caller's:
// drain or close a result set before issuing the next statement on that txCtx.
// A statement fn issues on it before the rows are drained waits on the
// connection fn's own rows still hold.
func (c *Client) Raw(ctx context.Context, rawSQL string, args []any, fn func(database.Rows) error) error {
	terminal := func(ctx context.Context, _ *hook.QueryContext) (any, error) {
		return nil, database.QueryFunc(ctx, database.Conn(ctx, c.querier), rawSQL, args, fn)
	}
	chain := hook.BuildQueryChain(c.opts.panicHandler, c.opts.queryHooks, terminal)
	_, err := chain(ctx, &hook.QueryContext{
		Op:    hook.QueryOp("raw_query"),
		Input: args,
	})
	return err
}

// sqlgen: raw query bypasses tenancy
// RawExec executes a raw statement and returns the result.
// Global hooks (tracing, auth) are applied; entity-specific hooks are not.
// Panic recovery always wraps the call.
func (c *Client) RawExec(ctx context.Context, rawSQL string, args ...any) (database.Result, error) {
	terminal := func(ctx context.Context, _ *hook.MutationContext) (any, error) {
		return database.Conn(ctx, c.querier).Exec(ctx, rawSQL, args...)
	}
	chain := hook.BuildMutationChain(c.opts.panicHandler, c.opts.mutationHooks, terminal)
	result, err := chain(ctx, &hook.MutationContext{
		Op:    hook.MutationOp("raw_exec"),
		Input: args,
	})
	if err != nil {
		return nil, err
	}
	return result.(database.Result), nil
}

// Ping verifies database connectivity. If the querier implements a native
// Ping(context.Context) error method, it is used directly. Otherwise falls
// back to executing SELECT 1.
func (c *Client) Ping(ctx context.Context) error {
	type pinger interface {
		Ping(ctx context.Context) error
	}
	if p, ok := c.querier.(pinger); ok {
		return p.Ping(ctx)
	}
	row := c.querier.QueryRow(ctx, "SELECT 1")
	var n int
	return row.Scan(&n)
}

// Close closes all closeable dependencies held by the client.
// If a dependency does not implement io.Closer, it is silently skipped.
// All close errors are collected and returned as a joined error.
func (c *Client) Close() error {
	var errs []error
	if closer, ok := c.querier.(io.Closer); ok {
		errs = append(errs, closer.Close())
	}
	return errors.Join(errs...)
}
