// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"encoding/base64"
	"encoding/json"

	"github.com/teandresmith/sqlgen/sql"
)

// ConnectionInput holds parameters for Relay cursor pagination.
type ConnectionInput[F any] struct {
	Filter *F      `json:"filter"`
	First  *int    `json:"first"`
	Last   *int    `json:"last"`
	After  *string `json:"after"`
	Before *string `json:"before"`
}

// Connection holds Relay-style cursor-paginated results.
type Connection[T any] struct {
	Edges      []Edge[T] `json:"edges"`
	PageInfo   PageInfo  `json:"page_info"`
	TotalCount int64     `json:"total_count"` // total matching rows across all pages
}

// Edge wraps a single node with its opaque cursor.
type Edge[T any] struct {
	Node   *T     `json:"node"`
	Cursor string `json:"cursor"`
}

// PageInfo holds pagination metadata following the Relay connection spec.
type PageInfo struct {
	HasNextPage     bool    `json:"has_next_page"`
	HasPreviousPage bool    `json:"has_previous_page"`
	StartCursor     *string `json:"start_cursor"` // nil when the edge list is empty
	EndCursor       *string `json:"end_cursor"`   // nil when the edge list is empty
}

// decodeCursor decodes a base64 JSON cursor string into key-value pairs.
func decodeCursor(s string) (map[string]any, error) {
	data, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		return nil, err
	}
	var cursor map[string]any
	if err := json.Unmarshal(data, &cursor); err != nil {
		return nil, err
	}
	return cursor, nil
}

// cursorKeyset builds a composite keyset condition from decoded cursor values.
// The op parameter is ">" for forward pagination or "<" for backward pagination.
//
// Each key is quoted by the dialect, so a cursor key that is a keyword, mixed
// case or digit-leading still parses. The quoted token is also the condition's
// Column, which is what sql.PrefixConditions qualifies in place on the O2O-join
// read path: `"2024_quota" > $` becomes `d."2024_quota" > $`.
func cursorKeyset(d sql.Dialect, keys []string, cursor map[string]any, op string) sql.Condition {
	compare := func(key, op string) sql.Condition {
		col := d.QuoteIdentifier(key)
		return sql.Condition{Clause: col + " " + op + " $", Value: cursor[key], Column: col}
	}
	if len(keys) == 1 {
		return compare(keys[0], op)
	}
	// Composite keyset: (a, b) > (v1, v2) is expressed as
	// (a > v1) OR (a = v1 AND b > v2)
	// Build this as a single OR condition with nested ANDs.
	orClauses := make([]sql.Condition, 0, len(keys))
	for i := range keys {
		andClauses := make([]sql.Condition, 0, i+1)
		for _, prev := range keys[:i] {
			andClauses = append(andClauses, compare(prev, "="))
		}
		andClauses = append(andClauses, compare(keys[i], op))
		orClauses = append(orClauses, sql.And(andClauses...))
	}
	return sql.Or(orClauses...)
}

// cursorSorts builds ORDER BY clauses from cursor key columns.
// When ascending is true, all columns sort ASC; otherwise DESC.
func cursorSorts(keys []string, ascending bool) []sql.Sort {
	direction := sql.Asc
	if !ascending {
		direction = sql.Desc
	}
	sorts := make([]sql.Sort, len(keys))
	for i, key := range keys {
		sorts[i] = sql.Sort{Column: key, Direction: direction}
	}
	return sorts
}
