// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"database/sql/driver"
	"fmt"
	"io"
	"strings"
)

// AttachmentEntityType — Which entity kind an attachment is bound to
type AttachmentEntityType string

const (
	AttachmentEntityTypeTask    AttachmentEntityType = "task"
	AttachmentEntityTypeComment AttachmentEntityType = "comment"
)

// AllAttachmentEntityType contains all valid AttachmentEntityType values.
var AllAttachmentEntityType = []AttachmentEntityType{
	AttachmentEntityTypeTask,
	AttachmentEntityTypeComment,
}

// String returns the string representation of the AttachmentEntityType.
func (s AttachmentEntityType) String() string { return string(s) }

// ValidateAttachmentEntityType returns a valid AttachmentEntityType or an error if the input
// is not a known value.
func ValidateAttachmentEntityType(s string) (AttachmentEntityType, error) {
	switch AttachmentEntityType(s) {
	case AttachmentEntityTypeTask, AttachmentEntityTypeComment:
		return AttachmentEntityType(s), nil
	default:
		return "", fmt.Errorf("invalid AttachmentEntityType: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AttachmentEntityType) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known AttachmentEntityType.
func (s *AttachmentEntityType) UnmarshalText(b []byte) error {
	v, err := ValidateAttachmentEntityType(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s AttachmentEntityType) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *AttachmentEntityType) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = AttachmentEntityType(v)
		return nil
	case []byte:
		*s = AttachmentEntityType(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into AttachmentEntityType", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s AttachmentEntityType) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case AttachmentEntityTypeTask:
		name = "TASK"
	case AttachmentEntityTypeComment:
		name = "COMMENT"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *AttachmentEntityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for AttachmentEntityType, got %T", v)
	}
	switch str {
	case "TASK":
		*s = AttachmentEntityTypeTask
	case "COMMENT":
		*s = AttachmentEntityTypeComment
	default:
		return fmt.Errorf("invalid AttachmentEntityType: %q", str)
	}
	return nil
}

// AttachmentEntityTypeSlice represents a PostgreSQL array of AttachmentEntityType values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type AttachmentEntityTypeSlice []AttachmentEntityType

// String returns the PostgreSQL array literal representation.
func (s AttachmentEntityTypeSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s AttachmentEntityTypeSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *AttachmentEntityTypeSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into AttachmentEntityTypeSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = AttachmentEntityTypeSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(AttachmentEntityTypeSlice, len(parts))
	for i, p := range parts {
		result[i] = AttachmentEntityType(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[AttachmentEntityType!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s AttachmentEntityTypeSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[AttachmentEntityType!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *AttachmentEntityTypeSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for AttachmentEntityTypeSlice, got %T", v)
	}
	out := make(AttachmentEntityTypeSlice, 0, len(raw))
	for i, item := range raw {
		var elem AttachmentEntityType
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("AttachmentEntityTypeSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}

// CycleStatus — Lifecycle state of a planning cycle
type CycleStatus string

const (
	CycleStatusUpcoming  CycleStatus = "upcoming"
	CycleStatusActive    CycleStatus = "active"
	CycleStatusCompleted CycleStatus = "completed"
)

// AllCycleStatus contains all valid CycleStatus values.
var AllCycleStatus = []CycleStatus{
	CycleStatusUpcoming,
	CycleStatusActive,
	CycleStatusCompleted,
}

// String returns the string representation of the CycleStatus.
func (s CycleStatus) String() string { return string(s) }

// ValidateCycleStatus returns a valid CycleStatus or an error if the input
// is not a known value.
func ValidateCycleStatus(s string) (CycleStatus, error) {
	switch CycleStatus(s) {
	case CycleStatusUpcoming, CycleStatusActive, CycleStatusCompleted:
		return CycleStatus(s), nil
	default:
		return "", fmt.Errorf("invalid CycleStatus: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CycleStatus) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known CycleStatus.
func (s *CycleStatus) UnmarshalText(b []byte) error {
	v, err := ValidateCycleStatus(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s CycleStatus) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *CycleStatus) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = CycleStatus(v)
		return nil
	case []byte:
		*s = CycleStatus(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into CycleStatus", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s CycleStatus) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case CycleStatusUpcoming:
		name = "UPCOMING"
	case CycleStatusActive:
		name = "ACTIVE"
	case CycleStatusCompleted:
		name = "COMPLETED"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *CycleStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for CycleStatus, got %T", v)
	}
	switch str {
	case "UPCOMING":
		*s = CycleStatusUpcoming
	case "ACTIVE":
		*s = CycleStatusActive
	case "COMPLETED":
		*s = CycleStatusCompleted
	default:
		return fmt.Errorf("invalid CycleStatus: %q", str)
	}
	return nil
}

// CycleStatusSlice represents a PostgreSQL array of CycleStatus values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type CycleStatusSlice []CycleStatus

// String returns the PostgreSQL array literal representation.
func (s CycleStatusSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s CycleStatusSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *CycleStatusSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into CycleStatusSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = CycleStatusSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(CycleStatusSlice, len(parts))
	for i, p := range parts {
		result[i] = CycleStatus(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[CycleStatus!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s CycleStatusSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[CycleStatus!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *CycleStatusSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for CycleStatusSlice, got %T", v)
	}
	out := make(CycleStatusSlice, 0, len(raw))
	for i, item := range raw {
		var elem CycleStatus
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("CycleStatusSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}

// DependencyType — Nature of a task-to-task dependency
type DependencyType string

const (
	DependencyTypeBlocks     DependencyType = "blocks"
	DependencyTypeRelatesTo  DependencyType = "relates_to"
	DependencyTypeDuplicates DependencyType = "duplicates"
)

// AllDependencyType contains all valid DependencyType values.
var AllDependencyType = []DependencyType{
	DependencyTypeBlocks,
	DependencyTypeRelatesTo,
	DependencyTypeDuplicates,
}

// String returns the string representation of the DependencyType.
func (s DependencyType) String() string { return string(s) }

// ValidateDependencyType returns a valid DependencyType or an error if the input
// is not a known value.
func ValidateDependencyType(s string) (DependencyType, error) {
	switch DependencyType(s) {
	case DependencyTypeBlocks, DependencyTypeRelatesTo, DependencyTypeDuplicates:
		return DependencyType(s), nil
	default:
		return "", fmt.Errorf("invalid DependencyType: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DependencyType) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known DependencyType.
func (s *DependencyType) UnmarshalText(b []byte) error {
	v, err := ValidateDependencyType(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s DependencyType) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *DependencyType) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = DependencyType(v)
		return nil
	case []byte:
		*s = DependencyType(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into DependencyType", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s DependencyType) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case DependencyTypeBlocks:
		name = "BLOCKS"
	case DependencyTypeRelatesTo:
		name = "RELATES_TO"
	case DependencyTypeDuplicates:
		name = "DUPLICATES"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *DependencyType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for DependencyType, got %T", v)
	}
	switch str {
	case "BLOCKS":
		*s = DependencyTypeBlocks
	case "RELATES_TO":
		*s = DependencyTypeRelatesTo
	case "DUPLICATES":
		*s = DependencyTypeDuplicates
	default:
		return fmt.Errorf("invalid DependencyType: %q", str)
	}
	return nil
}

// DependencyTypeSlice represents a PostgreSQL array of DependencyType values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type DependencyTypeSlice []DependencyType

// String returns the PostgreSQL array literal representation.
func (s DependencyTypeSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s DependencyTypeSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *DependencyTypeSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into DependencyTypeSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = DependencyTypeSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(DependencyTypeSlice, len(parts))
	for i, p := range parts {
		result[i] = DependencyType(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[DependencyType!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s DependencyTypeSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[DependencyType!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *DependencyTypeSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for DependencyTypeSlice, got %T", v)
	}
	out := make(DependencyTypeSlice, 0, len(raw))
	for i, item := range raw {
		var elem DependencyType
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("DependencyTypeSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}

// InvitationStatus — Lifecycle state of a workspace invitation
type InvitationStatus string

const (
	InvitationStatusPending  InvitationStatus = "pending"
	InvitationStatusAccepted InvitationStatus = "accepted"
	InvitationStatusRevoked  InvitationStatus = "revoked"
	InvitationStatusExpired  InvitationStatus = "expired"
)

// AllInvitationStatus contains all valid InvitationStatus values.
var AllInvitationStatus = []InvitationStatus{
	InvitationStatusPending,
	InvitationStatusAccepted,
	InvitationStatusRevoked,
	InvitationStatusExpired,
}

// String returns the string representation of the InvitationStatus.
func (s InvitationStatus) String() string { return string(s) }

// ValidateInvitationStatus returns a valid InvitationStatus or an error if the input
// is not a known value.
func ValidateInvitationStatus(s string) (InvitationStatus, error) {
	switch InvitationStatus(s) {
	case InvitationStatusPending, InvitationStatusAccepted, InvitationStatusRevoked, InvitationStatusExpired:
		return InvitationStatus(s), nil
	default:
		return "", fmt.Errorf("invalid InvitationStatus: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s InvitationStatus) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known InvitationStatus.
func (s *InvitationStatus) UnmarshalText(b []byte) error {
	v, err := ValidateInvitationStatus(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s InvitationStatus) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *InvitationStatus) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = InvitationStatus(v)
		return nil
	case []byte:
		*s = InvitationStatus(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into InvitationStatus", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s InvitationStatus) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case InvitationStatusPending:
		name = "PENDING"
	case InvitationStatusAccepted:
		name = "ACCEPTED"
	case InvitationStatusRevoked:
		name = "REVOKED"
	case InvitationStatusExpired:
		name = "EXPIRED"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *InvitationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for InvitationStatus, got %T", v)
	}
	switch str {
	case "PENDING":
		*s = InvitationStatusPending
	case "ACCEPTED":
		*s = InvitationStatusAccepted
	case "REVOKED":
		*s = InvitationStatusRevoked
	case "EXPIRED":
		*s = InvitationStatusExpired
	default:
		return fmt.Errorf("invalid InvitationStatus: %q", str)
	}
	return nil
}

// InvitationStatusSlice represents a PostgreSQL array of InvitationStatus values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type InvitationStatusSlice []InvitationStatus

// String returns the PostgreSQL array literal representation.
func (s InvitationStatusSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s InvitationStatusSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *InvitationStatusSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into InvitationStatusSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = InvitationStatusSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(InvitationStatusSlice, len(parts))
	for i, p := range parts {
		result[i] = InvitationStatus(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[InvitationStatus!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s InvitationStatusSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[InvitationStatus!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *InvitationStatusSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for InvitationStatusSlice, got %T", v)
	}
	out := make(InvitationStatusSlice, 0, len(raw))
	for i, item := range raw {
		var elem InvitationStatus
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("InvitationStatusSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}

// MembershipRole — A user's permission level within a workspace
type MembershipRole string

const (
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleAdmin  MembershipRole = "admin"
	MembershipRoleMember MembershipRole = "member"
	MembershipRoleGuest  MembershipRole = "guest"
)

// AllMembershipRole contains all valid MembershipRole values.
var AllMembershipRole = []MembershipRole{
	MembershipRoleOwner,
	MembershipRoleAdmin,
	MembershipRoleMember,
	MembershipRoleGuest,
}

// String returns the string representation of the MembershipRole.
func (s MembershipRole) String() string { return string(s) }

// ValidateMembershipRole returns a valid MembershipRole or an error if the input
// is not a known value.
func ValidateMembershipRole(s string) (MembershipRole, error) {
	switch MembershipRole(s) {
	case MembershipRoleOwner, MembershipRoleAdmin, MembershipRoleMember, MembershipRoleGuest:
		return MembershipRole(s), nil
	default:
		return "", fmt.Errorf("invalid MembershipRole: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MembershipRole) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known MembershipRole.
func (s *MembershipRole) UnmarshalText(b []byte) error {
	v, err := ValidateMembershipRole(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s MembershipRole) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *MembershipRole) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = MembershipRole(v)
		return nil
	case []byte:
		*s = MembershipRole(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into MembershipRole", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s MembershipRole) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case MembershipRoleOwner:
		name = "OWNER"
	case MembershipRoleAdmin:
		name = "ADMIN"
	case MembershipRoleMember:
		name = "MEMBER"
	case MembershipRoleGuest:
		name = "GUEST"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *MembershipRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for MembershipRole, got %T", v)
	}
	switch str {
	case "OWNER":
		*s = MembershipRoleOwner
	case "ADMIN":
		*s = MembershipRoleAdmin
	case "MEMBER":
		*s = MembershipRoleMember
	case "GUEST":
		*s = MembershipRoleGuest
	default:
		return fmt.Errorf("invalid MembershipRole: %q", str)
	}
	return nil
}

// MembershipRoleSlice represents a PostgreSQL array of MembershipRole values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type MembershipRoleSlice []MembershipRole

// String returns the PostgreSQL array literal representation.
func (s MembershipRoleSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s MembershipRoleSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *MembershipRoleSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into MembershipRoleSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = MembershipRoleSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(MembershipRoleSlice, len(parts))
	for i, p := range parts {
		result[i] = MembershipRole(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[MembershipRole!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s MembershipRoleSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[MembershipRole!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *MembershipRoleSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for MembershipRoleSlice, got %T", v)
	}
	out := make(MembershipRoleSlice, 0, len(raw))
	for i, item := range raw {
		var elem MembershipRole
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("MembershipRoleSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}

// SsoProvider — Identity provider protocol/vendor for SSO
type SsoProvider string

const (
	SsoProviderSaml   SsoProvider = "saml"
	SsoProviderOidc   SsoProvider = "oidc"
	SsoProviderGoogle SsoProvider = "google"
	SsoProviderOkta   SsoProvider = "okta"
)

// AllSsoProvider contains all valid SsoProvider values.
var AllSsoProvider = []SsoProvider{
	SsoProviderSaml,
	SsoProviderOidc,
	SsoProviderGoogle,
	SsoProviderOkta,
}

// String returns the string representation of the SsoProvider.
func (s SsoProvider) String() string { return string(s) }

// ValidateSsoProvider returns a valid SsoProvider or an error if the input
// is not a known value.
func ValidateSsoProvider(s string) (SsoProvider, error) {
	switch SsoProvider(s) {
	case SsoProviderSaml, SsoProviderOidc, SsoProviderGoogle, SsoProviderOkta:
		return SsoProvider(s), nil
	default:
		return "", fmt.Errorf("invalid SsoProvider: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SsoProvider) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known SsoProvider.
func (s *SsoProvider) UnmarshalText(b []byte) error {
	v, err := ValidateSsoProvider(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s SsoProvider) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *SsoProvider) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = SsoProvider(v)
		return nil
	case []byte:
		*s = SsoProvider(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into SsoProvider", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s SsoProvider) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case SsoProviderSaml:
		name = "SAML"
	case SsoProviderOidc:
		name = "OIDC"
	case SsoProviderGoogle:
		name = "GOOGLE"
	case SsoProviderOkta:
		name = "OKTA"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *SsoProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for SsoProvider, got %T", v)
	}
	switch str {
	case "SAML":
		*s = SsoProviderSaml
	case "OIDC":
		*s = SsoProviderOidc
	case "GOOGLE":
		*s = SsoProviderGoogle
	case "OKTA":
		*s = SsoProviderOkta
	default:
		return fmt.Errorf("invalid SsoProvider: %q", str)
	}
	return nil
}

// SsoProviderSlice represents a PostgreSQL array of SsoProvider values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type SsoProviderSlice []SsoProvider

// String returns the PostgreSQL array literal representation.
func (s SsoProviderSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s SsoProviderSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *SsoProviderSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into SsoProviderSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = SsoProviderSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(SsoProviderSlice, len(parts))
	for i, p := range parts {
		result[i] = SsoProvider(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[SsoProvider!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s SsoProviderSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[SsoProvider!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *SsoProviderSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for SsoProviderSlice, got %T", v)
	}
	out := make(SsoProviderSlice, 0, len(raw))
	for i, item := range raw {
		var elem SsoProvider
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("SsoProviderSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}

// TaskPriority — Relative urgency of a task
type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityUrgent TaskPriority = "urgent"
)

// AllTaskPriority contains all valid TaskPriority values.
var AllTaskPriority = []TaskPriority{
	TaskPriorityLow,
	TaskPriorityMedium,
	TaskPriorityHigh,
	TaskPriorityUrgent,
}

// String returns the string representation of the TaskPriority.
func (s TaskPriority) String() string { return string(s) }

// ValidateTaskPriority returns a valid TaskPriority or an error if the input
// is not a known value.
func ValidateTaskPriority(s string) (TaskPriority, error) {
	switch TaskPriority(s) {
	case TaskPriorityLow, TaskPriorityMedium, TaskPriorityHigh, TaskPriorityUrgent:
		return TaskPriority(s), nil
	default:
		return "", fmt.Errorf("invalid TaskPriority: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TaskPriority) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known TaskPriority.
func (s *TaskPriority) UnmarshalText(b []byte) error {
	v, err := ValidateTaskPriority(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s TaskPriority) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *TaskPriority) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = TaskPriority(v)
		return nil
	case []byte:
		*s = TaskPriority(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into TaskPriority", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s TaskPriority) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case TaskPriorityLow:
		name = "LOW"
	case TaskPriorityMedium:
		name = "MEDIUM"
	case TaskPriorityHigh:
		name = "HIGH"
	case TaskPriorityUrgent:
		name = "URGENT"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *TaskPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for TaskPriority, got %T", v)
	}
	switch str {
	case "LOW":
		*s = TaskPriorityLow
	case "MEDIUM":
		*s = TaskPriorityMedium
	case "HIGH":
		*s = TaskPriorityHigh
	case "URGENT":
		*s = TaskPriorityUrgent
	default:
		return fmt.Errorf("invalid TaskPriority: %q", str)
	}
	return nil
}

// TaskPrioritySlice represents a PostgreSQL array of TaskPriority values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type TaskPrioritySlice []TaskPriority

// String returns the PostgreSQL array literal representation.
func (s TaskPrioritySlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s TaskPrioritySlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *TaskPrioritySlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into TaskPrioritySlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = TaskPrioritySlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(TaskPrioritySlice, len(parts))
	for i, p := range parts {
		result[i] = TaskPriority(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[TaskPriority!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s TaskPrioritySlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[TaskPriority!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *TaskPrioritySlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for TaskPrioritySlice, got %T", v)
	}
	out := make(TaskPrioritySlice, 0, len(raw))
	for i, item := range raw {
		var elem TaskPriority
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("TaskPrioritySlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}

// TaskStatus — Lifecycle state of a task
type TaskStatus string

const (
	TaskStatusBacklog    TaskStatus = "backlog"
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusInReview   TaskStatus = "in_review"
	TaskStatusDone       TaskStatus = "done"
	TaskStatusCanceled   TaskStatus = "canceled"
)

// AllTaskStatus contains all valid TaskStatus values.
var AllTaskStatus = []TaskStatus{
	TaskStatusBacklog,
	TaskStatusTodo,
	TaskStatusInProgress,
	TaskStatusInReview,
	TaskStatusDone,
	TaskStatusCanceled,
}

// String returns the string representation of the TaskStatus.
func (s TaskStatus) String() string { return string(s) }

// ValidateTaskStatus returns a valid TaskStatus or an error if the input
// is not a known value.
func ValidateTaskStatus(s string) (TaskStatus, error) {
	switch TaskStatus(s) {
	case TaskStatusBacklog, TaskStatusTodo, TaskStatusInProgress, TaskStatusInReview, TaskStatusDone, TaskStatusCanceled:
		return TaskStatus(s), nil
	default:
		return "", fmt.Errorf("invalid TaskStatus: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TaskStatus) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known TaskStatus.
func (s *TaskStatus) UnmarshalText(b []byte) error {
	v, err := ValidateTaskStatus(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s TaskStatus) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *TaskStatus) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = TaskStatus(v)
		return nil
	case []byte:
		*s = TaskStatus(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into TaskStatus", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s TaskStatus) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case TaskStatusBacklog:
		name = "BACKLOG"
	case TaskStatusTodo:
		name = "TODO"
	case TaskStatusInProgress:
		name = "IN_PROGRESS"
	case TaskStatusInReview:
		name = "IN_REVIEW"
	case TaskStatusDone:
		name = "DONE"
	case TaskStatusCanceled:
		name = "CANCELED"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for TaskStatus, got %T", v)
	}
	switch str {
	case "BACKLOG":
		*s = TaskStatusBacklog
	case "TODO":
		*s = TaskStatusTodo
	case "IN_PROGRESS":
		*s = TaskStatusInProgress
	case "IN_REVIEW":
		*s = TaskStatusInReview
	case "DONE":
		*s = TaskStatusDone
	case "CANCELED":
		*s = TaskStatusCanceled
	default:
		return fmt.Errorf("invalid TaskStatus: %q", str)
	}
	return nil
}

// TaskStatusSlice represents a PostgreSQL array of TaskStatus values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type TaskStatusSlice []TaskStatus

// String returns the PostgreSQL array literal representation.
func (s TaskStatusSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s TaskStatusSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *TaskStatusSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into TaskStatusSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = TaskStatusSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(TaskStatusSlice, len(parts))
	for i, p := range parts {
		result[i] = TaskStatus(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[TaskStatus!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s TaskStatusSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[TaskStatus!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *TaskStatusSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for TaskStatusSlice, got %T", v)
	}
	out := make(TaskStatusSlice, 0, len(raw))
	for i, item := range raw {
		var elem TaskStatus
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("TaskStatusSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}
