// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"github.com/teandresmith/sqlgen/database"
)

// Sentinel errors re-exported from the database package for consumer convenience.
// Check with errors.Is().
var (
	// ErrNotFound is returned when Get/Exists finds no matching row.
	ErrNotFound = database.ErrNotFound

	// ErrEmptyFilter is returned when any *Where operation is called with a nil
	// or empty filter. Prevents accidental bulk operations.
	ErrEmptyFilter = database.ErrEmptyFilter

	// ErrNilInput is returned when a write is called with a nil input pointer
	// — Create, Update, Upsert, UpdateWhere, or a nil element in a
	// CreateMany / UpdateMany batch. Reads normalize a nil input to the zero
	// value; a write cannot, since a zero Create<T>Input legally writes a row:
	// each required field's zero value, or with no required field, every
	// column's default.
	ErrNilInput = database.ErrNilInput

	// ErrAmbiguousFilter is returned when a filter contains both And and Or
	// conditions at the same level, making the intent unclear.
	ErrAmbiguousFilter = database.ErrAmbiguousFilter

	// ErrInvalidCursor is returned when a pagination cursor cannot be decoded,
	// parsed, or does not contain the expected keys.
	ErrInvalidCursor = database.ErrInvalidCursor

	// ErrDeadlock is returned when the database detects a deadlock between
	// concurrent transactions and aborts this one.
	ErrDeadlock = database.ErrDeadlock

	// ErrConnectionFailed is returned when a database operation fails due to
	// a connection-level error.
	ErrConnectionFailed = database.ErrConnectionFailed

	// ErrConstraintViolation is the base error for all constraint failures.
	// Use errors.As() to extract the specific ConstraintError.
	ErrConstraintViolation = database.ErrConstraintViolation

	// ErrAlreadyRelated is returned when a nested `connect` names a target
	// already parented to a different row and the edge does not set
	// allow_reparent, or when a has-one `create` or `connect` finds the parent
	// already holding a different child.
	ErrAlreadyRelated = database.ErrAlreadyRelated

	// ErrNestedVerbConflict is returned before any statement on the edge runs when one
	// nested block names the same target under two verbs, or when a
	// self-referential edge names the parent's own primary key.
	ErrNestedVerbConflict = database.ErrNestedVerbConflict
)

// ConstraintError is a type alias for database.ConstraintError.
// Use errors.As() to extract structured constraint violation details.
type ConstraintError = database.ConstraintError

// ConstraintType identifies the kind of database constraint that was violated.
type ConstraintType = database.ConstraintType

// NestedMutationError is a type alias for database.NestedMutationError.
// Use errors.As() to read the failing edge, verb and target id off a nested
// mutation failure instead of parsing them out of the message.
type NestedMutationError = database.NestedMutationError

const (
	ConstraintUnique     = database.ConstraintUnique
	ConstraintForeignKey = database.ConstraintForeignKey
	ConstraintCheck      = database.ConstraintCheck
	ConstraintNotNull    = database.ConstraintNotNull
)
