// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"embed"
	"io/fs"

	"github.com/teandresmith/sqlgen/manifest"
)

//go:embed manifest/manifest_gen.json
var sqlgenManifestFS embed.FS

var (
	sqlgenManifestDoc      manifest.Document
	sqlgenManifestEntities = map[string]*manifest.Entity{}
	sqlgenManifestVersion  string
)

func init() {
	raw, err := sqlgenManifestFS.ReadFile("manifest/manifest_gen.json")
	if err != nil {
		panic(err)
	}

	var entityFS fs.FS

	if err := manifest.LoadInto(raw, entityFS, &sqlgenManifestDoc, sqlgenManifestEntities); err != nil {
		panic(err)
	}
	sqlgenManifestVersion = sqlgenManifestDoc.SchemaVersion
}

// Manifest returns the parsed manifest document. It is pre-parsed at package
// init and safe for concurrent reads. The document's Entities slice is the
// lightweight index form; use ManifestEntity for full entity records — the
// lookup is layout-agnostic.
func (c *Client) Manifest() *manifest.Document {
	return &sqlgenManifestDoc
}

// ManifestEntity returns the full record for the given SQL table name,
// identically across the single and per_entity disk layouts. It returns
// (nil, manifest.ErrEntityNotFound) for unknown tables.
func (c *Client) ManifestEntity(table string) (*manifest.Entity, error) {
	e, ok := sqlgenManifestEntities[table]
	if !ok {
		return nil, manifest.ErrEntityNotFound
	}
	return e, nil
}

// ManifestVersion returns the manifest schema_version string, pre-extracted at
// init for cheap drift detection without walking the full document.
func (c *Client) ManifestVersion() string {
	return sqlgenManifestVersion
}
