// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"github.com/teandresmith/sqlgen/sql"
)

// PaginateInput holds parameters for offset-based pagination.
type PaginateInput[F any] struct {
	Filter *F         `json:"filter"`
	Sort   []sql.Sort `json:"sort"`
	Limit  int        `json:"limit"`
	Offset int        `json:"offset"`
}

// PaginateResult holds the result of an offset-based pagination query.
type PaginateResult[T any] struct {
	Items      []*T  `json:"items"`       // entities for the current page
	TotalCount int64 `json:"total_count"` // total matching rows across all pages
	Offset     int   `json:"offset"`      // the offset used for this query
	Limit      int   `json:"limit"`       // the limit used for this query
	HasMore    bool  `json:"has_more"`    // true when Offset+Limit < TotalCount
}
