// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"database/sql/driver"
	"fmt"
	"slices"
	"strconv"
	"time"
	"uuid"

	"github.com/teandresmith/sqlgen/sql"
)

// CallOptions controls per-call behavior overrides.
type CallOptions[FO any] struct {
	SkipCache          bool         `json:"skip_cache"`           // bypass cache read-through and write-through
	SkipEvents         bool         `json:"skip_events"`          // suppress event publishing for this mutation
	SkipHooks          bool         `json:"skip_hooks"`           // bypass all hooks except panic recovery
	SkipTenancy        bool         `json:"skip_tenancy"`         // bypass tenant auto-filter and mutation mismatch check; orthogonal to SkipHooks
	Tenant             *uuid.UUID   `json:"tenant"`               // explicit tenant: resolve tenancy to this value (filter + auto-set) instead of the ctx resolver; wins over SkipTenancy; nil = unset
	FieldOptions       *FO          `json:"field_options"`        // column selection and relationship loading
	LockMode           sql.LockMode `json:"lock_mode"`            // row-level lock clause for read methods
	AllowInTransaction bool         `json:"allow_in_transaction"` // permit Stream inside a transaction; commits the caller to issuing nothing else on that txCtx
}

// IncrementInput holds parameters for atomic column increment/decrement.
type IncrementInput[C ~string] struct {
	Column C   `json:"column"`
	Amount int `json:"amount"`
}

// excludeColumns returns columns with any entries in exclude removed.
func excludeColumns(columns, exclude []string) []string {
	excludeSet := make(map[string]bool, len(exclude))
	for _, e := range exclude {
		excludeSet[e] = true
	}
	var result []string
	for _, c := range columns {
		if !excludeSet[c] {
			result = append(result, c)
		}
	}
	return result
}

// nestedChildOptions copies the option fields that cross a table boundary
// on a nested mutation. FieldOptions, LockMode and AllowInTransaction
// deliberately do not propagate: the inner calls select nothing, take no row
// lock, and issue no Stream.
func nestedChildOptions[FO, PFO any](o *CallOptions[FO], parent CallOptions[PFO]) {
	o.SkipCache, o.SkipEvents = parent.SkipCache, parent.SkipEvents
	o.SkipHooks = parent.SkipHooks
	o.SkipTenancy = parent.SkipTenancy
	o.Tenant = parent.Tenant
}

// nestedError attributes a nested-mutation failure to its edge and verb.
// The wrapped error is untouched, so errors.Is against the
// sentinels and the *ConstraintError dispatch keep working through it; id is
// nil when the failure is not id-scoped.
func nestedError(edge, verb string, id any, err error) error {
	return &NestedMutationError{Edge: edge, Verb: verb, ID: id, Err: err}
}

// resolveCallOptions applies option functions and returns the resolved struct. SkipHooks implies SkipCache and SkipEvents because cache and events are implemented as hooks.
func resolveCallOptions[FO any](opts []func(*CallOptions[FO])) CallOptions[FO] {
	var options CallOptions[FO]
	for _, fn := range opts {
		fn(&options)
	}
	// SkipHooks implies SkipCache and SkipEvents — cache and events are hooks.
	if options.SkipHooks {
		options.SkipCache = true
		options.SkipEvents = true
	}
	// Explicit tenant wins over SkipTenancy
	// — the call runs scoped to the explicit tenant.
	if options.Tenant != nil {
		options.SkipTenancy = false
	}
	return options
}

// toAnySlice converts a typed slice to []any for variadic query args.
func toAnySlice[T any](s []T) []any {
	result := make([]any, len(s))
	for i, v := range s {
		result[i] = v
	}
	return result
}

// unionColumns returns columns plus any required column it does not already
// carry, re-sorted. A narrowed projection reaches this whenever the call needs
// a column the caller did not select — a cursor key, a relationship mapping
// key — and the result is re-sorted because the SQL builder emits columns
// sorted and the scan functions match positionally against this slice.
// Returns columns unchanged when nothing is missing.
func unionColumns(columns []string, required ...string) []string {
	var missing []string
	for _, r := range required {
		if !slices.Contains(columns, r) && !slices.Contains(missing, r) {
			missing = append(missing, r)
		}
	}
	if len(missing) == 0 {
		return columns
	}
	result := make([]string, 0, len(columns)+len(missing))
	result = append(result, columns...)
	result = append(result, missing...)
	slices.Sort(result)
	return result
}

// upsertConflictPositions maps each column of an upsert conflict target to its
// position in an UpsertMany value row. Reports false when the target is empty
// or names a column the statement does not supply — neither can identify a row,
// so the caller must not dedupe on it and cannot look a written row up by it.
func upsertConflictPositions(columns, conflictColumns []string) ([]int, bool) {
	if len(conflictColumns) == 0 {
		return nil, false
	}
	positions := make([]int, 0, len(conflictColumns))
	for _, col := range conflictColumns {
		i := slices.Index(columns, col)
		if i < 0 {
			return nil, false
		}
		positions = append(positions, i)
	}
	return positions, true
}

// upsertDedupeKey builds the identity of one UpsertMany value row over its
// conflict target's columns, for the last-wins dedupe UpsertMany requires.
// Components are length-prefixed so two different column splits cannot produce
// one key.
//
// Reports false when the row carries no definite, non-NULL value for every
// conflict column — a DEFAULT the database has not yet evaluated, a NULL (which
// never matches under a unique index on any of the three dialects), or a Go type
// the driver cannot bind on its own. Such a row cannot be shown to collide
// in-statement, so it is kept rather than deduped.
func upsertDedupeKey(row []any, positions []int) (string, bool) {
	key := ""
	for _, pos := range positions {
		v := row[pos]
		if v == sql.Default {
			return "", false
		}
		if _, ok := v.(sql.DefaultExpr); ok {
			return "", false
		}
		// The driver's own parameter conversion is the right notion of
		// identity: it is what the value binds as, so two values that bind
		// identically key identically. It also dereferences the pointer a
		// nullable column binds through — %v on a *string prints an address —
		// and reports nil for a NULL, which never matches under a unique index.
		bound, err := driver.DefaultParameterConverter.ConvertValue(v)
		if err != nil || bound == nil {
			return "", false
		}
		if t, ok := bound.(time.Time); ok {
			// Drop the monotonic reading and the sub-microsecond tail no
			// dialect stores, so a caller's time.Now() keys the same as the
			// value read back from the row it wrote.
			bound = t.UTC().Truncate(time.Microsecond).Format(time.RFC3339Nano)
		}
		s := fmt.Sprintf("%v", bound)
		key += fmt.Sprintf("%d:%s", len(s), s)
	}
	return key, true
}

// FilterOption carries the per-call data a filter needs, beyond the dialect,
// to compile its relationship members into correlated EXISTS subqueries.
// Generated client methods supply the set; ToConditions threads it through
// And/Or composition and down into each relationship member.
type FilterOption func(*filterScope)

// filterScope is a resolved FilterOption set.
type filterScope struct {
	depth       int
	tenant      uuid.UUID
	applyTenant bool
}

// resolveFilterScope applies option functions and returns the resolved scope.
func resolveFilterScope(opts []FilterOption) filterScope {
	var scope filterScope
	for _, fn := range opts {
		fn(&scope)
	}
	return scope
}

// nestFilterScope returns opts with the subquery depth set to depth, for the
// next level of relationship nesting. The set is copied rather than appended in
// place so two relationship members compiled from the same filter cannot write
// through each other's backing array.
func nestFilterScope(opts []FilterOption, depth int) []FilterOption {
	nested := make([]FilterOption, len(opts), len(opts)+1)
	copy(nested, opts)
	return append(nested, func(s *filterScope) {
		s.depth = depth
	})
}

// filterSubqueryAlias returns the table alias a relationship filter's subquery
// uses at the given nesting depth. Distinct per level, so an inner subquery
// never shadows the alias its own correlation reference resolves against.
func filterSubqueryAlias(prefix string, depth int) string {
	return prefix + strconv.Itoa(depth)
}

// WithFilterTenant scopes the relationship subqueries a filter compiles to
// tenant, so a relationship filter reads the related table under the same
// tenant predicate the table's own read path applies. Generated read and filter-accepting mutation methods pass it
// automatically from the resolved tenant; converting a filter without it
// produces subqueries scoped as if CallOptions.SkipTenancy were set.
func WithFilterTenant(tenant uuid.UUID) FilterOption {
	return func(s *filterScope) {
		s.tenant = tenant
		s.applyTenant = true
	}
}
