// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"github.com/teandresmith/sqlgen/hook"
)

const (
	TableActivities        hook.TableName = "public.activity"
	TableAPITokens         hook.TableName = "public.api_tokens"
	TableAttachments       hook.TableName = "public.attachments"
	TableComments          hook.TableName = "public.comments"
	TableCycles            hook.TableName = "public.cycles"
	TableInvitations       hook.TableName = "public.invitations"
	TableLabels            hook.TableName = "public.labels"
	TableMemberships       hook.TableName = "public.memberships"
	TableProjects          hook.TableName = "public.projects"
	TableSsoConnections    hook.TableName = "public.sso_connections"
	TableTaskAssignees     hook.TableName = "public.task_assignees"
	TableTaskDependencies  hook.TableName = "public.task_dependencies"
	TableTaskLabels        hook.TableName = "public.task_labels"
	TableTaskWatchers      hook.TableName = "public.task_watchers"
	TableTasks             hook.TableName = "public.tasks"
	TableTeamMembers       hook.TableName = "public.team_members"
	TableTeams             hook.TableName = "public.teams"
	TableTimeEntries       hook.TableName = "public.time_entries"
	TableUsers             hook.TableName = "public.users"
	TableWorkspaceSettings hook.TableName = "public.workspace_settings"
	TableWorkspaces        hook.TableName = "public.workspaces"
	TableProjectStats      hook.TableName = "public.project_stats"
)
