// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package database

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"iter"
	"slices"
	"time"
	"uuid"

	"github.com/jackc/pgx/v5"
	"github.com/teandresmith/sqlgen/comparator"
	"github.com/teandresmith/sqlgen/database"
	"github.com/teandresmith/sqlgen/hook"
	"github.com/teandresmith/sqlgen/omittable"
	"github.com/teandresmith/sqlgen/sql"
)

// TaskDependencyPK - composite primary key for the task_dependencies table.
type TaskDependencyPK struct {
	// TaskID - The dependent task
	TaskID uuid.UUID `db:"task_id" json:"task_id"`
	// DependsOnTaskID - The task depended upon
	DependsOnTaskID uuid.UUID `db:"depends_on_task_id" json:"depends_on_task_id"`
}

// TaskDependency - Directed dependencies between tasks (self-referential M2M)
type TaskDependency struct {
	// TaskID - The dependent task
	TaskID uuid.UUID `db:"task_id" json:"task_id"`
	// DependsOnTaskID - The task depended upon
	DependsOnTaskID uuid.UUID `db:"depends_on_task_id" json:"depends_on_task_id"`
	// Type - Nature of the dependency
	Type DependencyType `db:"type" json:"type"`
	// CreatedAt - Row creation timestamp
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// TaskDependencyClient provides type-safe operations for the task_dependencies table.
type TaskDependencyClient interface {
	// --- Read Operations ---

	// Get returns a single taskDependency by primary key.
	Get(ctx context.Context, pk TaskDependencyPK, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*TaskDependency, error)

	// GetMany returns task_dependencies matching the given filter, field selection, and sort criteria.
	GetMany(ctx context.Context, input *GetTaskDependenciesInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error)

	// Exists returns true if a taskDependency with the given primary key exists.
	Exists(ctx context.Context, pk TaskDependencyPK, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (bool, error)

	// ExistsWhere returns true if any taskDependency matches the given filter.
	ExistsWhere(ctx context.Context, filter *TaskDependencyFilter, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (bool, error)

	// Count returns the number of task_dependencies matching the given filter.
	Count(ctx context.Context, filter *TaskDependencyFilter, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (int64, error)

	// --- Write Operations ---

	// Create inserts a new taskDependency and returns the created entity.
	Create(ctx context.Context, input *CreateTaskDependencyInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*TaskDependency, error)

	// CreateMany inserts multiple task_dependencies in batches and returns all created entities.
	// Sub-batches are not automatically rolled back on failure — wrap in a transaction for atomicity.
	CreateMany(ctx context.Context, inputs []*CreateTaskDependencyInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error)

	// Update partially updates a taskDependency by primary key and returns the updated entity.
	// Only fields where IsSet() is true are included in the SET clause.
	// Returns ErrNotFound if the primary key does not exist.
	Update(ctx context.Context, pk TaskDependencyPK, input *UpdateTaskDependencyInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*TaskDependency, error)

	// UpdateMany updates multiple task_dependencies and returns the updated entities.
	UpdateMany(ctx context.Context, items []UpdateTaskDependencyItem, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error)

	// UpdateWhere updates all task_dependencies matching the filter and returns the updated entities.
	// Idempotent — returns empty slice when no rows match.
	UpdateWhere(ctx context.Context, filter *TaskDependencyFilter, input *UpdateTaskDependencyInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error)

	// Upsert inserts a taskDependency or updates it on conflict and returns the resulting entity.
	Upsert(ctx context.Context, input *CreateTaskDependencyInput, target TaskDependencyConflictTarget, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*TaskDependency, error)

	// UpsertMany inserts or updates multiple task_dependencies in batches and returns all resulting entities.
	// Inputs resolving to the same conflict target are deduped, last occurrence wins.
	UpsertMany(ctx context.Context, inputs []*CreateTaskDependencyInput, target TaskDependencyConflictTarget, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error)

	// --- Hard Delete Operations ---

	// HardDelete permanently removes a taskDependency from the database.
	// Idempotent — returns nil if the primary key does not exist.
	HardDelete(ctx context.Context, pk TaskDependencyPK, opts ...func(*CallOptions[TaskDependencyFieldOptions])) error

	// HardDeleteMany permanently removes multiple task_dependencies from the database.
	HardDeleteMany(ctx context.Context, pks []TaskDependencyPK, opts ...func(*CallOptions[TaskDependencyFieldOptions])) error

	// HardDeleteWhere permanently removes all task_dependencies matching the filter.
	// Idempotent — returns nil when no rows match.
	HardDeleteWhere(ctx context.Context, filter *TaskDependencyFilter, opts ...func(*CallOptions[TaskDependencyFieldOptions])) error

	// --- Pagination Operations ---

	// Paginate returns a page of task_dependencies with total count for offset-based pagination.
	Paginate(ctx context.Context, input PaginateInput[TaskDependencyFilter], opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*PaginateResult[TaskDependency], error)

	// Connection returns a Relay-style cursor-paginated connection of task_dependencies.
	// Sort order is determined by cursor_keys — custom sorts are not supported.
	// Use Paginate for custom sort orders.
	Connection(ctx context.Context, input ConnectionInput[TaskDependencyFilter], opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*Connection[TaskDependency], error)

	// Stream returns an iterator over task_dependencies matching the filter and sort criteria.
	// Rows are yielded as the driver returns them; cache is bypassed.
	// Stream cannot load relationships.
	//
	// Stream refuses an active transaction unless CallOptions.AllowInTransaction
	// is set, and the opt-in commits the caller to issuing nothing else on that
	// txCtx: the one rule that remains the caller's — drain or close a result set
	// before issuing the next statement on that txCtx — applied to a loop whose
	// body is caller code.
	Stream(ctx context.Context, input *StreamTaskDependenciesInput, opts ...func(*CallOptions[StreamTaskDependencyFieldOptions])) iter.Seq2[*TaskDependency, error]
}

// taskDependencyClient implements the TaskDependencyClient interface.
type taskDependencyClient struct {
	querier       database.Querier
	dialect       sql.Dialect
	table         sql.Table
	batchSize     int
	queryLimit    int
	pageSize      int
	cursorKeys    []string
	strictUpdates bool
	mutationHooks []hook.MutationHook
	queryHooks    []hook.QueryHook
	panicHandler  hook.PanicHandler
}

// newTaskDependencyClient creates a new taskDependencyClient.
func newTaskDependencyClient(querier database.Querier, mutationHooks []hook.MutationHook, queryHooks []hook.QueryHook, panicHandler hook.PanicHandler) *taskDependencyClient {
	return &taskDependencyClient{
		querier:       querier,
		dialect:       sql.NewPostgresDialect(),
		table:         sql.Table{Schema: "public", Name: "task_dependencies"},
		batchSize:     200,
		queryLimit:    1000,
		pageSize:      100,
		cursorKeys:    []string{"task_id", "depends_on_task_id"},
		strictUpdates: true,
		mutationHooks: mutationHooks,
		queryHooks:    queryHooks,
		panicHandler:  panicHandler,
	}
}

// executeMutation runs fn through the mutation hook chain.
// When skipHooks is true, only panic recovery wraps the call.
func (c *taskDependencyClient) executeMutation(ctx context.Context, skipHooks bool, mc *hook.MutationContext, fn hook.MutationHandler) (any, error) {
	var hooks []hook.MutationHook
	if !skipHooks {
		hooks = c.mutationHooks
	}
	return hook.BuildMutationChain(c.panicHandler, hooks, fn)(ctx, mc)
}

// executeQuery runs fn through the query hook chain.
// When skipHooks is true, only panic recovery wraps the call.
func (c *taskDependencyClient) executeQuery(ctx context.Context, skipHooks bool, qc *hook.QueryContext, fn hook.QueryHandler) (any, error) {
	var hooks []hook.QueryHook
	if !skipHooks {
		hooks = c.queryHooks
	}
	return hook.BuildQueryChain(c.panicHandler, hooks, fn)(ctx, qc)
}

// taskDependencyAllColumns is the column list for full-entity reads, sorted for determinism.
var taskDependencyAllColumns = []string{"created_at", "depends_on_task_id", "task_id", "type"}

// scanTaskDependencies scans rows into TaskDependency entities using a column-name switch.
// Handles both scan target shapes (direct, wrapped) without reflection.
func scanTaskDependencies(rows database.Rows, columns []string) ([]*TaskDependency, error) {
	var result []*TaskDependency
	for rows.Next() {
		t := &TaskDependency{}

		targets := make([]any, len(columns))
		for idx, col := range columns {
			switch col {
			case "task_id":
				targets[idx] = &t.TaskID
			case "depends_on_task_id":
				targets[idx] = &t.DependsOnTaskID
			case "type":
				targets[idx] = &t.Type
			case "created_at":
				targets[idx] = &t.CreatedAt
			}
		}

		if err := rows.Scan(targets...); err != nil {
			return nil, fmt.Errorf("scan task_dependency: %w", err)
		}

		result = append(result, t)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate task_dependency rows: %w", err)
	}
	return result, nil
}

// Get returns a single task_dependency by primary key with optional field selection.
// If fieldOptions is provided, only the selected columns are returned and
// relationships with non-nil FieldOptions are loaded.
func (c *taskDependencyClient) Get(ctx context.Context, pk TaskDependencyPK, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*TaskDependency, error) {
	options := resolveCallOptions(opts)

	if options.LockMode != sql.LockNone {
		if !database.InTransaction(ctx) {
			return nil, fmt.Errorf("get task_dependency: LockMode requires an active transaction")
		}
		options.SkipCache = true
	}
	qctx := &hook.QueryContext{
		Op: hook.OpGet, Table: TableTaskDependencies, Schema: "public",
		PK: pk, CallOptions: options,
	}
	result, err := c.executeQuery(ctx, options.SkipHooks, qctx, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		// Hooks may mutate q.CallOptions (e.g. the cache hook's hydration
		// path overrides FieldOptions for a full-entity refill). Prefer
		// those overrides when present; otherwise fall back to the
		// caller-supplied options captured at Get() time.
		effectiveOpts := options
		if qOpts, ok := q.CallOptions.(CallOptions[TaskDependencyFieldOptions]); ok {
			effectiveOpts = qOpts
		}
		// Internal GetMany call with SkipHooks to prevent nested hook invocation
		internalOpts := func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = effectiveOpts
			o.SkipHooks = true
		}
		taskDependencies, err := c.GetMany(ctx, &GetTaskDependenciesInput{
			Filter: &TaskDependencyFilter{
				TaskID:          &comparator.ID{Eq: new(pk.TaskID.String())},
				DependsOnTaskID: &comparator.ID{Eq: new(pk.DependsOnTaskID.String())},
			},
			Limit: new(1),
		}, internalOpts)
		if err != nil {
			return nil, err
		}
		if len(taskDependencies) == 0 {
			return nil, ErrNotFound
		}
		return taskDependencies[0], nil
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.(*TaskDependency), nil
}

// GetMany returns task_dependencies matching the given filter, field selection, and sort criteria.
func (c *taskDependencyClient) GetMany(ctx context.Context, input *GetTaskDependenciesInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error) {
	// A nil input is the zero-value input — no filter, no sorts, no
	// limit. Normalized before the hook context is built, so a hook never sees
	// a nil Input either.
	if input == nil {
		input = &GetTaskDependenciesInput{}
	}
	options := resolveCallOptions(opts)

	if options.LockMode != sql.LockNone {
		if !database.InTransaction(ctx) {
			return nil, fmt.Errorf("get task_dependencies: LockMode requires an active transaction")
		}
		options.SkipCache = true
	}
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpGetMany, Table: TableTaskDependencies, Schema: "public",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		// FieldOptions from CallOptions — nil means all columns
		fieldOptions := options.FieldOptions

		// Nothing selected — return early
		if fieldOptions != nil && !fieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		// Determine columns from FieldOptions. A narrowed projection still
		// carries the columns this call structurally requires — the cursor keys
		// an internal caller declares. An all-false FieldOptions is
		// untouched: it short-circuits above.
		columns := taskDependencyAllColumns
		if fieldOptions != nil {
			if selected := fieldOptions.Columns(); len(selected) > 0 {
				columns = unionColumns(selected, input.requiredColumns...)
			}
		}

		// Build conditions from filter
		var conds []sql.Condition
		if input.Filter != nil {
			conds = input.Filter.ToConditions(c.dialect)
		}

		// Append internal conditions (e.g., keyset conditions from Connection)
		conds = append(conds, input.conditions...)

		// Resolve limit/offset to pointers for the builder.
		// nil → no clause, *0 (via new(0)) → no clause, *N → LIMIT/OFFSET N.
		var limitPtr *int
		if input.Limit != nil {
			if v := *input.Limit; v > 0 {
				limitPtr = new(v)
			}
		} else if c.queryLimit > 0 {
			limitPtr = new(c.queryLimit)
		}
		var offsetPtr *int
		if input.Offset != nil {
			if v := *input.Offset; v > 0 {
				offsetPtr = new(v)
			}
		}

		var taskDependencies []*TaskDependency
		query, args := sql.BuildSelect(c.dialect, c.table, sql.SelectOptions{
			Columns:    columns,
			Conditions: conds,
			OrderBy:    input.Sorts,
			Limit:      limitPtr,
			Offset:     offsetPtr,
			LockMode:   options.LockMode,
		})

		rows, err := conn.Query(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("get task_dependencies: %w", err)
		}
		defer rows.Close()

		taskDependencies, err = scanTaskDependencies(rows, columns)
		if err != nil {
			return nil, err
		}

		return taskDependencies, nil
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*TaskDependency), nil
}

// Create inserts a new task_dependency and returns the created entity.
func (c *taskDependencyClient) Create(ctx context.Context, input *CreateTaskDependencyInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*TaskDependency, error) {
	// A write cannot normalize nil to the zero value the way a read
	// does — a zero CreateTaskDependencyInput legally writes a row (each required
	// field's zero value, or with no required field, every column's default), so
	// that would turn a caller's mistake into a silently written one. Guarded
	// before the executor, so nil fires no hook and publishes no event.
	if input == nil {
		return nil, ErrNilInput
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpCreate, Table: TableTaskDependencies, Schema: "public",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		columns := []string{"task_id", "depends_on_task_id"}
		args := []any{input.TaskID, input.DependsOnTaskID}

		if v, ok := input.Type.Get(); ok {
			columns = append(columns, "type")
			args = append(args, v)
		}

		if v, ok := input.CreatedAt.Get(); ok {
			columns = append(columns, "created_at")
			args = append(args, v)
		}

		query, queryArgs := sql.BuildInsert(c.dialect, c.table, sql.InsertOptions{
			Columns: columns,
			Values:  args,
		})
		_, err := conn.Exec(ctx, query, queryArgs...)
		if err != nil {
			return nil, fmt.Errorf("create task_dependency: %w", err)
		}

		m.AffectedPKs = []any{TaskDependencyPK{TaskID: input.TaskID, DependsOnTaskID: input.DependsOnTaskID}}

		// Empty FieldOptions — caller doesn't need the result
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.Get(ctx, TaskDependencyPK{TaskID: input.TaskID, DependsOnTaskID: input.DependsOnTaskID}, func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.(*TaskDependency), nil
}

// CreateMany inserts multiple task_dependencies in batches and returns all created entities.
// Sub-batches are not automatically rolled back on failure — wrap in a transaction for atomicity.
func (c *taskDependencyClient) CreateMany(ctx context.Context, inputs []*CreateTaskDependencyInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error) {
	// A nil *slice* is simply no rows, but a nil *element* is the
	// same caller error a nil Create argument is — and skipping it silently
	// would drop a row the caller asked for. Rejected before the executor.
	for _, in := range inputs {
		if in == nil {
			return nil, ErrNilInput
		}
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpCreateMany, Table: TableTaskDependencies, Schema: "public",
		Input: inputs, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		// An empty batch writes nothing and must read nothing. The trailing
		// re-fetch below filters on the keys this call touched, and every
		// generated key filter treats an empty set as *no condition* — so
		// without this guard the re-fetch degrades to an unfiltered SELECT and
		// returns the whole table as if this call had produced it.
		if len(inputs) == 0 {
			return []*TaskDependency{}, nil
		}
		var allPKs []TaskDependencyPK
		for start := 0; start < len(inputs); start += c.batchSize {
			end := min(start+c.batchSize, len(inputs))
			batch := inputs[start:end]

			columns := []string{"task_id", "depends_on_task_id", "type", "created_at"}
			var valueRows [][]any
			for _, input := range batch {
				var typeVal any = sql.Default
				if v, ok := input.Type.Get(); ok {
					typeVal = v
				}
				var createdAt any = sql.Default
				if v, ok := input.CreatedAt.Get(); ok {
					createdAt = v
				}

				valueRows = append(valueRows, []any{
					input.TaskID,
					input.DependsOnTaskID,
					typeVal,
					createdAt,
				})
			}

			query, queryArgs := sql.BuildMultiInsert(c.dialect, c.table, sql.MultiInsertOptions{
				Columns:   columns,
				ValueRows: valueRows,
			})
			_, err := conn.Exec(ctx, query, queryArgs...)
			if err != nil {
				return nil, fmt.Errorf("create task_dependencies batch: %w", err)
			}
			for _, input := range batch {
				allPKs = append(allPKs, TaskDependencyPK{TaskID: input.TaskID, DependsOnTaskID: input.DependsOnTaskID})
			}
		}

		m.AffectedPKs = toAnySlice(allPKs)

		// Empty FieldOptions — skip fetch
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		// Re-fetch via composite PK filter
		return c.GetMany(ctx, &GetTaskDependenciesInput{
			Filter: &TaskDependencyFilter{PKs: allPKs},
			Limit:  new(0),
		}, func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*TaskDependency), nil
}

// Update partially updates a task_dependency by primary key and returns the updated entity.
// Only fields where IsSet() is true are included in the SET clause. If no fields are
// set, no UPDATE is executed and the current entity is returned unchanged.
// Returns ErrNotFound if the primary key does not exist (strict_updates is enabled).
func (c *taskDependencyClient) Update(ctx context.Context, pk TaskDependencyPK, input *UpdateTaskDependencyInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*TaskDependency, error) {
	// Nil is a caller error, distinct from an empty-but-non-nil
	// input — that one is the documented no-op returning the entity unchanged.
	// Guarded before the executor, so nil fires no hook and publishes no event.
	if input == nil {
		return nil, ErrNilInput
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpdate, Table: TableTaskDependencies, Schema: "public",
		PK: pk, Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		// Build SET clause from omittable fields — explicit per-field checks, no reflection
		setClauses := make(map[string]any)
		if v, ok := input.Type.Get(); ok {
			setClauses["type"] = v
		}
		if v, ok := input.CreatedAt.Get(); ok {
			setClauses["created_at"] = v
		}

		// Empty update — no fields set, return current entity unchanged
		if len(setClauses) == 0 {
			// Empty FieldOptions — caller doesn't need the result
			if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
				return nil, nil
			}

			return c.Get(ctx, pk, func(o *CallOptions[TaskDependencyFieldOptions]) {
				*o = options
				o.SkipHooks = true
				o.LockMode = sql.LockNone
			})
		}

		query, args := sql.BuildUpdate(c.dialect, c.table, sql.UpdateOptions{
			SetClauses: setClauses,
			Conditions: sql.BuildCompositePKConditions(c.dialect,
				[]string{"task_id", "depends_on_task_id"},
				[]any{pk.TaskID, pk.DependsOnTaskID}),
		})

		execResult, err := conn.Exec(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("update task_dependency: %w", err)
		}
		count, err := execResult.RowsAffected()
		if err != nil {
			return nil, fmt.Errorf("update task_dependency rows affected: %w", err)
		}
		if count == 0 {
			return nil, ErrNotFound
		}
		m.AffectedPKs = []any{pk}

		// Empty FieldOptions — caller doesn't need the result
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.Get(ctx, pk, func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.(*TaskDependency), nil
}

// UpdateTaskDependencyItem pairs a primary key with an update input for batch updates.
type UpdateTaskDependencyItem struct {
	PK    TaskDependencyPK           `json:"pk"`
	Input *UpdateTaskDependencyInput `json:"input"`
}

// UpdateMany partially updates multiple task_dependencies and returns the updated entities.
// Each item is a (PK, UpdateInput) pair. Splits into batches of batchSize.
// On pgx, uses SendBatch for pipelined execution within each batch.
func (c *taskDependencyClient) UpdateMany(ctx context.Context, items []UpdateTaskDependencyItem, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error) {
	// UpdateTaskDependencyItem.Input is a pointer, so a zero-valued item
	// carries a nil one — a shape that compiles naturally. Rejected before the
	// executor, like every other nil write input.
	for _, item := range items {
		if item.Input == nil {
			return nil, ErrNilInput
		}
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpdateMany, Table: TableTaskDependencies, Schema: "public",
		Input: items, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		// An empty batch writes nothing and must read nothing. The trailing
		// re-fetch below filters on the keys this call touched, and every
		// generated key filter treats an empty set as *no condition* — so
		// without this guard the re-fetch degrades to an unfiltered SELECT and
		// returns the whole table as if this call had produced it.
		if len(items) == 0 {
			return []*TaskDependency{}, nil
		}
		var allPKs []TaskDependencyPK
		for start := 0; start < len(items); start += c.batchSize {
			end := min(start+c.batchSize, len(items))
			batch := items[start:end]

			// Build all UPDATE statements for this batch
			pgxBatch := &pgx.Batch{}
			var batchQueries []string
			var batchArgs [][]any
			for _, item := range batch {
				setClauses := make(map[string]any)
				if v, ok := item.Input.Type.Get(); ok {
					setClauses["type"] = v
				}
				if v, ok := item.Input.CreatedAt.Get(); ok {
					setClauses["created_at"] = v
				}

				// Skip no-op updates
				if len(setClauses) == 0 {
					allPKs = append(allPKs, item.PK)
					continue
				}

				query, args := sql.BuildUpdate(c.dialect, c.table, sql.UpdateOptions{
					SetClauses: setClauses,
					Conditions: sql.BuildCompositePKConditions(c.dialect,
						[]string{"task_id", "depends_on_task_id"},
						[]any{item.PK.TaskID, item.PK.DependsOnTaskID}),
				})
				pgxBatch.Queue(query, args...)
				batchQueries = append(batchQueries, query)
				batchArgs = append(batchArgs, args)
				allPKs = append(allPKs, item.PK)
			}

			// Send all UPDATEs — pipelined if supported, sequential otherwise
			if pgxBatch.Len() > 0 {
				if batcher, ok := conn.(interface {
					SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults
				}); ok {
					br := batcher.SendBatch(ctx, pgxBatch)
					for range pgxBatch.Len() {
						if _, err := br.Exec(); err != nil {
							br.Close()
							return nil, fmt.Errorf("update task_dependencies batch: %w", err)
						}
					}
					if err := br.Close(); err != nil {
						return nil, fmt.Errorf("close update batch: %w", err)
					}
				} else {
					for i, q := range batchQueries {
						if _, err := conn.Exec(ctx, q, batchArgs[i]...); err != nil {
							return nil, fmt.Errorf("update task_dependencies batch: %w", err)
						}
					}
				}
			}
		}

		m.AffectedPKs = toAnySlice(allPKs)

		// Empty FieldOptions — skip fetch
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.GetMany(ctx, &GetTaskDependenciesInput{
			Filter: &TaskDependencyFilter{PKs: allPKs},
			Limit:  new(0),
		}, func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*TaskDependency), nil
}

// UpdateWhere updates all task_dependencies matching the filter and returns the updated entities.
// Idempotent — returns empty slice when no rows match.
// Returns ErrNilInput when input is nil, checked before the filter.
// Returns ErrEmptyFilter when the filter is nil or produces no conditions.
func (c *taskDependencyClient) UpdateWhere(ctx context.Context, filter *TaskDependencyFilter, input *UpdateTaskDependencyInput, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error) {
	// Argument validity is checked before the filter's bulk-op
	// safety guard, and before the executor, so a nil input fires no hook and
	// publishes no event. ErrEmptyFilter still covers a non-nil input with an
	// empty filter.
	if input == nil {
		return nil, ErrNilInput
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpdateWhere, Table: TableTaskDependencies, Schema: "public",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		conds := filter.ToConditions(c.dialect)
		if len(conds) == 0 {
			return nil, ErrEmptyFilter
		}

		// Build SET clause (same per-field checks as Update)
		setClauses := make(map[string]any)
		if v, ok := input.Type.Get(); ok {
			setClauses["type"] = v
		}
		if v, ok := input.CreatedAt.Get(); ok {
			setClauses["created_at"] = v
		}

		// No fields set — return matching entities unchanged
		if len(setClauses) == 0 {
			if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
				return nil, nil
			}
			return c.GetMany(ctx, &GetTaskDependenciesInput{
				Filter: filter,
				Limit:  new(0),
			}, func(o *CallOptions[TaskDependencyFieldOptions]) {
				*o = options
				o.SkipHooks = true
				o.LockMode = sql.LockNone
			})
		}

		// UPDATE with RETURNING — get affected composite PKs in one round-trip
		query, args := sql.BuildUpdate(c.dialect, c.table, sql.UpdateOptions{
			SetClauses:       setClauses,
			Conditions:       conds,
			ReturningColumns: []string{"task_id", "depends_on_task_id"},
		})

		rows, err := conn.Query(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("update task_dependencies where: %w", err)
		}
		defer rows.Close()

		var pks []TaskDependencyPK
		for rows.Next() {
			var pk TaskDependencyPK
			if err := rows.Scan(&pk.TaskID, &pk.DependsOnTaskID); err != nil {
				return nil, fmt.Errorf("scan updated task_dependency pk: %w", err)
			}
			pks = append(pks, pk)
		}
		if err := rows.Err(); err != nil {
			return nil, err
		}
		if len(pks) == 0 {
			return nil, nil
		}
		m.AffectedPKs = toAnySlice(pks)

		// Empty FieldOptions — skip fetch
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.GetMany(ctx, &GetTaskDependenciesInput{
			Filter: &TaskDependencyFilter{PKs: pks},
			Limit:  new(0),
		}, func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*TaskDependency), nil
}

// HardDelete permanently removes a task_dependency from the database.
// Idempotent — returns nil if the primary key does not exist.
func (c *taskDependencyClient) HardDelete(ctx context.Context, pk TaskDependencyPK, opts ...func(*CallOptions[TaskDependencyFieldOptions])) error {
	options := resolveCallOptions(opts)
	_, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpHardDelete, Table: TableTaskDependencies, Schema: "public",
		PK: pk, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		query, args := sql.BuildHardDelete(c.dialect, c.table, sql.HardDeleteOptions{
			Conditions: sql.BuildCompositePKConditions(c.dialect,
				[]string{"task_id", "depends_on_task_id"},
				[]any{pk.TaskID, pk.DependsOnTaskID}),
		})

		_, err := conn.Exec(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("hard delete task_dependency: %w", err)
		}
		m.AffectedPKs = []any{pk}
		return nil, nil
	})
	return err
}

// HardDeleteMany permanently removes multiple task_dependencies from the database.
func (c *taskDependencyClient) HardDeleteMany(ctx context.Context, pks []TaskDependencyPK, opts ...func(*CallOptions[TaskDependencyFieldOptions])) error {
	options := resolveCallOptions(opts)
	_, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpHardDeleteMany, Table: TableTaskDependencies, Schema: "public",
		Input: pks, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		pkValues := make([][]any, len(pks))
		for i, pk := range pks {
			pkValues[i] = []any{pk.TaskID, pk.DependsOnTaskID}
		}

		query, args := sql.BuildHardDelete(c.dialect, c.table, sql.HardDeleteOptions{
			Conditions: []sql.Condition{
				sql.BuildCompositePKBatchCondition(c.dialect, []string{"task_id", "depends_on_task_id"}, pkValues),
			},
		})

		_, err := conn.Exec(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("hard delete task_dependencies: %w", err)
		}
		m.AffectedPKs = toAnySlice(pks)
		return nil, nil
	})
	return err
}

// HardDeleteWhere permanently removes all task_dependencies matching the filter.
// Idempotent — returns nil when no rows match.
// Returns ErrEmptyFilter when the filter is nil or produces no conditions.
func (c *taskDependencyClient) HardDeleteWhere(ctx context.Context, filter *TaskDependencyFilter, opts ...func(*CallOptions[TaskDependencyFieldOptions])) error {
	options := resolveCallOptions(opts)
	_, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpHardDeleteWhere, Table: TableTaskDependencies, Schema: "public",
		Input: filter, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		conds := filter.ToConditions(c.dialect)
		if len(conds) == 0 {
			return nil, ErrEmptyFilter
		}

		// DELETE with RETURNING — get affected composite PKs in one round-trip
		query, args := sql.BuildHardDelete(c.dialect, c.table, sql.HardDeleteOptions{
			Conditions:       conds,
			ReturningColumns: []string{"task_id", "depends_on_task_id"},
		})

		rows, err := conn.Query(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("hard delete task_dependencies where: %w", err)
		}
		defer rows.Close()

		var pks []TaskDependencyPK
		for rows.Next() {
			var pk TaskDependencyPK
			if err := rows.Scan(&pk.TaskID, &pk.DependsOnTaskID); err != nil {
				return nil, fmt.Errorf("scan deleted task_dependency pk: %w", err)
			}
			pks = append(pks, pk)
		}
		if err := rows.Err(); err != nil {
			return nil, err
		}
		m.AffectedPKs = toAnySlice(pks)
		return nil, nil
	})
	return err
}

// TaskDependencyConflictTarget identifies a unique constraint for upsert conflict detection.
type TaskDependencyConflictTarget int

const (
	TaskDependencyConflictPK TaskDependencyConflictTarget = iota // PRIMARY KEY (task_id, depends_on_task_id)
)

// taskDependencyConflictColumns maps each conflict target to its column set.
var taskDependencyConflictColumns = map[TaskDependencyConflictTarget][]string{
	TaskDependencyConflictPK: {"task_id", "depends_on_task_id"},
}

// Upsert inserts a task_dependency or updates it if a row matching the conflict target already
// exists. Returns the resulting entity with optional field selection and relationship loading.
// The conflict target determines which unique constraint triggers an update
// instead of an insert. Non-PK, non-conflict columns are included in the SET clause.
func (c *taskDependencyClient) Upsert(ctx context.Context, input *CreateTaskDependencyInput, target TaskDependencyConflictTarget, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*TaskDependency, error) {
	// A write cannot normalize nil to the zero value the way a read
	// does — a zero CreateTaskDependencyInput legally writes a row (each required
	// field's zero value, or with no required field, every column's default).
	// Guarded before the executor, so nil fires no hook and publishes no event.
	// An input that supplies no column gets no conflict clause on any dialect:
	// it is a plain insert, so a conflict on a UNIQUE column with a
	// DEFAULT is a unique violation, including on MySQL, where ON DUPLICATE KEY
	// UPDATE would have returned the existing row.
	if input == nil {
		return nil, ErrNilInput
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpsert, Table: TableTaskDependencies, Schema: "public",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		columns := []string{"task_id", "depends_on_task_id"}
		args := []any{input.TaskID, input.DependsOnTaskID}

		if v, ok := input.Type.Get(); ok {
			columns = append(columns, "type")
			args = append(args, v)
		}

		if v, ok := input.CreatedAt.Get(); ok {
			columns = append(columns, "created_at")
			args = append(args, v)
		}

		// Resolve conflict target and update columns. Tenant column is excluded
		// from the UPDATE-set half of the conflict clause — a
		// row's tenant is not a mutable attribute under normal operation.
		conflictColumns := taskDependencyConflictColumns[target]
		updateColumns := excludeColumns(columns, append(conflictColumns, "task_id", "depends_on_task_id"))

		query, queryArgs := sql.BuildInsert(c.dialect, c.table, sql.InsertOptions{
			Columns:             columns,
			Values:              args,
			UpsertConflictKeys:  conflictColumns,
			UpsertUpdateColumns: updateColumns,
		})
		_, err := conn.Exec(ctx, query, queryArgs...)
		if err != nil {
			return nil, fmt.Errorf("upsert task_dependency: %w", err)
		}

		m.AffectedPKs = []any{TaskDependencyPK{TaskID: input.TaskID, DependsOnTaskID: input.DependsOnTaskID}}

		// Empty FieldOptions — caller doesn't need the result
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.Get(ctx, TaskDependencyPK{TaskID: input.TaskID, DependsOnTaskID: input.DependsOnTaskID}, func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.(*TaskDependency), nil
}

// UpsertMany inserts or updates multiple task_dependencies in batches and returns all
// resulting entities. One conflict target applies to the whole batch, drawn from
// the same enum Upsert takes. Sub-batches are not automatically rolled back on
// failure — wrap in a transaction for atomicity.
//
// Inputs resolving to the same conflict target are deduped before the statement
// is built, last occurrence wins. PostgreSQL rejects an
// ON CONFLICT ... DO UPDATE that would affect one row twice; MySQL and SQLite
// accept it and keep the last row. The dedupe is what makes one spelling behave
// identically on all three. A row carrying no definite, non-NULL value for every
// conflict column is exempt: a NULL never matches under a unique index on any of
// the three dialects, so two such rows are two rows, not a duplicate.
//
// The returned slice carries one entity per deduped input on every dialect,
// including the DO NOTHING branch a conflict target covering every inserted
// column produces. The entities come from a re-fetch by primary key, never from
// RETURNING — RETURNING yields only the rows actually inserted, so a batch that
// conflicted would come back short. Row order is GetMany's, as with
// CreateMany.
func (c *taskDependencyClient) UpsertMany(ctx context.Context, inputs []*CreateTaskDependencyInput, target TaskDependencyConflictTarget, opts ...func(*CallOptions[TaskDependencyFieldOptions])) ([]*TaskDependency, error) {
	// A nil *slice* is simply no rows, but a nil *element* is the
	// same caller error a nil Upsert argument is — and skipping it silently
	// would drop a row the caller asked for. Rejected before the executor.
	for _, in := range inputs {
		if in == nil {
			return nil, ErrNilInput
		}
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpsertMany, Table: TableTaskDependencies, Schema: "public",
		Input: inputs, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		// No rows means no statement and nothing affected. Guarded here because
		// the terminal GetMany filters on the written keys, and a key filter
		// built from an empty set contributes no condition — an unguarded empty
		// call would read the whole table back.
		if len(inputs) == 0 {
			return []*TaskDependency{}, nil
		}
		conn := database.Conn(ctx, c.querier)

		// Resolve conflict target and update columns. Tenant column is excluded
		// from the UPDATE-set half of the conflict clause — a
		// row's tenant is not a mutable attribute under normal operation.
		//
		// UpsertResolvePKColumn is deliberately not set: it exists so a
		// single-row MySQL upsert can republish the conflicting row's id into
		// the OK packet, and after a batch that packet names at most one row.
		// Nothing here reads LastInsertId, so requesting it would
		// only add a misleading assignment to the SET list.
		columns := []string{"task_id", "depends_on_task_id", "type", "created_at"}
		conflictColumns := taskDependencyConflictColumns[target]
		updateColumns := excludeColumns(columns, append(conflictColumns, "task_id", "depends_on_task_id"))
		conflictPositions, haveConflictKey := upsertConflictPositions(columns, conflictColumns)

		// One value row per input, built before any statement runs: the dedupe
		// spans the whole call, not a sub-batch (ceil(M/batch_size)
		// statements for M inputs, *after* the dedupe).
		valueRows := make([][]any, 0, len(inputs))
		rowInputs := make([]*CreateTaskDependencyInput, 0, len(inputs))
		rowPKs := make([]TaskDependencyPK, 0, len(inputs))
		for _, input := range inputs {
			var typeVal any = sql.Default
			if v, ok := input.Type.Get(); ok {
				typeVal = v
			}
			var createdAt any = sql.Default
			if v, ok := input.CreatedAt.Get(); ok {
				createdAt = v
			}

			valueRows = append(valueRows, []any{
				input.TaskID,
				input.DependsOnTaskID,
				typeVal,
				createdAt,
			})
			rowInputs = append(rowInputs, input)
			rowPKs = append(rowPKs, TaskDependencyPK{TaskID: input.TaskID, DependsOnTaskID: input.DependsOnTaskID})
		}

		// Dedupe by conflict target, last occurrence wins, first-appearance
		// order preserved.
		if haveConflictKey {
			seen := make(map[string]int, len(valueRows))
			dedupedRows := make([][]any, 0, len(valueRows))
			dedupedInputs := make([]*CreateTaskDependencyInput, 0, len(rowInputs))
			dedupedPKs := make([]TaskDependencyPK, 0, len(rowPKs))
			for i, row := range valueRows {
				key, keyed := upsertDedupeKey(row, conflictPositions)
				if keyed {
					if j, ok := seen[key]; ok {
						dedupedRows[j] = row
						dedupedInputs[j] = rowInputs[i]
						dedupedPKs[j] = rowPKs[i]
						continue
					}
					seen[key] = len(dedupedRows)
				}
				dedupedRows = append(dedupedRows, row)
				dedupedInputs = append(dedupedInputs, rowInputs[i])
				dedupedPKs = append(dedupedPKs, rowPKs[i])
			}
			valueRows = dedupedRows
			rowInputs = dedupedInputs
			rowPKs = dedupedPKs
		}
		// The published input is the deduped slice, so it stays index-aligned
		// with m.AffectedPKs: an event fanned out per affected row carries the
		// input that actually wrote that row.
		m.Input = rowInputs

		for start := 0; start < len(valueRows); start += c.batchSize {
			end := min(start+c.batchSize, len(valueRows))
			batch := valueRows[start:end]

			query, queryArgs := sql.BuildMultiInsert(c.dialect, c.table, sql.MultiInsertOptions{
				Columns:             columns,
				ValueRows:           batch,
				UpsertConflictKeys:  conflictColumns,
				UpsertUpdateColumns: updateColumns,
			})
			if _, err := conn.Exec(ctx, query, queryArgs...); err != nil {
				return nil, fmt.Errorf("upsert task_dependencies batch: %w", err)
			}
		}

		m.AffectedPKs = toAnySlice(rowPKs)

		// Empty FieldOptions — skip fetch
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		// Re-fetch via composite PK filter
		return c.GetMany(ctx, &GetTaskDependenciesInput{
			Filter: &TaskDependencyFilter{PKs: rowPKs},
			Limit:  new(0),
		}, func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*TaskDependency), nil
}

// Exists returns true if a task_dependency with the given primary key exists.
func (c *taskDependencyClient) Exists(ctx context.Context, pk TaskDependencyPK, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (bool, error) {
	options := resolveCallOptions(opts)
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpExists, Table: TableTaskDependencies, Schema: "public",
		PK: pk, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		conds := sql.BuildCompositePKConditions(c.dialect,
			[]string{"task_id", "depends_on_task_id"},
			[]any{pk.TaskID, pk.DependsOnTaskID})

		query, args := sql.BuildExists(c.dialect, c.table, conds)

		var exists bool
		if err := conn.QueryRow(ctx, query, args...).Scan(&exists); err != nil {
			return false, fmt.Errorf("exists task_dependency: %w", err)
		}
		return exists, nil
	})
	if err != nil {
		return false, err
	}
	return result.(bool), nil
}

// ExistsWhere returns true if any task_dependency matches the given filter.
func (c *taskDependencyClient) ExistsWhere(ctx context.Context, filter *TaskDependencyFilter, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (bool, error) {
	options := resolveCallOptions(opts)
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpExists, Table: TableTaskDependencies, Schema: "public",
		Input: filter, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		var conds []sql.Condition
		if filter != nil {
			conds = filter.ToConditions(c.dialect)
		}

		query, args := sql.BuildExists(c.dialect, c.table, conds)

		var exists bool
		if err := conn.QueryRow(ctx, query, args...).Scan(&exists); err != nil {
			return false, fmt.Errorf("exists task_dependency where: %w", err)
		}
		return exists, nil
	})
	if err != nil {
		return false, err
	}
	return result.(bool), nil
}

// Count returns the number of task_dependencies matching the given filter.
// A nil filter counts all task_dependencies.
func (c *taskDependencyClient) Count(ctx context.Context, filter *TaskDependencyFilter, opts ...func(*CallOptions[TaskDependencyFieldOptions])) (int64, error) {
	options := resolveCallOptions(opts)
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpCount, Table: TableTaskDependencies, Schema: "public",
		Input: filter, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		var conds []sql.Condition
		if filter != nil {
			conds = filter.ToConditions(c.dialect)
		}

		query, args := sql.BuildCount(c.dialect, c.table, conds)

		var count int64
		if err := conn.QueryRow(ctx, query, args...).Scan(&count); err != nil {
			return int64(0), fmt.Errorf("count task_dependencies: %w", err)
		}
		return count, nil
	})
	if err != nil {
		return 0, err
	}
	return result.(int64), nil
}

// Paginate returns a page of task_dependencies with total count for offset-based pagination.
// A nil filter paginates all task_dependencies.
func (c *taskDependencyClient) Paginate(ctx context.Context, input PaginateInput[TaskDependencyFilter], opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*PaginateResult[TaskDependency], error) {
	options := resolveCallOptions(opts)
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpPaginate, Table: TableTaskDependencies, Schema: "public",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		// Internal calls with SkipHooks to prevent nested hook invocation
		internalOpts := func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
		}

		// Total count (delegates to Count — both are always generated)
		totalCount, err := c.Count(ctx, input.Filter, internalOpts)
		if err != nil {
			return nil, fmt.Errorf("paginate task_dependencies count: %w", err)
		}

		// Page data via GetMany (handles FieldOptions and relationships)
		taskDependencies, err := c.GetMany(ctx, &GetTaskDependenciesInput{
			Filter: input.Filter,
			Sorts:  input.Sort,
			Limit:  &input.Limit,
			Offset: &input.Offset,
		}, internalOpts)
		if err != nil {
			return nil, fmt.Errorf("paginate task_dependencies: %w", err)
		}

		return &PaginateResult[TaskDependency]{
			Items:      taskDependencies,
			TotalCount: totalCount,
			Offset:     input.Offset,
			Limit:      input.Limit,
			HasMore:    int64(input.Offset+input.Limit) < totalCount,
		}, nil
	})
	if err != nil {
		return nil, err
	}
	return result.(*PaginateResult[TaskDependency]), nil
}

// Connection returns a Relay-style cursor-paginated connection of task_dependencies.
// Sort order is determined by cursor_keys — custom sorts are not supported.
// Use Paginate for custom sort orders.
func (c *taskDependencyClient) Connection(ctx context.Context, input ConnectionInput[TaskDependencyFilter], opts ...func(*CallOptions[TaskDependencyFieldOptions])) (*Connection[TaskDependency], error) {
	options := resolveCallOptions(opts)

	if options.LockMode != sql.LockNone {
		if !database.InTransaction(ctx) {
			return nil, fmt.Errorf("connection task_dependencies: LockMode requires an active transaction")
		}
		options.SkipCache = true
	}
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpConnection, Table: TableTaskDependencies, Schema: "public",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		// Internal calls with SkipHooks to prevent nested hook invocation
		internalOpts := func(o *CallOptions[TaskDependencyFieldOptions]) {
			*o = options
			o.SkipHooks = true
		}

		// Validate: first and last are mutually exclusive
		if input.First != nil && input.Last != nil {
			return nil, ErrInvalidCursor
		}

		// Total count (separate COUNT query — no cursor conditions)
		totalCount, err := c.Count(ctx, input.Filter, internalOpts)
		if err != nil {
			return nil, fmt.Errorf("connection task_dependencies count: %w", err)
		}

		// Decode cursors and build keyset conditions
		var keysetConds []sql.Condition
		if input.After != nil {
			cursor, err := decodeCursor(*input.After)
			if err != nil {
				return nil, ErrInvalidCursor
			}
			keysetConds = append(keysetConds, cursorKeyset(c.dialect, c.cursorKeys, cursor, ">"))
		}
		if input.Before != nil {
			cursor, err := decodeCursor(*input.Before)
			if err != nil {
				return nil, ErrInvalidCursor
			}
			keysetConds = append(keysetConds, cursorKeyset(c.dialect, c.cursorKeys, cursor, "<"))
		}

		// Direction and limit
		limit := c.pageSize
		ascending := true
		if input.First != nil {
			limit = *input.First
		} else if input.Last != nil {
			limit = *input.Last
			ascending = false
		}

		// Fetch limit+1 rows via GetMany (handles FieldOptions, O2O joins, relationships, soft delete)
		connLimit := limit + 1
		taskDependencies, err := c.GetMany(ctx, &GetTaskDependenciesInput{
			Filter:     input.Filter,
			Sorts:      cursorSorts(c.cursorKeys, ascending),
			Limit:      &connLimit,
			conditions: keysetConds,
			// Each edge's cursor is encoded from the row it wraps, so the cursor
			// keys have to survive a narrowed FieldOptions — otherwise the
			// encoder reads fields the SELECT never filled and every cursor
			// carries zero values.
			requiredColumns: c.cursorKeys,
		}, internalOpts)
		if err != nil {
			return nil, fmt.Errorf("connection task_dependencies: %w", err)
		}

		// Trim extra row and determine page boundaries
		hasMore := len(taskDependencies) > limit
		if hasMore {
			taskDependencies = taskDependencies[:limit]
		}

		// Backward pagination: reverse for ascending cursor order
		if !ascending {
			slices.Reverse(taskDependencies)
		}

		// Build edges with encoded cursors
		edges := make([]Edge[TaskDependency], len(taskDependencies))
		for i, row := range taskDependencies {
			cursor, err := encodeTaskDependencyCursor(c.cursorKeys, row)
			if err != nil {
				return nil, err
			}
			edges[i] = Edge[TaskDependency]{
				Node:   row,
				Cursor: cursor,
			}
		}

		pageInfo := PageInfo{
			HasNextPage:     (ascending && hasMore) || (!ascending && input.Before != nil),
			HasPreviousPage: (!ascending && hasMore) || (ascending && input.After != nil),
		}
		if len(edges) > 0 {
			pageInfo.StartCursor = &edges[0].Cursor
			pageInfo.EndCursor = &edges[len(edges)-1].Cursor
		}

		return &Connection[TaskDependency]{Edges: edges, PageInfo: pageInfo, TotalCount: totalCount}, nil
	})
	if err != nil {
		return nil, err
	}
	return result.(*Connection[TaskDependency]), nil
}

// encodeTaskDependencyCursor encodes cursor key values as a base64 JSON string.
func encodeTaskDependencyCursor(keys []string, t *TaskDependency) (string, error) {
	out := make(map[string]any, len(keys))
	for _, key := range keys {
		switch key {
		case "task_id":
			out["task_id"] = t.TaskID
		case "depends_on_task_id":
			out["depends_on_task_id"] = t.DependsOnTaskID
		case "type":
			out["type"] = t.Type
		case "created_at":
			out["created_at"] = t.CreatedAt
		}
	}
	data, err := json.Marshal(out)
	if err != nil {
		return "", fmt.Errorf("encode task_dependency cursor: %w", err)
	}
	return base64.StdEncoding.EncodeToString(data), nil
}

// StreamTaskDependenciesInput holds query parameters for streaming task_dependencies records.
// Stream is iterator-style and intentionally has no Limit/Offset.
// Field selection is controlled via CallOptions.FieldOptions, not this struct.
type StreamTaskDependenciesInput struct {
	Filter *TaskDependencyFilter `json:"filter"`
	Sorts  []sql.Sort            `json:"sorts"`
}

// StreamTaskDependencyFieldOptions controls scalar column selection for task_dependencies streams.
// Stream cannot load relationships — only scalar columns are selectable.
type StreamTaskDependencyFieldOptions struct {
	TaskID          bool `json:"task_id"`
	DependsOnTaskID bool `json:"depends_on_task_id"`
	Type            bool `json:"type"`
	CreatedAt       bool `json:"created_at"`
}

// Columns returns the SQL column names for all selected columns, sorted alphabetically
// to match the SQL builder's deterministic column ordering.
func (fo *StreamTaskDependencyFieldOptions) Columns() []string {
	var cols []string
	if fo.TaskID {
		cols = append(cols, "task_id")
	}
	if fo.DependsOnTaskID {
		cols = append(cols, "depends_on_task_id")
	}
	if fo.Type {
		cols = append(cols, "type")
	}
	if fo.CreatedAt {
		cols = append(cols, "created_at")
	}
	slices.Sort(cols)
	return cols
}

// HasSelectedColumns reports whether any column is selected.
func (fo *StreamTaskDependencyFieldOptions) HasSelectedColumns() bool {
	if fo.TaskID {
		return true
	}
	if fo.DependsOnTaskID {
		return true
	}
	if fo.Type {
		return true
	}
	if fo.CreatedAt {
		return true
	}
	return false
}

// scanTaskDependencyRow scans a single row into a TaskDependency entity.
// Used by Stream to yield rows one at a time without materializing the result set.
func scanTaskDependencyRow(rows database.Rows, columns []string) (*TaskDependency, error) {
	t := &TaskDependency{}

	targets := make([]any, len(columns))
	for idx, col := range columns {
		switch col {
		case "task_id":
			targets[idx] = &t.TaskID
		case "depends_on_task_id":
			targets[idx] = &t.DependsOnTaskID
		case "type":
			targets[idx] = &t.Type
		case "created_at":
			targets[idx] = &t.CreatedAt
		}
	}

	if err := rows.Scan(targets...); err != nil {
		return nil, fmt.Errorf("scan task_dependency: %w", err)
	}

	return t, nil
}

// Stream returns an iterator over task_dependencies matching the given filter and sort criteria.
// Rows are yielded as the driver returns them, without materializing the full
// result set. Cache is bypassed regardless of caller setting.
// Stream cannot load relationships — use Connection in a loop when relationships
// are required.
//
// Stream refuses an active transaction. It runs consumer code inside an open
// result set, which inside a transaction is the transaction's only connection,
// held for the whole iteration — so a statement issued from the loop body on the
// same txCtx waits on a reservation the loop itself holds. Set
// CallOptions.AllowInTransaction for a snapshot-consistent stream that issues
// nothing else on that txCtx. That obligation is the one rule that remains the
// caller's — drain or close a result set before issuing the next statement on
// that txCtx — applied to a loop whose body is caller code.
func (c *taskDependencyClient) Stream(ctx context.Context, input *StreamTaskDependenciesInput, opts ...func(*CallOptions[StreamTaskDependencyFieldOptions])) iter.Seq2[*TaskDependency, error] {
	return func(yield func(*TaskDependency, error) bool) {
		// A nil input is the zero-value input. Without it, an
		// unguarded nil dereference in the handler would be recovered by the
		// panic wrapper and reported as an error instead of streaming the table.
		if input == nil {
			input = &StreamTaskDependenciesInput{}
		}
		options := resolveCallOptions(opts)
		options.SkipCache = true

		// Stream's contract is that the connection stays open across
		// caller code; a transaction's is one connection, one statement at a
		// time. The two cannot both hold, so Stream refuses a transaction unless
		// the caller opts in. Refused before any SQL is issued and before the
		// hook chain is built, mirroring the LockMode precondition, and
		// surfaced through yield because Stream returns an iterator and has no
		// error return.
		if database.InTransaction(ctx) && !options.AllowInTransaction {
			yield(nil, fmt.Errorf("stream task_dependencies: unsupported inside a transaction — use Connection in a loop, "+
				"or set AllowInTransaction for a snapshot-consistent stream that issues nothing else on this txCtx"))
			return
		}

		// stopped is true while the consumer's loop body runs, and stays true
		// once the body breaks (yield returned false) or panics out of yield.
		// Calling yield again after either makes the Go runtime panic, so the
		// chain's error below is yielded only while stopped is false.
		var stopped bool
		emit := func(row *TaskDependency, err error) bool {
			stopped = true
			if !yield(row, err) {
				return false
			}
			stopped = false
			return true
		}

		// A recovered panic and a hook's abort error are the
		// chain's return value. Stream has no error return, so it yields that
		// error once, after anything the handler yielded.
		_, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
			Op: hook.OpStream, Table: TableTaskDependencies, Schema: "public",
			Input: input, CallOptions: options,
		}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
			conn := database.Conn(ctx, c.querier)

			fieldOptions := options.FieldOptions
			columns := taskDependencyAllColumns
			if fieldOptions != nil {
				if selected := fieldOptions.Columns(); len(selected) > 0 {
					columns = selected
				}
			}

			var conds []sql.Condition
			if input.Filter != nil {
				conds = input.Filter.ToConditions(c.dialect)
			}

			query, args := sql.BuildSelect(c.dialect, c.table, sql.SelectOptions{
				Columns:    columns,
				Conditions: conds,
				OrderBy:    input.Sorts,
			})

			rows, err := conn.Query(ctx, query, args...)
			if err != nil {
				emit(nil, fmt.Errorf("stream task_dependencies: %w", err))
				return nil, nil
			}
			defer rows.Close()

			for rows.Next() {
				t, err := scanTaskDependencyRow(rows, columns)
				if err != nil {
					if !emit(nil, err) {
						return nil, nil
					}
					continue
				}
				if !emit(t, nil) {
					return nil, nil
				}
			}
			if err := rows.Err(); err != nil {
				emit(nil, fmt.Errorf("iterate task_dependency rows: %w", err))
			}
			return nil, nil
		})
		if err != nil && !stopped {
			yield(nil, err)
		}
	}
}

// TaskDependencyFilter provides type-safe filtering for the task_dependencies table.
type TaskDependencyFilter struct {
	CreatedAt       *comparator.Time                 `json:"created_at"`
	DependsOnTaskID *comparator.ID                   `json:"depends_on_task_id"`
	TaskID          *comparator.ID                   `json:"task_id"`
	Type            *comparator.Enum[DependencyType] `json:"type"`
	PKs             []TaskDependencyPK               `json:"pks"`
	And             []*TaskDependencyFilter          `json:"and"`
	Or              []*TaskDependencyFilter          `json:"or"`
}

// ToConditions converts the filter to a slice of SQL conditions.
//
// A nil receiver contributes no conditions. Two callers depend on that. The
// *Where methods dereference their filter only here and document a nil one as
// the empty-filter case, so this is what makes ErrEmptyFilter reachable instead
// of a nil dereference. And a nil entry inside and / or is skipped rather than
// fatal, matching the "an unset member contributes no SQL" rule the
// relationship members already follow.
func (f *TaskDependencyFilter) ToConditions(dialect sql.Dialect, opts ...FilterOption) []sql.Condition {
	if f == nil {
		return nil
	}

	var conds []sql.Condition

	if f.CreatedAt != nil {
		conds = append(conds, f.CreatedAt.Parse(dialect.QuoteIdentifier("created_at"), dialect)...)
	}

	if f.DependsOnTaskID != nil {
		conds = append(conds, f.DependsOnTaskID.Parse(dialect.QuoteIdentifier("depends_on_task_id"), dialect)...)
	}

	if f.TaskID != nil {
		conds = append(conds, f.TaskID.Parse(dialect.QuoteIdentifier("task_id"), dialect)...)
	}

	if f.Type != nil {
		conds = append(conds, f.Type.Parse(dialect.QuoteIdentifier("type"), dialect)...)
	}

	if len(f.PKs) > 0 {
		var pkConds []sql.Condition
		for _, pk := range f.PKs {
			pkConds = append(pkConds, sql.And(
				sql.Condition{Clause: dialect.QuoteIdentifier("task_id") + " = $", Value: pk.TaskID},
				sql.Condition{Clause: dialect.QuoteIdentifier("depends_on_task_id") + " = $", Value: pk.DependsOnTaskID},
			))
		}
		conds = append(conds, sql.Or(pkConds...))
	}

	for _, sub := range f.And {
		subConds := sub.ToConditions(dialect, opts...)
		if len(subConds) > 0 {
			conds = append(conds, sql.And(subConds...))
		}
	}

	// A filter object's own fields are always conjunctive, so each or member
	// contributes sql.And of its own conditions and the members are OR-ed
	// together as ONE group condition. Appending a per-member
	// sql.Or instead hands the caller N conditions, and buildWhere joins those
	// with AND — turning or: [A, B] into A AND B, while simultaneously OR-ing a
	// single member's own fields against each other.
	//
	// The group is appended only when some member compiled to something:
	// sql.Or of nothing expands to a literal "()", which buildWhere keeps
	// because it is not the empty string, yielding invalid SQL.
	var orGroup []sql.Condition
	for _, sub := range f.Or {
		subConds := sub.ToConditions(dialect, opts...)
		if len(subConds) > 0 {
			orGroup = append(orGroup, sql.And(subConds...))
		}
	}
	if len(orGroup) > 0 {
		conds = append(conds, sql.Or(orGroup...))
	}

	return conds
}

// TaskDependencyFieldOptions controls column selection and relationship loading for task_dependencies queries.
type TaskDependencyFieldOptions struct {
	TaskID          bool `json:"task_id"`
	DependsOnTaskID bool `json:"depends_on_task_id"`
	Type            bool `json:"type"`
	CreatedAt       bool `json:"created_at"`
}

// Columns returns the SQL column names for all selected columns, sorted alphabetically
// to match the SQL builder's deterministic column ordering.
func (fo *TaskDependencyFieldOptions) Columns() []string {
	var cols []string
	if fo.TaskID {
		cols = append(cols, "task_id")
	}
	if fo.DependsOnTaskID {
		cols = append(cols, "depends_on_task_id")
	}
	if fo.Type {
		cols = append(cols, "type")
	}
	if fo.CreatedAt {
		cols = append(cols, "created_at")
	}
	slices.Sort(cols)
	return cols
}

// ColumnMap returns a mapping of Go field name to SQL column name for all columns.
func (fo *TaskDependencyFieldOptions) ColumnMap() map[string]string {
	return map[string]string{
		"TaskID":          "task_id",
		"DependsOnTaskID": "depends_on_task_id",
		"Type":            "type",
		"CreatedAt":       "created_at",
	}
}

// HasSelectedColumns reports whether any column or relationship is selected.
func (fo *TaskDependencyFieldOptions) HasSelectedColumns() bool {
	if fo.TaskID {
		return true
	}
	if fo.DependsOnTaskID {
		return true
	}
	if fo.Type {
		return true
	}
	if fo.CreatedAt {
		return true
	}
	return false
}

// CreateTaskDependencyInput holds the fields for creating a task_dependencies record.
type CreateTaskDependencyInput struct {
	// TaskID - The dependent task
	TaskID uuid.UUID `json:"task_id"`
	// DependsOnTaskID - The task depended upon
	DependsOnTaskID uuid.UUID `json:"depends_on_task_id"`
	// Type - Nature of the dependency
	Type omittable.Value[DependencyType] `json:"type,omitzero"`
	// CreatedAt - Row creation timestamp
	CreatedAt omittable.Value[time.Time] `json:"created_at,omitzero"`
}

// UpdateTaskDependencyInput holds the fields for updating a task_dependencies record.
// All fields use omittable.Value to distinguish "not set" from "set to zero".
type UpdateTaskDependencyInput struct {
	// Type - Nature of the dependency
	Type omittable.Value[DependencyType] `json:"type,omitzero"`
	// CreatedAt - Row creation timestamp
	CreatedAt omittable.Value[time.Time] `json:"created_at,omitzero"`
}

// GetTaskDependenciesInput holds query parameters for retrieving task_dependencies records.
// Field selection is controlled via CallOptions.FieldOptions, not this struct.
type GetTaskDependenciesInput struct {
	Filter *TaskDependencyFilter `json:"filter"`
	Limit  *int                  `json:"limit"`
	Offset *int                  `json:"offset"`
	Sorts  []sql.Sort            `json:"sorts"`
	// conditions holds additional SQL conditions injected by internal callers
	// (e.g., Connection keyset conditions). Not part of the public API.
	conditions []sql.Condition
	// requiredColumns holds columns an internal caller needs read back even
	// when FieldOptions narrows the projection (e.g., Connection cursor keys).
	// Not part of the public API.
	requiredColumns []string
}
