// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package sqlgenresolver

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// coalescedField is one distinct field *name* in a selection set, paired with
// the union of the sub-selections every alias of that name collected.
//
// gqlgen's CollectFields groups by (Name, Alias), not by Name — `a: edges { … }
// b: edges { … }` yields two entries both named "edges". The walkers switch on
// Name and every non-column arm assigns, so without this collapse the last
// alias would win and the others would render off columns the SELECT never
// fetched. Coalescing first restores the invariant the arms are
// written against: each name is handled exactly once, over everything every
// alias of it asked for.
type coalescedField struct {
	Name string
	Sub  []graphql.CollectedField
}

// coalesceAliases collapses aliased duplicates of the same field into one entry
// per name, preserving first-appearance order.
//
// The union is built at the []graphql.CollectedField level rather than by
// concatenating the underlying ast.SelectionSets, deliberately: gqlgen caches
// CollectFields results under a key derived from the *address and length* of
// the selection set passed in, and a slice synthesized here would not be
// retained by that cache — so a later allocation of the same length could land
// on the recycled address and take a stale hit. Collecting each alias's own
// (gqlgen-owned) selections and appending the results keeps every cache key on
// memory gqlgen itself holds.
//
// The scan is linear, matching gqlgen's own getOrCreateAndAppendField: a
// selection set is small, and this keeps the result order-stable without a map.
func coalesceAliases(opCtx *graphql.OperationContext, fields []graphql.CollectedField) []coalescedField {
	out := make([]coalescedField, 0, len(fields))
	for _, f := range fields {
		// A leaf selection (a plain column, `__typename`) has no sub-selections
		// to collect, and CollectFields on an empty set would only churn its
		// cache.
		var sub []graphql.CollectedField
		if len(f.Selections) > 0 {
			sub = graphql.CollectFields(opCtx, f.Selections, nil)
		}
		if i := indexCoalesced(out, f.Name); i >= 0 {
			// Built into a fresh slice rather than appended in place: the base
			// is gqlgen's own cached CollectFields result, and appending into
			// its spare capacity would write through to memory another caller
			// holds.
			merged := make([]graphql.CollectedField, 0, len(out[i].Sub)+len(sub))
			merged = append(merged, out[i].Sub...)
			merged = append(merged, sub...)
			out[i].Sub = merged
			continue
		}
		out = append(out, coalescedField{Name: f.Name, Sub: sub})
	}
	return out
}

// indexCoalesced returns the position of name in fields, or -1.
func indexCoalesced(fields []coalescedField, name string) int {
	for i := range fields {
		if fields[i].Name == name {
			return i
		}
	}
	return -1
}

// unwrapConnectionFields descends through the two envelope shapes the curated
// surface emits — the Relay Connection (`{ edges { node { real fields } } }`)
// and the offset ListResult (`{ items { real fields } totalCount … }`) — so
// the per-table walker only needs to handle real field selections.
// Get queries select columns directly on the type and don't need unwrapping;
// for them this helper returns the input unchanged.
//
// It answers two questions at once, because they have the same source: the
// entity-level selection set, and whether the request needs entity rows at all.
// A count-only envelope selection (`{ totalCount }`) is the one shape that
// reports wantsRows=false — it never reaches a row, so the entry point skips
// the walk, the all-false FieldOptions stands, and the query costs exactly one
// COUNT. Every other selection asks for rows even when it
// names no column: `edges { cursor }`, `edges { __typename }`,
// `edges { node { __typename } }` and every `pageInfo` field are resolved off
// the fetched page — the cursors from the first and last row, hasNextPage from
// the limit+1 probe.
//
// Both envelope branches are gated on the request's parent GraphQL
// type matching the table's `<T>Connection` / `<T>ListResult` envelope name
// (passed in by each per-table entry point). Without the gate a consumer
// schema with a column or relationship literally named `edges` or `items`
// would be misinterpreted as the envelope shape when walking a bare entity
// (e.g. `cart(id) { items { … } }`), silently producing the wrong
// FieldOptions tree.
//
// Emitted once across the whole generated project (single shared impl); every
// per-table FieldOptionsFromContext entry point routes through this helper.
func unwrapConnectionFields(ctx context.Context, fields []graphql.CollectedField, connectionType, listResultType string) ([]graphql.CollectedField, bool) {
	opCtx := graphql.GetOperationContext(ctx)
	parentType := ""
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Field != nil {
		if def := fc.Field.Definition; def != nil && def.Type != nil {
			parentType = def.Type.Name()
		}
	}
	if parentType != connectionType && parentType != listResultType {
		return fields, true
	}
	var entityFields []graphql.CollectedField
	wantsRows := false
	// Coalesced so `a: edges { … } b: edges { … }` is answered over the union of
	// both aliases rather than whichever one the loop visits last.
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "edges":
			if parentType != connectionType {
				continue
			}
			wantsRows = true
			for _, e := range coalesceAliases(opCtx, f.Sub) {
				if e.Name == "node" {
					entityFields = append(entityFields, e.Sub...)
				}
			}
		case "pageInfo":
			// No entity fields of its own, but every PageInfo value is read off
			// the page the connection fetched, so selecting it needs rows.
			if parentType != connectionType {
				continue
			}
			wantsRows = true
		case "items":
			if parentType != listResultType {
				continue
			}
			wantsRows = true
			entityFields = append(entityFields, f.Sub...)
		}
	}
	return entityFields, wantsRows
}
