// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package sqlgenresolver

import (
	"context"

	"github.com/99designs/gqlgen/graphql"

	database "github.com/teandresmith/sqlgen-example/internal/database"
)

// Per-table field-selection walkers. Each pair of functions translates the
// GraphQL selection set in a request context into a fully-populated
// <Table>FieldOptions tree. The walker is the load-bearing
// piece behind the query-count contract: every column and relationship
// in the source schema has a corresponding `case` clause here, so the
// resolver can pre-compute the exact set of fields/relationships to load and
// the unified client issues `1 + count(O2M selected) + 2 * count(M2M selected)`
// queries per request, regardless of result-set size (each M2M edge costs
// two queries — junction + entities).
//
// `<table>FieldOptionsFromContext` is the entry point used by every per-table
// resolver method. It pulls the collected fields out of ctx, descends through
// the conventional Relay Connection shape (`{ edges { node { ... } } }`) via
// the shared `unwrapConnectionFields` helper when present, then forwards to
// the recursive walker. `<table>FieldOptionsFromCollected` is the recursive
// step used both at the top level and when descending into relationships.
//
// A selection set that asks for the row but names no column — `__typename`
// alone, an edge selecting only its `cursor`, a `pageInfo` sub-selection —
// still projects the row's identity columns, because the read path reads an
// all-false FieldOptions as "the caller wants no rows" and would otherwise
// swallow a row the request did ask for. The one selection that
// genuinely wants no rows is a count-only envelope, and it never reaches the
// walker: `unwrapConnectionFields` reports it and the entry point returns the
// all-false value directly.
//
// Fragment & directive handling is delegated to gqlgen's CollectFieldsCtx /
// CollectFields built-ins, which flatten named + inline fragments, apply
// `@skip` / `@include`, and resolve aliases transparently. The walker only
// sees real field names.
//
// "Transparently" resolves the *name*, not the multiplicity: CollectFields
// groups by (Name, Alias), so one selection set naming the same field under two
// aliases hands the walker two entries carrying the same Name. Every arm below
// is written as though a name arrives once, so the fields are run through
// `coalesceAliases` first, which unions the sub-selections of every alias into
// a single entry per name. Relationship fields take no GraphQL
// arguments, so two aliases of one relationship can differ only in
// what they select — the union is the whole of what both asked for, and gqlgen
// renders both aliases from the one load it drives.

// apiTokenFieldOptionsFromContext returns the
// database.APITokenFieldOptions for the current GraphQL request.
func apiTokenFieldOptionsFromContext(ctx context.Context) *database.APITokenFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "APITokenConnection", "APITokenListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.APITokenFieldOptions{}
	}
	return apiTokenFieldOptionsFromCollected(opCtx, entityFields)
}

// apiTokenFieldOptionsFromCollected walks one level of
// the APIToken selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func apiTokenFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.APITokenFieldOptions {
	fo := &database.APITokenFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "userID":
			fo.UserID = true
		case "name":
			fo.Name = true
		case "scopes":
			fo.Scopes = true
		case "lastUsedAt":
			fo.LastUsedAt = true
		case "expiresAt":
			fo.ExpiresAt = true
		case "createdAt":
			fo.CreatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// activityFieldOptionsFromContext returns the
// database.ActivityFieldOptions for the current GraphQL request.
func activityFieldOptionsFromContext(ctx context.Context) *database.ActivityFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "ActivityConnection", "ActivityListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.ActivityFieldOptions{}
	}
	return activityFieldOptionsFromCollected(opCtx, entityFields)
}

// activityFieldOptionsFromCollected walks one level of
// the Activity selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func activityFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.ActivityFieldOptions {
	fo := &database.ActivityFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "actorID":
			fo.ActorID = true
		case "entityTable":
			fo.EntityTable = true
		case "entityID":
			fo.EntityID = true
		case "action":
			fo.Action = true
		case "payload":
			fo.Payload = true
		case "createdAt":
			fo.CreatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// attachmentFieldOptionsFromContext returns the
// database.AttachmentFieldOptions for the current GraphQL request.
func attachmentFieldOptionsFromContext(ctx context.Context) *database.AttachmentFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "AttachmentConnection", "AttachmentListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.AttachmentFieldOptions{}
	}
	return attachmentFieldOptionsFromCollected(opCtx, entityFields)
}

// attachmentFieldOptionsFromCollected walks one level of
// the Attachment selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func attachmentFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.AttachmentFieldOptions {
	fo := &database.AttachmentFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "entityType":
			fo.EntityType = true
		case "entityID":
			fo.EntityID = true
		case "uploadedBy":
			fo.UploadedBy = true
		case "fileName":
			fo.FileName = true
		case "contentType":
			fo.ContentType = true
		case "sizeBytes":
			fo.SizeBytes = true
		case "storageURL":
			fo.StorageURL = true
		case "createdAt":
			fo.CreatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// commentFieldOptionsFromContext returns the
// database.CommentFieldOptions for the current GraphQL request.
func commentFieldOptionsFromContext(ctx context.Context) *database.CommentFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "CommentConnection", "CommentListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.CommentFieldOptions{}
	}
	return commentFieldOptionsFromCollected(opCtx, entityFields)
}

// commentFieldOptionsFromCollected walks one level of
// the Comment selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func commentFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.CommentFieldOptions {
	fo := &database.CommentFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "taskID":
			fo.TaskID = true
		case "authorID":
			fo.AuthorID = true
		case "body":
			fo.Body = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		case "attachments":
			fo.Attachments = &database.AttachmentRelationshipOptions{
				FieldOptions: attachmentFieldOptionsFromCollected(opCtx, f.Sub),
			}
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// cycleFieldOptionsFromContext returns the
// database.CycleFieldOptions for the current GraphQL request.
func cycleFieldOptionsFromContext(ctx context.Context) *database.CycleFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "CycleConnection", "CycleListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.CycleFieldOptions{}
	}
	return cycleFieldOptionsFromCollected(opCtx, entityFields)
}

// cycleFieldOptionsFromCollected walks one level of
// the Cycle selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func cycleFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.CycleFieldOptions {
	fo := &database.CycleFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "teamID":
			fo.TeamID = true
		case "name":
			fo.Name = true
		case "status":
			fo.Status = true
		case "startsOn":
			fo.StartsOn = true
		case "endsOn":
			fo.EndsOn = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		case "tasks":
			fo.Tasks = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// invitationFieldOptionsFromContext returns the
// database.InvitationFieldOptions for the current GraphQL request.
func invitationFieldOptionsFromContext(ctx context.Context) *database.InvitationFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "InvitationConnection", "InvitationListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.InvitationFieldOptions{}
	}
	return invitationFieldOptionsFromCollected(opCtx, entityFields)
}

// invitationFieldOptionsFromCollected walks one level of
// the Invitation selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func invitationFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.InvitationFieldOptions {
	fo := &database.InvitationFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "email":
			fo.Email = true
		case "role":
			fo.Role = true
		case "token":
			fo.Token = true
		case "status":
			fo.Status = true
		case "invitedBy":
			fo.InvitedBy = true
		case "expiresAt":
			fo.ExpiresAt = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// labelFieldOptionsFromContext returns the
// database.LabelFieldOptions for the current GraphQL request.
func labelFieldOptionsFromContext(ctx context.Context) *database.LabelFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "LabelConnection", "LabelListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.LabelFieldOptions{}
	}
	return labelFieldOptionsFromCollected(opCtx, entityFields)
}

// labelFieldOptionsFromCollected walks one level of
// the Label selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func labelFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.LabelFieldOptions {
	fo := &database.LabelFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "name":
			fo.Name = true
		case "color":
			fo.Color = true
		case "createdAt":
			fo.CreatedAt = true
		case "tasks":
			fo.Tasks = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// membershipFieldOptionsFromContext returns the
// database.MembershipFieldOptions for the current GraphQL request.
func membershipFieldOptionsFromContext(ctx context.Context) *database.MembershipFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "MembershipConnection", "MembershipListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.MembershipFieldOptions{}
	}
	return membershipFieldOptionsFromCollected(opCtx, entityFields)
}

// membershipFieldOptionsFromCollected walks one level of
// the Membership selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func membershipFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.MembershipFieldOptions {
	fo := &database.MembershipFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "workspaceID":
			fo.WorkspaceID = true
		case "userID":
			fo.UserID = true
		case "role":
			fo.Role = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.WorkspaceID = true
		fo.UserID = true
	}
	return fo
}

// projectFieldOptionsFromContext returns the
// database.ProjectFieldOptions for the current GraphQL request.
func projectFieldOptionsFromContext(ctx context.Context) *database.ProjectFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "ProjectConnection", "ProjectListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.ProjectFieldOptions{}
	}
	return projectFieldOptionsFromCollected(opCtx, entityFields)
}

// projectFieldOptionsFromCollected walks one level of
// the Project selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func projectFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.ProjectFieldOptions {
	fo := &database.ProjectFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "name":
			fo.Name = true
		case "description":
			fo.Description = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		case "deletedAt":
			fo.DeletedAt = true
		case "teamID":
			fo.TeamID = true
		case "tasks":
			fo.Tasks = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// projectStatFieldOptionsFromContext returns the
// database.ProjectStatFieldOptions for the current GraphQL request.
func projectStatFieldOptionsFromContext(ctx context.Context) *database.ProjectStatFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "ProjectStatConnection", "ProjectStatListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.ProjectStatFieldOptions{}
	}
	return projectStatFieldOptionsFromCollected(opCtx, entityFields)
}

// projectStatFieldOptionsFromCollected walks one level of
// the ProjectStat selection set and produces the corresponding
// FieldOptions tree. A view has no relationships, so this walker is
// columns-only and the read it drives is exactly one query.
func projectStatFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.ProjectStatFieldOptions {
	fo := &database.ProjectStatFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "projectID":
			fo.ProjectID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "totalTasks":
			fo.TotalTasks = true
		case "doneTasks":
			fo.DoneTasks = true
		case "openTasks":
			fo.OpenTasks = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ProjectID = true
	}
	return fo
}

// ssoConnectionFieldOptionsFromContext returns the
// database.SsoConnectionFieldOptions for the current GraphQL request.
func ssoConnectionFieldOptionsFromContext(ctx context.Context) *database.SsoConnectionFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "SsoConnectionConnection", "SsoConnectionListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.SsoConnectionFieldOptions{}
	}
	return ssoConnectionFieldOptionsFromCollected(opCtx, entityFields)
}

// ssoConnectionFieldOptionsFromCollected walks one level of
// the SsoConnection selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func ssoConnectionFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.SsoConnectionFieldOptions {
	fo := &database.SsoConnectionFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "provider":
			fo.Provider = true
		case "config":
			fo.Config = true
		case "enabled":
			fo.Enabled = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// taskFieldOptionsFromContext returns the
// database.TaskFieldOptions for the current GraphQL request.
func taskFieldOptionsFromContext(ctx context.Context) *database.TaskFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "TaskConnection", "TaskListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.TaskFieldOptions{}
	}
	return taskFieldOptionsFromCollected(opCtx, entityFields)
}

// taskFieldOptionsFromCollected walks one level of
// the Task selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func taskFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.TaskFieldOptions {
	fo := &database.TaskFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "projectID":
			fo.ProjectID = true
		case "parentTaskID":
			fo.ParentTaskID = true
		case "reporterID":
			fo.ReporterID = true
		case "title":
			fo.Title = true
		case "description":
			fo.Description = true
		case "status":
			fo.Status = true
		case "priority":
			fo.Priority = true
		case "customFields":
			fo.CustomFields = true
		case "dueAt":
			fo.DueAt = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		case "deletedAt":
			fo.DeletedAt = true
		case "cycleID":
			fo.CycleID = true
		case "assignees":
			fo.Assignees = &database.UserRelationshipOptions{
				FieldOptions: userFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "attachments":
			fo.Attachments = &database.AttachmentRelationshipOptions{
				FieldOptions: attachmentFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "subtasks":
			fo.Subtasks = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "watchers":
			fo.Watchers = &database.UserRelationshipOptions{
				FieldOptions: userFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "comments":
			fo.Comments = &database.CommentRelationshipOptions{
				FieldOptions: commentFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "dependsOnTasks":
			fo.DependsOnTasks = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "labels":
			fo.Labels = &database.LabelRelationshipOptions{
				FieldOptions: labelFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "tasks":
			fo.Tasks = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "timeEntries":
			fo.TimeEntries = &database.TimeEntryRelationshipOptions{
				FieldOptions: timeEntryFieldOptionsFromCollected(opCtx, f.Sub),
			}
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// taskAssigneeFieldOptionsFromContext returns the
// database.TaskAssigneeFieldOptions for the current GraphQL request.
func taskAssigneeFieldOptionsFromContext(ctx context.Context) *database.TaskAssigneeFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "TaskAssigneeConnection", "TaskAssigneeListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.TaskAssigneeFieldOptions{}
	}
	return taskAssigneeFieldOptionsFromCollected(opCtx, entityFields)
}

// taskAssigneeFieldOptionsFromCollected walks one level of
// the TaskAssignee selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func taskAssigneeFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.TaskAssigneeFieldOptions {
	fo := &database.TaskAssigneeFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "taskID":
			fo.TaskID = true
		case "userID":
			fo.UserID = true
		case "assignedAt":
			fo.AssignedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.TaskID = true
		fo.UserID = true
	}
	return fo
}

// taskDependencyFieldOptionsFromContext returns the
// database.TaskDependencyFieldOptions for the current GraphQL request.
func taskDependencyFieldOptionsFromContext(ctx context.Context) *database.TaskDependencyFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "TaskDependencyConnection", "TaskDependencyListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.TaskDependencyFieldOptions{}
	}
	return taskDependencyFieldOptionsFromCollected(opCtx, entityFields)
}

// taskDependencyFieldOptionsFromCollected walks one level of
// the TaskDependency selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func taskDependencyFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.TaskDependencyFieldOptions {
	fo := &database.TaskDependencyFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "taskID":
			fo.TaskID = true
		case "dependsOnTaskID":
			fo.DependsOnTaskID = true
		case "type":
			fo.Type = true
		case "createdAt":
			fo.CreatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.TaskID = true
		fo.DependsOnTaskID = true
	}
	return fo
}

// taskLabelFieldOptionsFromContext returns the
// database.TaskLabelFieldOptions for the current GraphQL request.
func taskLabelFieldOptionsFromContext(ctx context.Context) *database.TaskLabelFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "TaskLabelConnection", "TaskLabelListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.TaskLabelFieldOptions{}
	}
	return taskLabelFieldOptionsFromCollected(opCtx, entityFields)
}

// taskLabelFieldOptionsFromCollected walks one level of
// the TaskLabel selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func taskLabelFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.TaskLabelFieldOptions {
	fo := &database.TaskLabelFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "taskID":
			fo.TaskID = true
		case "labelID":
			fo.LabelID = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.TaskID = true
		fo.LabelID = true
	}
	return fo
}

// taskWatcherFieldOptionsFromContext returns the
// database.TaskWatcherFieldOptions for the current GraphQL request.
func taskWatcherFieldOptionsFromContext(ctx context.Context) *database.TaskWatcherFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "TaskWatcherConnection", "TaskWatcherListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.TaskWatcherFieldOptions{}
	}
	return taskWatcherFieldOptionsFromCollected(opCtx, entityFields)
}

// taskWatcherFieldOptionsFromCollected walks one level of
// the TaskWatcher selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func taskWatcherFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.TaskWatcherFieldOptions {
	fo := &database.TaskWatcherFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "taskID":
			fo.TaskID = true
		case "userID":
			fo.UserID = true
		case "createdAt":
			fo.CreatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.TaskID = true
		fo.UserID = true
	}
	return fo
}

// teamFieldOptionsFromContext returns the
// database.TeamFieldOptions for the current GraphQL request.
func teamFieldOptionsFromContext(ctx context.Context) *database.TeamFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "TeamConnection", "TeamListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.TeamFieldOptions{}
	}
	return teamFieldOptionsFromCollected(opCtx, entityFields)
}

// teamFieldOptionsFromCollected walks one level of
// the Team selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func teamFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.TeamFieldOptions {
	fo := &database.TeamFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "name":
			fo.Name = true
		case "slug":
			fo.Slug = true
		case "description":
			fo.Description = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		case "cycles":
			fo.Cycles = &database.CycleRelationshipOptions{
				FieldOptions: cycleFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "projects":
			fo.Projects = &database.ProjectRelationshipOptions{
				FieldOptions: projectFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "users":
			fo.Users = &database.UserRelationshipOptions{
				FieldOptions: userFieldOptionsFromCollected(opCtx, f.Sub),
			}
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// teamMemberFieldOptionsFromContext returns the
// database.TeamMemberFieldOptions for the current GraphQL request.
func teamMemberFieldOptionsFromContext(ctx context.Context) *database.TeamMemberFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "TeamMemberConnection", "TeamMemberListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.TeamMemberFieldOptions{}
	}
	return teamMemberFieldOptionsFromCollected(opCtx, entityFields)
}

// teamMemberFieldOptionsFromCollected walks one level of
// the TeamMember selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func teamMemberFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.TeamMemberFieldOptions {
	fo := &database.TeamMemberFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "teamID":
			fo.TeamID = true
		case "userID":
			fo.UserID = true
		case "addedAt":
			fo.AddedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.TeamID = true
		fo.UserID = true
	}
	return fo
}

// timeEntryFieldOptionsFromContext returns the
// database.TimeEntryFieldOptions for the current GraphQL request.
func timeEntryFieldOptionsFromContext(ctx context.Context) *database.TimeEntryFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "TimeEntryConnection", "TimeEntryListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.TimeEntryFieldOptions{}
	}
	return timeEntryFieldOptionsFromCollected(opCtx, entityFields)
}

// timeEntryFieldOptionsFromCollected walks one level of
// the TimeEntry selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func timeEntryFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.TimeEntryFieldOptions {
	fo := &database.TimeEntryFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "taskID":
			fo.TaskID = true
		case "userID":
			fo.UserID = true
		case "hours":
			fo.Hours = true
		case "billable":
			fo.Billable = true
		case "notes":
			fo.Notes = true
		case "spentOn":
			fo.SpentOn = true
		case "createdAt":
			fo.CreatedAt = true
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// userFieldOptionsFromContext returns the
// database.UserFieldOptions for the current GraphQL request.
func userFieldOptionsFromContext(ctx context.Context) *database.UserFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "UserConnection", "UserListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.UserFieldOptions{}
	}
	return userFieldOptionsFromCollected(opCtx, entityFields)
}

// userFieldOptionsFromCollected walks one level of
// the User selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func userFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.UserFieldOptions {
	fo := &database.UserFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "email":
			fo.Email = true
		case "displayName":
			fo.DisplayName = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		case "activities":
			fo.Activities = &database.ActivityRelationshipOptions{
				FieldOptions: activityFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "apiTokens":
			fo.APITokens = &database.APITokenRelationshipOptions{
				FieldOptions: apiTokenFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "attachments":
			fo.Attachments = &database.AttachmentRelationshipOptions{
				FieldOptions: attachmentFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "comments":
			fo.Comments = &database.CommentRelationshipOptions{
				FieldOptions: commentFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "invitations":
			fo.Invitations = &database.InvitationRelationshipOptions{
				FieldOptions: invitationFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "reporterTasks":
			fo.ReporterTasks = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "taskAssignees":
			fo.TaskAssignees = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "taskWatchers":
			fo.TaskWatchers = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "teams":
			fo.Teams = &database.TeamRelationshipOptions{
				FieldOptions: teamFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "timeEntries":
			fo.TimeEntries = &database.TimeEntryRelationshipOptions{
				FieldOptions: timeEntryFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "workspaces":
			fo.Workspaces = &database.WorkspaceRelationshipOptions{
				FieldOptions: workspaceFieldOptionsFromCollected(opCtx, f.Sub),
			}
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// workspaceFieldOptionsFromContext returns the
// database.WorkspaceFieldOptions for the current GraphQL request.
func workspaceFieldOptionsFromContext(ctx context.Context) *database.WorkspaceFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "WorkspaceConnection", "WorkspaceListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.WorkspaceFieldOptions{}
	}
	return workspaceFieldOptionsFromCollected(opCtx, entityFields)
}

// workspaceFieldOptionsFromCollected walks one level of
// the Workspace selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func workspaceFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.WorkspaceFieldOptions {
	fo := &database.WorkspaceFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "name":
			fo.Name = true
		case "slug":
			fo.Slug = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		case "activities":
			fo.Activities = &database.ActivityRelationshipOptions{
				FieldOptions: activityFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "apiTokens":
			fo.APITokens = &database.APITokenRelationshipOptions{
				FieldOptions: apiTokenFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "attachments":
			fo.Attachments = &database.AttachmentRelationshipOptions{
				FieldOptions: attachmentFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "comments":
			fo.Comments = &database.CommentRelationshipOptions{
				FieldOptions: commentFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "cycles":
			fo.Cycles = &database.CycleRelationshipOptions{
				FieldOptions: cycleFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "invitations":
			fo.Invitations = &database.InvitationRelationshipOptions{
				FieldOptions: invitationFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "labels":
			fo.Labels = &database.LabelRelationshipOptions{
				FieldOptions: labelFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "projects":
			fo.Projects = &database.ProjectRelationshipOptions{
				FieldOptions: projectFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "ssoConnections":
			fo.SsoConnections = &database.SsoConnectionRelationshipOptions{
				FieldOptions: ssoConnectionFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "tasks":
			fo.Tasks = &database.TaskRelationshipOptions{
				FieldOptions: taskFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "teams":
			fo.Teams = &database.TeamRelationshipOptions{
				FieldOptions: teamFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "timeEntries":
			fo.TimeEntries = &database.TimeEntryRelationshipOptions{
				FieldOptions: timeEntryFieldOptionsFromCollected(opCtx, f.Sub),
			}
		case "users":
			fo.Users = &database.UserRelationshipOptions{
				FieldOptions: userFieldOptionsFromCollected(opCtx, f.Sub),
			}
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}

// workspaceSettingFieldOptionsFromContext returns the
// database.WorkspaceSettingFieldOptions for the current GraphQL request.
func workspaceSettingFieldOptionsFromContext(ctx context.Context) *database.WorkspaceSettingFieldOptions {
	opCtx := graphql.GetOperationContext(ctx)
	fields := graphql.CollectFieldsCtx(ctx, nil)
	entityFields, wantsRows := unwrapConnectionFields(ctx, fields, "WorkspaceSettingConnection", "WorkspaceSettingListResult")
	if !wantsRows {
		// Count-only envelope selection: the request never reaches a row, so
		// the all-false FieldOptions is the right answer and the read
		// short-circuits into a single COUNT.
		return &database.WorkspaceSettingFieldOptions{}
	}
	return workspaceSettingFieldOptionsFromCollected(opCtx, entityFields)
}

// workspaceSettingFieldOptionsFromCollected walks one level of
// the WorkspaceSetting selection set and produces the corresponding
// FieldOptions tree. Recursive descent into relationships re-enters the
// related table's walker on the child's selection set.
func workspaceSettingFieldOptionsFromCollected(opCtx *graphql.OperationContext, fields []graphql.CollectedField) *database.WorkspaceSettingFieldOptions {
	fo := &database.WorkspaceSettingFieldOptions{}
	for _, f := range coalesceAliases(opCtx, fields) {
		switch f.Name {
		case "id":
			fo.ID = true
		case "workspaceID":
			fo.WorkspaceID = true
		case "settings":
			fo.Settings = true
		case "createdAt":
			fo.CreatedAt = true
		case "updatedAt":
			fo.UpdatedAt = true
		case "workspaces":
			fo.Workspaces = workspaceFieldOptionsFromCollected(opCtx, f.Sub)
		}
	}
	if !fo.HasSelectedColumns() {
		// The selection asked for this row but named no column. Projecting the
		// row's identity keeps the all-false short-circuit — which means
		// "the caller wants no rows" — from swallowing it. Columns
		// the read derives rather than returns (cursor keys, relationship
		// mapping keys, O2O NULL-detection keys) are unioned in downstream by
		// the client method that reads them, not here.
		fo.ID = true
	}
	return fo
}
