// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
	"uuid"

	"github.com/shopspring/decimal"
	"github.com/teandresmith/sqlgen-example/internal/database"
	"github.com/teandresmith/sqlgen/types"
)

type APITokenFilter struct {
	WorkspaceID *IDComparator           `json:"workspaceID,omitempty"`
	UserID      *NullableIDComparator   `json:"userID,omitempty"`
	Name        *StringComparator       `json:"name,omitempty"`
	Scopes      *StringSliceComparator  `json:"scopes,omitempty"`
	LastUsedAt  *NullableTimeComparator `json:"lastUsedAt,omitempty"`
	ExpiresAt   *NullableTimeComparator `json:"expiresAt,omitempty"`
	CreatedAt   *TimeComparator         `json:"createdAt,omitempty"`
	And         []*APITokenFilter       `json:"and,omitempty"`
	Or          []*APITokenFilter       `json:"or,omitempty"`
}

type APITokenSort struct {
	Field     APITokenSortField `json:"field"`
	Direction SortDirection     `json:"direction"`
}

type ActivityFilter struct {
	WorkspaceID *IDComparator         `json:"workspaceID,omitempty"`
	ActorID     *NullableIDComparator `json:"actorID,omitempty"`
	EntityTable *StringComparator     `json:"entityTable,omitempty"`
	EntityID    *IDComparator         `json:"entityID,omitempty"`
	Action      *StringComparator     `json:"action,omitempty"`
	Payload     *JSONBComparator      `json:"payload,omitempty"`
	CreatedAt   *TimeComparator       `json:"createdAt,omitempty"`
	And         []*ActivityFilter     `json:"and,omitempty"`
	Or          []*ActivityFilter     `json:"or,omitempty"`
}

type ActivitySort struct {
	Field     ActivitySortField `json:"field"`
	Direction SortDirection     `json:"direction"`
}

type AttachmentEntityTypeComparator struct {
	Eq  *database.AttachmentEntityType  `json:"eq,omitempty"`
	Neq *database.AttachmentEntityType  `json:"neq,omitempty"`
	In  []database.AttachmentEntityType `json:"in,omitempty"`
	Nin []database.AttachmentEntityType `json:"nin,omitempty"`
}

type AttachmentFilter struct {
	WorkspaceID *IDComparator                   `json:"workspaceID,omitempty"`
	EntityType  *AttachmentEntityTypeComparator `json:"entityType,omitempty"`
	EntityID    *IDComparator                   `json:"entityID,omitempty"`
	UploadedBy  *IDComparator                   `json:"uploadedBy,omitempty"`
	FileName    *StringComparator               `json:"fileName,omitempty"`
	ContentType *StringComparator               `json:"contentType,omitempty"`
	SizeBytes   *NumericComparator              `json:"sizeBytes,omitempty"`
	StorageURL  *StringComparator               `json:"storageURL,omitempty"`
	CreatedAt   *TimeComparator                 `json:"createdAt,omitempty"`
	And         []*AttachmentFilter             `json:"and,omitempty"`
	Or          []*AttachmentFilter             `json:"or,omitempty"`
}

type AttachmentSort struct {
	Field     AttachmentSortField `json:"field"`
	Direction SortDirection       `json:"direction"`
}

// The result of a successful register or login: a signed JWT bearer token and the
// authenticated User. The token carries the User identity only and binds the
// caller to no Workspace (ADR-0004).
type AuthPayload struct {
	Token string         `json:"token"`
	User  *database.User `json:"user"`
}

type BooleanComparator struct {
	Eq  *bool `json:"eq,omitempty"`
	Neq *bool `json:"neq,omitempty"`
}

// Details for founding a new Workspace. The caller (from the request's bearer
// token) becomes the Workspace's `owner`; no Workspace is selected via
// X-Workspace-Id for this operation.
type BootstrapWorkspaceInput struct {
	// Human-readable workspace name
	Name string `json:"name"`
	// URL-safe unique short name
	Slug string `json:"slug"`
}

type CommentFilter struct {
	WorkspaceID *IDComparator     `json:"workspaceID,omitempty"`
	TaskID      *IDComparator     `json:"taskID,omitempty"`
	AuthorID    *IDComparator     `json:"authorID,omitempty"`
	Body        *StringComparator `json:"body,omitempty"`
	CreatedAt   *TimeComparator   `json:"createdAt,omitempty"`
	UpdatedAt   *TimeComparator   `json:"updatedAt,omitempty"`
	Attachments *AttachmentFilter `json:"attachments,omitempty"`
	And         []*CommentFilter  `json:"and,omitempty"`
	Or          []*CommentFilter  `json:"or,omitempty"`
}

type CommentSort struct {
	Field     CommentSortField `json:"field"`
	Direction SortDirection    `json:"direction"`
}

// Details for configuring a Workspace's single sign-on connection. The Workspace is
// the Active Workspace (auto-injected); a connection is identified by its provider,
// so re-configuring the same provider updates the existing connection.
type ConfigureSSOConnectionInput struct {
	// Identity provider protocol/vendor.
	Provider database.SsoProvider `json:"provider"`
	// Provider-specific configuration (metadata URL, client IDs, etc.).
	Config types.JSON `json:"config"`
	// Whether the connection is active. Omit to default to disabled.
	Enabled *bool `json:"enabled,omitempty"`
}

// Details for minting an API Token in the caller's Active Workspace. Only the
// label, optional scopes, and optional expiry are client-controlled; the secret,
// its hash, the owning User (for a personal token), and the Workspace are all set
// server-side.
type CreateAPITokenInput struct {
	// Human-readable label for the token.
	Name string `json:"name"`
	// Granted permission scopes (recorded; enforcement is out of scope per the PRD). Omit for none.
	Scopes []string `json:"scopes,omitempty"`
	// Optional expiry; omit for a token that never expires.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// The result of minting an API Token. The secret is returned exactly once, at
// creation — it is stored only as a hash and can never be retrieved again.
type CreateAPITokenResult struct {
	// The created API Token (metadata only — the secret it authenticates with is never stored in plaintext).
	APIToken *database.APIToken `json:"apiToken"`
	// The plaintext token secret, shown exactly once. Store it now; it cannot be recovered.
	Secret string `json:"secret"`
}

type CreateActivityInput struct {
	WorkspaceID uuid.UUID  `json:"workspaceID"`
	ActorID     *uuid.UUID `json:"actorID,omitempty"`
	EntityTable string     `json:"entityTable"`
	EntityID    uuid.UUID  `json:"entityID"`
	Action      string     `json:"action"`
	Payload     types.JSON `json:"payload"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type CreateCycleInput struct {
	WorkspaceID uuid.UUID            `json:"workspaceID"`
	TeamID      *uuid.UUID           `json:"teamID,omitempty"`
	Name        string               `json:"name"`
	Status      database.CycleStatus `json:"status"`
	StartsOn    time.Time            `json:"startsOn"`
	EndsOn      time.Time            `json:"endsOn"`
	CreatedAt   time.Time            `json:"createdAt"`
	UpdatedAt   time.Time            `json:"updatedAt"`
}

type CreateLabelInput struct {
	WorkspaceID uuid.UUID `json:"workspaceID"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"createdAt"`
}

type CreateProjectInput struct {
	WorkspaceID uuid.UUID  `json:"workspaceID"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
	TeamID      *uuid.UUID `json:"teamID,omitempty"`
}

// Details for creating a Task in a Project. The Reporter is not part of the input:
// it is set server-side to the authenticated caller (PRD story 30), and the owning
// Workspace is injected from the Active Workspace by tenant scoping — a client
// controls only the work item's own fields.
type CreateTaskInProjectInput struct {
	// Project the Task belongs to; must live in the Active Workspace
	ProjectID uuid.UUID `json:"projectID"`
	// Parent Task for a Subtask; omit for a top-level Task (PRD story 22)
	ParentTaskID *uuid.UUID `json:"parentTaskID,omitempty"`
	// Short task summary
	Title string `json:"title"`
	// Optional long-form description
	Description *string `json:"description,omitempty"`
	// Initial lifecycle state; defaults to BACKLOG when omitted
	Status *database.TaskStatus `json:"status,omitempty"`
	// Relative urgency; defaults to MEDIUM when omitted
	Priority *database.TaskPriority `json:"priority,omitempty"`
}

type CreateTaskInput struct {
	WorkspaceID  uuid.UUID             `json:"workspaceID"`
	ProjectID    uuid.UUID             `json:"projectID"`
	ParentTaskID *uuid.UUID            `json:"parentTaskID,omitempty"`
	ReporterID   uuid.UUID             `json:"reporterID"`
	Title        string                `json:"title"`
	Description  *string               `json:"description,omitempty"`
	Status       database.TaskStatus   `json:"status"`
	Priority     database.TaskPriority `json:"priority"`
	CustomFields types.JSON            `json:"customFields"`
	DueAt        *time.Time            `json:"dueAt,omitempty"`
	CreatedAt    time.Time             `json:"createdAt"`
	UpdatedAt    time.Time             `json:"updatedAt"`
	DeletedAt    *time.Time            `json:"deletedAt,omitempty"`
	CycleID      *uuid.UUID            `json:"cycleID,omitempty"`
}

type CreateTeamInput struct {
	WorkspaceID uuid.UUID `json:"workspaceID"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type CreateUserInput struct {
	Email        string    `json:"email"`
	DisplayName  string    `json:"displayName"`
	PasswordHash string    `json:"passwordHash"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type CreateWorkspaceInput struct {
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type CreateWorkspaceSettingInput struct {
	WorkspaceID uuid.UUID  `json:"workspaceID"`
	Settings    types.JSON `json:"settings"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

type CycleFilter struct {
	WorkspaceID *IDComparator          `json:"workspaceID,omitempty"`
	TeamID      *NullableIDComparator  `json:"teamID,omitempty"`
	Name        *StringComparator      `json:"name,omitempty"`
	Status      *CycleStatusComparator `json:"status,omitempty"`
	StartsOn    *TimeComparator        `json:"startsOn,omitempty"`
	EndsOn      *TimeComparator        `json:"endsOn,omitempty"`
	CreatedAt   *TimeComparator        `json:"createdAt,omitempty"`
	UpdatedAt   *TimeComparator        `json:"updatedAt,omitempty"`
	Tasks       *TaskFilter            `json:"tasks,omitempty"`
	And         []*CycleFilter         `json:"and,omitempty"`
	Or          []*CycleFilter         `json:"or,omitempty"`
}

type CycleSort struct {
	Field     CycleSortField `json:"field"`
	Direction SortDirection  `json:"direction"`
}

type CycleStatusComparator struct {
	Eq  *database.CycleStatus  `json:"eq,omitempty"`
	Neq *database.CycleStatus  `json:"neq,omitempty"`
	In  []database.CycleStatus `json:"in,omitempty"`
	Nin []database.CycleStatus `json:"nin,omitempty"`
}

type CycleTasksCreateInput struct {
	WorkspaceID  uuid.UUID             `json:"workspaceID"`
	ProjectID    uuid.UUID             `json:"projectID"`
	ParentTaskID *uuid.UUID            `json:"parentTaskID,omitempty"`
	ReporterID   uuid.UUID             `json:"reporterID"`
	Title        string                `json:"title"`
	Description  *string               `json:"description,omitempty"`
	Status       database.TaskStatus   `json:"status"`
	Priority     database.TaskPriority `json:"priority"`
	CustomFields types.JSON            `json:"customFields"`
	DueAt        *time.Time            `json:"dueAt,omitempty"`
	CreatedAt    time.Time             `json:"createdAt"`
	UpdatedAt    time.Time             `json:"updatedAt"`
	DeletedAt    *time.Time            `json:"deletedAt,omitempty"`
}

type CycleTasksUpdateNested struct {
	Clear      *bool                    `json:"clear,omitempty"`
	Create     []*CycleTasksCreateInput `json:"create,omitempty"`
	Connect    []uuid.UUID              `json:"connect,omitempty"`
	Disconnect []uuid.UUID              `json:"disconnect,omitempty"`
}

type DecimalComparator struct {
	Eq  *decimal.Decimal   `json:"eq,omitempty"`
	Neq *decimal.Decimal   `json:"neq,omitempty"`
	Gt  *decimal.Decimal   `json:"gt,omitempty"`
	Gte *decimal.Decimal   `json:"gte,omitempty"`
	Lt  *decimal.Decimal   `json:"lt,omitempty"`
	Lte *decimal.Decimal   `json:"lte,omitempty"`
	In  []*decimal.Decimal `json:"in,omitempty"`
	Nin []*decimal.Decimal `json:"nin,omitempty"`
}

type DependencyTypeComparator struct {
	Eq  *database.DependencyType  `json:"eq,omitempty"`
	Neq *database.DependencyType  `json:"neq,omitempty"`
	In  []database.DependencyType `json:"in,omitempty"`
	Nin []database.DependencyType `json:"nin,omitempty"`
}

type IDComparator struct {
	Eq  *string  `json:"eq,omitempty"`
	Neq *string  `json:"neq,omitempty"`
	Gt  *string  `json:"gt,omitempty"`
	Gte *string  `json:"gte,omitempty"`
	Lt  *string  `json:"lt,omitempty"`
	Lte *string  `json:"lte,omitempty"`
	In  []string `json:"in,omitempty"`
	Nin []string `json:"nin,omitempty"`
}

type InvitationFilter struct {
	WorkspaceID *IDComparator               `json:"workspaceID,omitempty"`
	Email       *StringComparator           `json:"email,omitempty"`
	Role        *MembershipRoleComparator   `json:"role,omitempty"`
	Token       *StringComparator           `json:"token,omitempty"`
	Status      *InvitationStatusComparator `json:"status,omitempty"`
	InvitedBy   *IDComparator               `json:"invitedBy,omitempty"`
	ExpiresAt   *TimeComparator             `json:"expiresAt,omitempty"`
	CreatedAt   *TimeComparator             `json:"createdAt,omitempty"`
	UpdatedAt   *TimeComparator             `json:"updatedAt,omitempty"`
	And         []*InvitationFilter         `json:"and,omitempty"`
	Or          []*InvitationFilter         `json:"or,omitempty"`
}

type InvitationSort struct {
	Field     InvitationSortField `json:"field"`
	Direction SortDirection       `json:"direction"`
}

type InvitationStatusComparator struct {
	Eq  *database.InvitationStatus  `json:"eq,omitempty"`
	Neq *database.InvitationStatus  `json:"neq,omitempty"`
	In  []database.InvitationStatus `json:"in,omitempty"`
	Nin []database.InvitationStatus `json:"nin,omitempty"`
}

// Details for inviting a person to the caller's Active Workspace. The invitee is
// named only by email — they need not yet have a User account. Everything else
// about the Invitation (its token, pending status, issuer, and expiry) is set
// server-side.
type InviteToWorkspaceInput struct {
	// Email address to invite; the invitee accepts by matching it at login
	Email string `json:"email"`
	// Role the invitee receives on acceptance
	Role database.MembershipRole `json:"role"`
}

type JSONBComparator struct {
	HasKey      *string    `json:"hasKey,omitempty"`
	HasAnyKey   []string   `json:"hasAnyKey,omitempty"`
	HasAllKeys  []string   `json:"hasAllKeys,omitempty"`
	Contains    types.JSON `json:"contains,omitempty"`
	ContainedBy types.JSON `json:"containedBy,omitempty"`
	PathExists  *string    `json:"pathExists,omitempty"`
}

type LabelFilter struct {
	WorkspaceID *IDComparator     `json:"workspaceID,omitempty"`
	Name        *StringComparator `json:"name,omitempty"`
	Color       *StringComparator `json:"color,omitempty"`
	CreatedAt   *TimeComparator   `json:"createdAt,omitempty"`
	Tasks       *TaskFilter       `json:"tasks,omitempty"`
	And         []*LabelFilter    `json:"and,omitempty"`
	Or          []*LabelFilter    `json:"or,omitempty"`
}

type LabelSort struct {
	Field     LabelSortField `json:"field"`
	Direction SortDirection  `json:"direction"`
}

// Credentials for an interactive login.
type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MembershipFilter struct {
	Role      *MembershipRoleComparator `json:"role,omitempty"`
	CreatedAt *TimeComparator           `json:"createdAt,omitempty"`
	UpdatedAt *TimeComparator           `json:"updatedAt,omitempty"`
	And       []*MembershipFilter       `json:"and,omitempty"`
	Or        []*MembershipFilter       `json:"or,omitempty"`
}

type MembershipRoleComparator struct {
	Eq  *database.MembershipRole  `json:"eq,omitempty"`
	Neq *database.MembershipRole  `json:"neq,omitempty"`
	In  []database.MembershipRole `json:"in,omitempty"`
	Nin []database.MembershipRole `json:"nin,omitempty"`
}

type MembershipSort struct {
	Field     MembershipSortField `json:"field"`
	Direction SortDirection       `json:"direction"`
}

type Mutation struct {
}

type NullableIDComparator struct {
	Eq     *string  `json:"eq,omitempty"`
	Neq    *string  `json:"neq,omitempty"`
	Gt     *string  `json:"gt,omitempty"`
	Gte    *string  `json:"gte,omitempty"`
	Lt     *string  `json:"lt,omitempty"`
	Lte    *string  `json:"lte,omitempty"`
	In     []string `json:"in,omitempty"`
	Nin    []string `json:"nin,omitempty"`
	IsNull *bool    `json:"isNull,omitempty"`
}

type NullableStringComparator struct {
	Eq         *string  `json:"eq,omitempty"`
	Neq        *string  `json:"neq,omitempty"`
	Gt         *string  `json:"gt,omitempty"`
	Gte        *string  `json:"gte,omitempty"`
	Lt         *string  `json:"lt,omitempty"`
	Lte        *string  `json:"lte,omitempty"`
	Contains   *string  `json:"contains,omitempty"`
	StartsWith *string  `json:"startsWith,omitempty"`
	EndsWith   *string  `json:"endsWith,omitempty"`
	Like       *string  `json:"like,omitempty"`
	Nlike      *string  `json:"nlike,omitempty"`
	In         []string `json:"in,omitempty"`
	Nin        []string `json:"nin,omitempty"`
	IsNull     *bool    `json:"isNull,omitempty"`
}

type NullableTimeComparator struct {
	Eq       *time.Time   `json:"eq,omitempty"`
	Neq      *time.Time   `json:"neq,omitempty"`
	Gt       *time.Time   `json:"gt,omitempty"`
	Gte      *time.Time   `json:"gte,omitempty"`
	Lt       *time.Time   `json:"lt,omitempty"`
	Lte      *time.Time   `json:"lte,omitempty"`
	In       []*time.Time `json:"in,omitempty"`
	Nin      []*time.Time `json:"nin,omitempty"`
	Between  *TimeRange   `json:"between,omitempty"`
	Nbetween *TimeRange   `json:"nbetween,omitempty"`
	IsNull   *bool        `json:"isNull,omitempty"`
}

type NumericComparator struct {
	Eq       *float64      `json:"eq,omitempty"`
	Neq      *float64      `json:"neq,omitempty"`
	Gt       *float64      `json:"gt,omitempty"`
	Gte      *float64      `json:"gte,omitempty"`
	Lt       *float64      `json:"lt,omitempty"`
	Lte      *float64      `json:"lte,omitempty"`
	In       []float64     `json:"in,omitempty"`
	Nin      []float64     `json:"nin,omitempty"`
	Between  *NumericRange `json:"between,omitempty"`
	Nbetween *NumericRange `json:"nbetween,omitempty"`
}

type NumericRange struct {
	From float64 `json:"from"`
	To   float64 `json:"to"`
}

type ProjectFilter struct {
	WorkspaceID *IDComparator             `json:"workspaceID,omitempty"`
	Name        *StringComparator         `json:"name,omitempty"`
	Description *NullableStringComparator `json:"description,omitempty"`
	CreatedAt   *TimeComparator           `json:"createdAt,omitempty"`
	UpdatedAt   *TimeComparator           `json:"updatedAt,omitempty"`
	DeletedAt   *NullableTimeComparator   `json:"deletedAt,omitempty"`
	TeamID      *NullableIDComparator     `json:"teamID,omitempty"`
	Tasks       *TaskFilter               `json:"tasks,omitempty"`
	And         []*ProjectFilter          `json:"and,omitempty"`
	Or          []*ProjectFilter          `json:"or,omitempty"`
}

type ProjectSort struct {
	Field     ProjectSortField `json:"field"`
	Direction SortDirection    `json:"direction"`
}

type ProjectStatFilter struct {
	WorkspaceID *StringComparator    `json:"workspaceID,omitempty"`
	TotalTasks  *NumericComparator   `json:"totalTasks,omitempty"`
	DoneTasks   *NumericComparator   `json:"doneTasks,omitempty"`
	OpenTasks   *NumericComparator   `json:"openTasks,omitempty"`
	And         []*ProjectStatFilter `json:"and,omitempty"`
	Or          []*ProjectStatFilter `json:"or,omitempty"`
}

type ProjectStatSort struct {
	Field     ProjectStatSortField `json:"field"`
	Direction SortDirection        `json:"direction"`
}

type Query struct {
}

// Credentials and profile for registering a new global User.
type RegisterInput struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"displayName"`
}

type SsoConnectionFilter struct {
	WorkspaceID *IDComparator          `json:"workspaceID,omitempty"`
	Provider    *SsoProviderComparator `json:"provider,omitempty"`
	Config      *JSONBComparator       `json:"config,omitempty"`
	Enabled     *BooleanComparator     `json:"enabled,omitempty"`
	CreatedAt   *TimeComparator        `json:"createdAt,omitempty"`
	UpdatedAt   *TimeComparator        `json:"updatedAt,omitempty"`
	And         []*SsoConnectionFilter `json:"and,omitempty"`
	Or          []*SsoConnectionFilter `json:"or,omitempty"`
}

type SsoConnectionSort struct {
	Field     SsoConnectionSortField `json:"field"`
	Direction SortDirection          `json:"direction"`
}

type SsoProviderComparator struct {
	Eq  *database.SsoProvider  `json:"eq,omitempty"`
	Neq *database.SsoProvider  `json:"neq,omitempty"`
	In  []database.SsoProvider `json:"in,omitempty"`
	Nin []database.SsoProvider `json:"nin,omitempty"`
}

type StringComparator struct {
	Eq         *string  `json:"eq,omitempty"`
	Neq        *string  `json:"neq,omitempty"`
	Gt         *string  `json:"gt,omitempty"`
	Gte        *string  `json:"gte,omitempty"`
	Lt         *string  `json:"lt,omitempty"`
	Lte        *string  `json:"lte,omitempty"`
	Contains   *string  `json:"contains,omitempty"`
	StartsWith *string  `json:"startsWith,omitempty"`
	EndsWith   *string  `json:"endsWith,omitempty"`
	Like       *string  `json:"like,omitempty"`
	Nlike      *string  `json:"nlike,omitempty"`
	In         []string `json:"in,omitempty"`
	Nin        []string `json:"nin,omitempty"`
}

type StringSliceComparator struct {
	ContainsAny []string `json:"containsAny,omitempty"`
	ContainsAll []string `json:"containsAll,omitempty"`
	ContainedBy []string `json:"containedBy,omitempty"`
	IsEmpty     *bool    `json:"isEmpty,omitempty"`
}

type TaskAssigneeFilter struct {
	AssignedAt *TimeComparator       `json:"assignedAt,omitempty"`
	And        []*TaskAssigneeFilter `json:"and,omitempty"`
	Or         []*TaskAssigneeFilter `json:"or,omitempty"`
}

type TaskAssigneeSort struct {
	Field     TaskAssigneeSortField `json:"field"`
	Direction SortDirection         `json:"direction"`
}

type TaskDependencyFilter struct {
	Type      *DependencyTypeComparator `json:"type,omitempty"`
	CreatedAt *TimeComparator           `json:"createdAt,omitempty"`
	And       []*TaskDependencyFilter   `json:"and,omitempty"`
	Or        []*TaskDependencyFilter   `json:"or,omitempty"`
}

type TaskDependencySort struct {
	Field     TaskDependencySortField `json:"field"`
	Direction SortDirection           `json:"direction"`
}

type TaskFilter struct {
	WorkspaceID    *IDComparator             `json:"workspaceID,omitempty"`
	ProjectID      *IDComparator             `json:"projectID,omitempty"`
	ParentTaskID   *NullableIDComparator     `json:"parentTaskID,omitempty"`
	ReporterID     *IDComparator             `json:"reporterID,omitempty"`
	Title          *StringComparator         `json:"title,omitempty"`
	Description    *NullableStringComparator `json:"description,omitempty"`
	Status         *TaskStatusComparator     `json:"status,omitempty"`
	Priority       *TaskPriorityComparator   `json:"priority,omitempty"`
	CustomFields   *JSONBComparator          `json:"customFields,omitempty"`
	DueAt          *NullableTimeComparator   `json:"dueAt,omitempty"`
	CreatedAt      *TimeComparator           `json:"createdAt,omitempty"`
	UpdatedAt      *TimeComparator           `json:"updatedAt,omitempty"`
	DeletedAt      *NullableTimeComparator   `json:"deletedAt,omitempty"`
	CycleID        *NullableIDComparator     `json:"cycleID,omitempty"`
	Assignees      *UserFilter               `json:"assignees,omitempty"`
	Attachments    *AttachmentFilter         `json:"attachments,omitempty"`
	Comments       *CommentFilter            `json:"comments,omitempty"`
	DependsOnTasks *TaskFilter               `json:"dependsOnTasks,omitempty"`
	Labels         *LabelFilter              `json:"labels,omitempty"`
	Subtasks       *TaskFilter               `json:"subtasks,omitempty"`
	Tasks          *TaskFilter               `json:"tasks,omitempty"`
	TimeEntries    *TimeEntryFilter          `json:"timeEntries,omitempty"`
	Watchers       *UserFilter               `json:"watchers,omitempty"`
	And            []*TaskFilter             `json:"and,omitempty"`
	Or             []*TaskFilter             `json:"or,omitempty"`
}

type TaskLabelFilter struct {
	And []*TaskLabelFilter `json:"and,omitempty"`
	Or  []*TaskLabelFilter `json:"or,omitempty"`
}

type TaskLabelSort struct {
	Field     TaskLabelSortField `json:"field"`
	Direction SortDirection      `json:"direction"`
}

type TaskLabelsUpdateNested struct {
	Clear      *bool               `json:"clear,omitempty"`
	Create     []*CreateLabelInput `json:"create,omitempty"`
	Connect    []uuid.UUID         `json:"connect,omitempty"`
	Disconnect []uuid.UUID         `json:"disconnect,omitempty"`
}

type TaskPriorityComparator struct {
	Eq  *database.TaskPriority  `json:"eq,omitempty"`
	Neq *database.TaskPriority  `json:"neq,omitempty"`
	In  []database.TaskPriority `json:"in,omitempty"`
	Nin []database.TaskPriority `json:"nin,omitempty"`
}

type TaskSort struct {
	Field     TaskSortField `json:"field"`
	Direction SortDirection `json:"direction"`
}

type TaskStatusComparator struct {
	Eq  *database.TaskStatus  `json:"eq,omitempty"`
	Neq *database.TaskStatus  `json:"neq,omitempty"`
	In  []database.TaskStatus `json:"in,omitempty"`
	Nin []database.TaskStatus `json:"nin,omitempty"`
}

type TaskWatcherFilter struct {
	CreatedAt *TimeComparator      `json:"createdAt,omitempty"`
	And       []*TaskWatcherFilter `json:"and,omitempty"`
	Or        []*TaskWatcherFilter `json:"or,omitempty"`
}

type TaskWatcherSort struct {
	Field     TaskWatcherSortField `json:"field"`
	Direction SortDirection        `json:"direction"`
}

type TeamFilter struct {
	WorkspaceID *IDComparator             `json:"workspaceID,omitempty"`
	Name        *StringComparator         `json:"name,omitempty"`
	Slug        *StringComparator         `json:"slug,omitempty"`
	Description *NullableStringComparator `json:"description,omitempty"`
	CreatedAt   *TimeComparator           `json:"createdAt,omitempty"`
	UpdatedAt   *TimeComparator           `json:"updatedAt,omitempty"`
	Cycles      *CycleFilter              `json:"cycles,omitempty"`
	Projects    *ProjectFilter            `json:"projects,omitempty"`
	Users       *UserFilter               `json:"users,omitempty"`
	And         []*TeamFilter             `json:"and,omitempty"`
	Or          []*TeamFilter             `json:"or,omitempty"`
}

type TeamMemberFilter struct {
	AddedAt *TimeComparator     `json:"addedAt,omitempty"`
	And     []*TeamMemberFilter `json:"and,omitempty"`
	Or      []*TeamMemberFilter `json:"or,omitempty"`
}

type TeamMemberSort struct {
	Field     TeamMemberSortField `json:"field"`
	Direction SortDirection       `json:"direction"`
}

type TeamProjectsCreateInput struct {
	WorkspaceID uuid.UUID  `json:"workspaceID"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
}

type TeamProjectsUpdateNested struct {
	Clear      *bool                      `json:"clear,omitempty"`
	Create     []*TeamProjectsCreateInput `json:"create,omitempty"`
	Connect    []uuid.UUID                `json:"connect,omitempty"`
	Disconnect []uuid.UUID                `json:"disconnect,omitempty"`
}

type TeamSort struct {
	Field     TeamSortField `json:"field"`
	Direction SortDirection `json:"direction"`
}

type TimeComparator struct {
	Eq       *time.Time   `json:"eq,omitempty"`
	Neq      *time.Time   `json:"neq,omitempty"`
	Gt       *time.Time   `json:"gt,omitempty"`
	Gte      *time.Time   `json:"gte,omitempty"`
	Lt       *time.Time   `json:"lt,omitempty"`
	Lte      *time.Time   `json:"lte,omitempty"`
	In       []*time.Time `json:"in,omitempty"`
	Nin      []*time.Time `json:"nin,omitempty"`
	Between  *TimeRange   `json:"between,omitempty"`
	Nbetween *TimeRange   `json:"nbetween,omitempty"`
}

type TimeEntryFilter struct {
	WorkspaceID *IDComparator             `json:"workspaceID,omitempty"`
	TaskID      *IDComparator             `json:"taskID,omitempty"`
	UserID      *IDComparator             `json:"userID,omitempty"`
	Hours       *DecimalComparator        `json:"hours,omitempty"`
	Billable    *BooleanComparator        `json:"billable,omitempty"`
	Notes       *NullableStringComparator `json:"notes,omitempty"`
	SpentOn     *TimeComparator           `json:"spentOn,omitempty"`
	CreatedAt   *TimeComparator           `json:"createdAt,omitempty"`
	And         []*TimeEntryFilter        `json:"and,omitempty"`
	Or          []*TimeEntryFilter        `json:"or,omitempty"`
}

type TimeEntrySort struct {
	Field     TimeEntrySortField `json:"field"`
	Direction SortDirection      `json:"direction"`
}

type TimeRange struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

type UpdateActivityInput struct {
	ActorID     *uuid.UUID `json:"actorID,omitempty"`
	EntityTable *string    `json:"entityTable,omitempty"`
	EntityID    *uuid.UUID `json:"entityID,omitempty"`
	Action      *string    `json:"action,omitempty"`
	Payload     types.JSON `json:"payload,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
}

type UpdateAttachmentInput struct {
	EntityType   *database.AttachmentEntityType `json:"entityType,omitempty"`
	EntityID     *uuid.UUID                     `json:"entityID,omitempty"`
	UploadedBy   *uuid.UUID                     `json:"uploadedBy,omitempty"`
	FileName     *string                        `json:"fileName,omitempty"`
	ContentType  *string                        `json:"contentType,omitempty"`
	SizeBytes    *int                           `json:"sizeBytes,omitempty"`
	SizeBytesInc *int                           `json:"sizeBytes_inc,omitempty"`
	SizeBytesDec *int                           `json:"sizeBytes_dec,omitempty"`
	StorageURL   *string                        `json:"storageURL,omitempty"`
	CreatedAt    *time.Time                     `json:"createdAt,omitempty"`
}

type UpdateCommentInput struct {
	TaskID    *uuid.UUID `json:"taskID,omitempty"`
	AuthorID  *uuid.UUID `json:"authorID,omitempty"`
	Body      *string    `json:"body,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type UpdateCycleInput struct {
	TeamID    *uuid.UUID            `json:"teamID,omitempty"`
	Name      *string               `json:"name,omitempty"`
	Status    *database.CycleStatus `json:"status,omitempty"`
	StartsOn  *time.Time            `json:"startsOn,omitempty"`
	EndsOn    *time.Time            `json:"endsOn,omitempty"`
	CreatedAt *time.Time            `json:"createdAt,omitempty"`
	UpdatedAt *time.Time            `json:"updatedAt,omitempty"`
}

type UpdateCycleWithRelatedInput struct {
	Cycle *UpdateCycleInput       `json:"cycle,omitempty"`
	Tasks *CycleTasksUpdateNested `json:"tasks,omitempty"`
}

type UpdateLabelInput struct {
	Name      *string    `json:"name,omitempty"`
	Color     *string    `json:"color,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

type UpdateMembershipInput struct {
	Role      *database.MembershipRole `json:"role,omitempty"`
	CreatedAt *time.Time               `json:"createdAt,omitempty"`
	UpdatedAt *time.Time               `json:"updatedAt,omitempty"`
}

type UpdateProjectInput struct {
	Name        *string    `json:"name,omitempty"`
	Description *string    `json:"description,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
	TeamID      *uuid.UUID `json:"teamID,omitempty"`
}

type UpdateTaskAssigneeInput struct {
	AssignedAt *time.Time `json:"assignedAt,omitempty"`
}

type UpdateTaskDependencyInput struct {
	Type      *database.DependencyType `json:"type,omitempty"`
	CreatedAt *time.Time               `json:"createdAt,omitempty"`
}

type UpdateTaskInput struct {
	ProjectID    *uuid.UUID             `json:"projectID,omitempty"`
	ParentTaskID *uuid.UUID             `json:"parentTaskID,omitempty"`
	ReporterID   *uuid.UUID             `json:"reporterID,omitempty"`
	Title        *string                `json:"title,omitempty"`
	Description  *string                `json:"description,omitempty"`
	Status       *database.TaskStatus   `json:"status,omitempty"`
	Priority     *database.TaskPriority `json:"priority,omitempty"`
	CustomFields types.JSON             `json:"customFields,omitempty"`
	DueAt        *time.Time             `json:"dueAt,omitempty"`
	CreatedAt    *time.Time             `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time             `json:"updatedAt,omitempty"`
	DeletedAt    *time.Time             `json:"deletedAt,omitempty"`
	CycleID      *uuid.UUID             `json:"cycleID,omitempty"`
}

type UpdateTaskWatcherInput struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

type UpdateTaskWithRelatedInput struct {
	Task   *UpdateTaskInput        `json:"task,omitempty"`
	Labels *TaskLabelsUpdateNested `json:"labels,omitempty"`
}

type UpdateTeamInput struct {
	Name        *string    `json:"name,omitempty"`
	Slug        *string    `json:"slug,omitempty"`
	Description *string    `json:"description,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

type UpdateTeamWithRelatedInput struct {
	Team     *UpdateTeamInput          `json:"team,omitempty"`
	Projects *TeamProjectsUpdateNested `json:"projects,omitempty"`
}

type UpdateTimeEntryInput struct {
	TaskID    *uuid.UUID       `json:"taskID,omitempty"`
	UserID    *uuid.UUID       `json:"userID,omitempty"`
	Hours     *decimal.Decimal `json:"hours,omitempty"`
	HoursInc  *int             `json:"hours_inc,omitempty"`
	HoursDec  *int             `json:"hours_dec,omitempty"`
	Billable  *bool            `json:"billable,omitempty"`
	Notes     *string          `json:"notes,omitempty"`
	SpentOn   *time.Time       `json:"spentOn,omitempty"`
	CreatedAt *time.Time       `json:"createdAt,omitempty"`
}

type UpdateUserInput struct {
	Email        *string    `json:"email,omitempty"`
	DisplayName  *string    `json:"displayName,omitempty"`
	PasswordHash *string    `json:"passwordHash,omitempty"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
}

type UpdateWorkspaceInput struct {
	Name      *string    `json:"name,omitempty"`
	Slug      *string    `json:"slug,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type UpdateWorkspaceSettingInput struct {
	Settings  types.JSON `json:"settings,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type UserFilter struct {
	Email         *StringComparator `json:"email,omitempty"`
	DisplayName   *StringComparator `json:"displayName,omitempty"`
	CreatedAt     *TimeComparator   `json:"createdAt,omitempty"`
	UpdatedAt     *TimeComparator   `json:"updatedAt,omitempty"`
	APITokens     *APITokenFilter   `json:"apiTokens,omitempty"`
	Activities    *ActivityFilter   `json:"activities,omitempty"`
	Attachments   *AttachmentFilter `json:"attachments,omitempty"`
	Comments      *CommentFilter    `json:"comments,omitempty"`
	Invitations   *InvitationFilter `json:"invitations,omitempty"`
	ReporterTasks *TaskFilter       `json:"reporterTasks,omitempty"`
	TaskAssignees *TaskFilter       `json:"taskAssignees,omitempty"`
	TaskWatchers  *TaskFilter       `json:"taskWatchers,omitempty"`
	Teams         *TeamFilter       `json:"teams,omitempty"`
	TimeEntries   *TimeEntryFilter  `json:"timeEntries,omitempty"`
	Workspaces    *WorkspaceFilter  `json:"workspaces,omitempty"`
	And           []*UserFilter     `json:"and,omitempty"`
	Or            []*UserFilter     `json:"or,omitempty"`
}

type UserSort struct {
	Field     UserSortField `json:"field"`
	Direction SortDirection `json:"direction"`
}

type WorkspaceFilter struct {
	Name           *StringComparator    `json:"name,omitempty"`
	Slug           *StringComparator    `json:"slug,omitempty"`
	CreatedAt      *TimeComparator      `json:"createdAt,omitempty"`
	UpdatedAt      *TimeComparator      `json:"updatedAt,omitempty"`
	APITokens      *APITokenFilter      `json:"apiTokens,omitempty"`
	Activities     *ActivityFilter      `json:"activities,omitempty"`
	Attachments    *AttachmentFilter    `json:"attachments,omitempty"`
	Comments       *CommentFilter       `json:"comments,omitempty"`
	Cycles         *CycleFilter         `json:"cycles,omitempty"`
	Invitations    *InvitationFilter    `json:"invitations,omitempty"`
	Labels         *LabelFilter         `json:"labels,omitempty"`
	Projects       *ProjectFilter       `json:"projects,omitempty"`
	SsoConnections *SsoConnectionFilter `json:"ssoConnections,omitempty"`
	Tasks          *TaskFilter          `json:"tasks,omitempty"`
	Teams          *TeamFilter          `json:"teams,omitempty"`
	TimeEntries    *TimeEntryFilter     `json:"timeEntries,omitempty"`
	Users          *UserFilter          `json:"users,omitempty"`
	And            []*WorkspaceFilter   `json:"and,omitempty"`
	Or             []*WorkspaceFilter   `json:"or,omitempty"`
}

type WorkspaceSettingFilter struct {
	WorkspaceID *IDComparator             `json:"workspaceID,omitempty"`
	Settings    *JSONBComparator          `json:"settings,omitempty"`
	CreatedAt   *TimeComparator           `json:"createdAt,omitempty"`
	UpdatedAt   *TimeComparator           `json:"updatedAt,omitempty"`
	And         []*WorkspaceSettingFilter `json:"and,omitempty"`
	Or          []*WorkspaceSettingFilter `json:"or,omitempty"`
}

type WorkspaceSettingSort struct {
	Field     WorkspaceSettingSortField `json:"field"`
	Direction SortDirection             `json:"direction"`
}

type WorkspaceSort struct {
	Field     WorkspaceSortField `json:"field"`
	Direction SortDirection      `json:"direction"`
}

type APITokenSortField string

const (
	APITokenSortFieldID          APITokenSortField = "ID"
	APITokenSortFieldWorkspaceID APITokenSortField = "WORKSPACE_ID"
	APITokenSortFieldUserID      APITokenSortField = "USER_ID"
	APITokenSortFieldName        APITokenSortField = "NAME"
	APITokenSortFieldScopes      APITokenSortField = "SCOPES"
	APITokenSortFieldLastUsedAt  APITokenSortField = "LAST_USED_AT"
	APITokenSortFieldExpiresAt   APITokenSortField = "EXPIRES_AT"
	APITokenSortFieldCreatedAt   APITokenSortField = "CREATED_AT"
)

var AllAPITokenSortField = []APITokenSortField{
	APITokenSortFieldID,
	APITokenSortFieldWorkspaceID,
	APITokenSortFieldUserID,
	APITokenSortFieldName,
	APITokenSortFieldScopes,
	APITokenSortFieldLastUsedAt,
	APITokenSortFieldExpiresAt,
	APITokenSortFieldCreatedAt,
}

func (e APITokenSortField) IsValid() bool {
	switch e {
	case APITokenSortFieldID, APITokenSortFieldWorkspaceID, APITokenSortFieldUserID, APITokenSortFieldName, APITokenSortFieldScopes, APITokenSortFieldLastUsedAt, APITokenSortFieldExpiresAt, APITokenSortFieldCreatedAt:
		return true
	}
	return false
}

func (e APITokenSortField) String() string {
	return string(e)
}

func (e *APITokenSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = APITokenSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid APITokenSortField", str)
	}
	return nil
}

func (e APITokenSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *APITokenSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e APITokenSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ActivitySortField string

const (
	ActivitySortFieldID          ActivitySortField = "ID"
	ActivitySortFieldWorkspaceID ActivitySortField = "WORKSPACE_ID"
	ActivitySortFieldActorID     ActivitySortField = "ACTOR_ID"
	ActivitySortFieldEntityTable ActivitySortField = "ENTITY_TABLE"
	ActivitySortFieldEntityID    ActivitySortField = "ENTITY_ID"
	ActivitySortFieldAction      ActivitySortField = "ACTION"
	ActivitySortFieldPayload     ActivitySortField = "PAYLOAD"
	ActivitySortFieldCreatedAt   ActivitySortField = "CREATED_AT"
)

var AllActivitySortField = []ActivitySortField{
	ActivitySortFieldID,
	ActivitySortFieldWorkspaceID,
	ActivitySortFieldActorID,
	ActivitySortFieldEntityTable,
	ActivitySortFieldEntityID,
	ActivitySortFieldAction,
	ActivitySortFieldPayload,
	ActivitySortFieldCreatedAt,
}

func (e ActivitySortField) IsValid() bool {
	switch e {
	case ActivitySortFieldID, ActivitySortFieldWorkspaceID, ActivitySortFieldActorID, ActivitySortFieldEntityTable, ActivitySortFieldEntityID, ActivitySortFieldAction, ActivitySortFieldPayload, ActivitySortFieldCreatedAt:
		return true
	}
	return false
}

func (e ActivitySortField) String() string {
	return string(e)
}

func (e *ActivitySortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivitySortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivitySortField", str)
	}
	return nil
}

func (e ActivitySortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivitySortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivitySortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AttachmentSortField string

const (
	AttachmentSortFieldID          AttachmentSortField = "ID"
	AttachmentSortFieldWorkspaceID AttachmentSortField = "WORKSPACE_ID"
	AttachmentSortFieldEntityType  AttachmentSortField = "ENTITY_TYPE"
	AttachmentSortFieldEntityID    AttachmentSortField = "ENTITY_ID"
	AttachmentSortFieldUploadedBy  AttachmentSortField = "UPLOADED_BY"
	AttachmentSortFieldFileName    AttachmentSortField = "FILE_NAME"
	AttachmentSortFieldContentType AttachmentSortField = "CONTENT_TYPE"
	AttachmentSortFieldSizeBytes   AttachmentSortField = "SIZE_BYTES"
	AttachmentSortFieldStorageURL  AttachmentSortField = "STORAGE_URL"
	AttachmentSortFieldCreatedAt   AttachmentSortField = "CREATED_AT"
)

var AllAttachmentSortField = []AttachmentSortField{
	AttachmentSortFieldID,
	AttachmentSortFieldWorkspaceID,
	AttachmentSortFieldEntityType,
	AttachmentSortFieldEntityID,
	AttachmentSortFieldUploadedBy,
	AttachmentSortFieldFileName,
	AttachmentSortFieldContentType,
	AttachmentSortFieldSizeBytes,
	AttachmentSortFieldStorageURL,
	AttachmentSortFieldCreatedAt,
}

func (e AttachmentSortField) IsValid() bool {
	switch e {
	case AttachmentSortFieldID, AttachmentSortFieldWorkspaceID, AttachmentSortFieldEntityType, AttachmentSortFieldEntityID, AttachmentSortFieldUploadedBy, AttachmentSortFieldFileName, AttachmentSortFieldContentType, AttachmentSortFieldSizeBytes, AttachmentSortFieldStorageURL, AttachmentSortFieldCreatedAt:
		return true
	}
	return false
}

func (e AttachmentSortField) String() string {
	return string(e)
}

func (e *AttachmentSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AttachmentSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AttachmentSortField", str)
	}
	return nil
}

func (e AttachmentSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AttachmentSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AttachmentSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentSortField string

const (
	CommentSortFieldID          CommentSortField = "ID"
	CommentSortFieldWorkspaceID CommentSortField = "WORKSPACE_ID"
	CommentSortFieldTaskID      CommentSortField = "TASK_ID"
	CommentSortFieldAuthorID    CommentSortField = "AUTHOR_ID"
	CommentSortFieldBody        CommentSortField = "BODY"
	CommentSortFieldCreatedAt   CommentSortField = "CREATED_AT"
	CommentSortFieldUpdatedAt   CommentSortField = "UPDATED_AT"
)

var AllCommentSortField = []CommentSortField{
	CommentSortFieldID,
	CommentSortFieldWorkspaceID,
	CommentSortFieldTaskID,
	CommentSortFieldAuthorID,
	CommentSortFieldBody,
	CommentSortFieldCreatedAt,
	CommentSortFieldUpdatedAt,
}

func (e CommentSortField) IsValid() bool {
	switch e {
	case CommentSortFieldID, CommentSortFieldWorkspaceID, CommentSortFieldTaskID, CommentSortFieldAuthorID, CommentSortFieldBody, CommentSortFieldCreatedAt, CommentSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e CommentSortField) String() string {
	return string(e)
}

func (e *CommentSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentSortField", str)
	}
	return nil
}

func (e CommentSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CycleSortField string

const (
	CycleSortFieldID          CycleSortField = "ID"
	CycleSortFieldWorkspaceID CycleSortField = "WORKSPACE_ID"
	CycleSortFieldTeamID      CycleSortField = "TEAM_ID"
	CycleSortFieldName        CycleSortField = "NAME"
	CycleSortFieldStatus      CycleSortField = "STATUS"
	CycleSortFieldStartsOn    CycleSortField = "STARTS_ON"
	CycleSortFieldEndsOn      CycleSortField = "ENDS_ON"
	CycleSortFieldCreatedAt   CycleSortField = "CREATED_AT"
	CycleSortFieldUpdatedAt   CycleSortField = "UPDATED_AT"
)

var AllCycleSortField = []CycleSortField{
	CycleSortFieldID,
	CycleSortFieldWorkspaceID,
	CycleSortFieldTeamID,
	CycleSortFieldName,
	CycleSortFieldStatus,
	CycleSortFieldStartsOn,
	CycleSortFieldEndsOn,
	CycleSortFieldCreatedAt,
	CycleSortFieldUpdatedAt,
}

func (e CycleSortField) IsValid() bool {
	switch e {
	case CycleSortFieldID, CycleSortFieldWorkspaceID, CycleSortFieldTeamID, CycleSortFieldName, CycleSortFieldStatus, CycleSortFieldStartsOn, CycleSortFieldEndsOn, CycleSortFieldCreatedAt, CycleSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e CycleSortField) String() string {
	return string(e)
}

func (e *CycleSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CycleSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CycleSortField", str)
	}
	return nil
}

func (e CycleSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CycleSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CycleSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvitationSortField string

const (
	InvitationSortFieldID          InvitationSortField = "ID"
	InvitationSortFieldWorkspaceID InvitationSortField = "WORKSPACE_ID"
	InvitationSortFieldEmail       InvitationSortField = "EMAIL"
	InvitationSortFieldRole        InvitationSortField = "ROLE"
	InvitationSortFieldToken       InvitationSortField = "TOKEN"
	InvitationSortFieldStatus      InvitationSortField = "STATUS"
	InvitationSortFieldInvitedBy   InvitationSortField = "INVITED_BY"
	InvitationSortFieldExpiresAt   InvitationSortField = "EXPIRES_AT"
	InvitationSortFieldCreatedAt   InvitationSortField = "CREATED_AT"
	InvitationSortFieldUpdatedAt   InvitationSortField = "UPDATED_AT"
)

var AllInvitationSortField = []InvitationSortField{
	InvitationSortFieldID,
	InvitationSortFieldWorkspaceID,
	InvitationSortFieldEmail,
	InvitationSortFieldRole,
	InvitationSortFieldToken,
	InvitationSortFieldStatus,
	InvitationSortFieldInvitedBy,
	InvitationSortFieldExpiresAt,
	InvitationSortFieldCreatedAt,
	InvitationSortFieldUpdatedAt,
}

func (e InvitationSortField) IsValid() bool {
	switch e {
	case InvitationSortFieldID, InvitationSortFieldWorkspaceID, InvitationSortFieldEmail, InvitationSortFieldRole, InvitationSortFieldToken, InvitationSortFieldStatus, InvitationSortFieldInvitedBy, InvitationSortFieldExpiresAt, InvitationSortFieldCreatedAt, InvitationSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e InvitationSortField) String() string {
	return string(e)
}

func (e *InvitationSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvitationSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvitationSortField", str)
	}
	return nil
}

func (e InvitationSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvitationSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvitationSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LabelSortField string

const (
	LabelSortFieldID          LabelSortField = "ID"
	LabelSortFieldWorkspaceID LabelSortField = "WORKSPACE_ID"
	LabelSortFieldName        LabelSortField = "NAME"
	LabelSortFieldColor       LabelSortField = "COLOR"
	LabelSortFieldCreatedAt   LabelSortField = "CREATED_AT"
)

var AllLabelSortField = []LabelSortField{
	LabelSortFieldID,
	LabelSortFieldWorkspaceID,
	LabelSortFieldName,
	LabelSortFieldColor,
	LabelSortFieldCreatedAt,
}

func (e LabelSortField) IsValid() bool {
	switch e {
	case LabelSortFieldID, LabelSortFieldWorkspaceID, LabelSortFieldName, LabelSortFieldColor, LabelSortFieldCreatedAt:
		return true
	}
	return false
}

func (e LabelSortField) String() string {
	return string(e)
}

func (e *LabelSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LabelSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LabelSortField", str)
	}
	return nil
}

func (e LabelSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LabelSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LabelSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MembershipSortField string

const (
	MembershipSortFieldWorkspaceID MembershipSortField = "WORKSPACE_ID"
	MembershipSortFieldUserID      MembershipSortField = "USER_ID"
	MembershipSortFieldRole        MembershipSortField = "ROLE"
	MembershipSortFieldCreatedAt   MembershipSortField = "CREATED_AT"
	MembershipSortFieldUpdatedAt   MembershipSortField = "UPDATED_AT"
)

var AllMembershipSortField = []MembershipSortField{
	MembershipSortFieldWorkspaceID,
	MembershipSortFieldUserID,
	MembershipSortFieldRole,
	MembershipSortFieldCreatedAt,
	MembershipSortFieldUpdatedAt,
}

func (e MembershipSortField) IsValid() bool {
	switch e {
	case MembershipSortFieldWorkspaceID, MembershipSortFieldUserID, MembershipSortFieldRole, MembershipSortFieldCreatedAt, MembershipSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e MembershipSortField) String() string {
	return string(e)
}

func (e *MembershipSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MembershipSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MembershipSortField", str)
	}
	return nil
}

func (e MembershipSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MembershipSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MembershipSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectSortField string

const (
	ProjectSortFieldID          ProjectSortField = "ID"
	ProjectSortFieldWorkspaceID ProjectSortField = "WORKSPACE_ID"
	ProjectSortFieldName        ProjectSortField = "NAME"
	ProjectSortFieldDescription ProjectSortField = "DESCRIPTION"
	ProjectSortFieldCreatedAt   ProjectSortField = "CREATED_AT"
	ProjectSortFieldUpdatedAt   ProjectSortField = "UPDATED_AT"
	ProjectSortFieldDeletedAt   ProjectSortField = "DELETED_AT"
	ProjectSortFieldTeamID      ProjectSortField = "TEAM_ID"
)

var AllProjectSortField = []ProjectSortField{
	ProjectSortFieldID,
	ProjectSortFieldWorkspaceID,
	ProjectSortFieldName,
	ProjectSortFieldDescription,
	ProjectSortFieldCreatedAt,
	ProjectSortFieldUpdatedAt,
	ProjectSortFieldDeletedAt,
	ProjectSortFieldTeamID,
}

func (e ProjectSortField) IsValid() bool {
	switch e {
	case ProjectSortFieldID, ProjectSortFieldWorkspaceID, ProjectSortFieldName, ProjectSortFieldDescription, ProjectSortFieldCreatedAt, ProjectSortFieldUpdatedAt, ProjectSortFieldDeletedAt, ProjectSortFieldTeamID:
		return true
	}
	return false
}

func (e ProjectSortField) String() string {
	return string(e)
}

func (e *ProjectSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectSortField", str)
	}
	return nil
}

func (e ProjectSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectStatSortField string

const (
	ProjectStatSortFieldProjectID   ProjectStatSortField = "PROJECT_ID"
	ProjectStatSortFieldWorkspaceID ProjectStatSortField = "WORKSPACE_ID"
	ProjectStatSortFieldTotalTasks  ProjectStatSortField = "TOTAL_TASKS"
	ProjectStatSortFieldDoneTasks   ProjectStatSortField = "DONE_TASKS"
	ProjectStatSortFieldOpenTasks   ProjectStatSortField = "OPEN_TASKS"
)

var AllProjectStatSortField = []ProjectStatSortField{
	ProjectStatSortFieldProjectID,
	ProjectStatSortFieldWorkspaceID,
	ProjectStatSortFieldTotalTasks,
	ProjectStatSortFieldDoneTasks,
	ProjectStatSortFieldOpenTasks,
}

func (e ProjectStatSortField) IsValid() bool {
	switch e {
	case ProjectStatSortFieldProjectID, ProjectStatSortFieldWorkspaceID, ProjectStatSortFieldTotalTasks, ProjectStatSortFieldDoneTasks, ProjectStatSortFieldOpenTasks:
		return true
	}
	return false
}

func (e ProjectStatSortField) String() string {
	return string(e)
}

func (e *ProjectStatSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectStatSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectStatSortField", str)
	}
	return nil
}

func (e ProjectStatSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectStatSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectStatSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SsoConnectionSortField string

const (
	SsoConnectionSortFieldID          SsoConnectionSortField = "ID"
	SsoConnectionSortFieldWorkspaceID SsoConnectionSortField = "WORKSPACE_ID"
	SsoConnectionSortFieldProvider    SsoConnectionSortField = "PROVIDER"
	SsoConnectionSortFieldConfig      SsoConnectionSortField = "CONFIG"
	SsoConnectionSortFieldEnabled     SsoConnectionSortField = "ENABLED"
	SsoConnectionSortFieldCreatedAt   SsoConnectionSortField = "CREATED_AT"
	SsoConnectionSortFieldUpdatedAt   SsoConnectionSortField = "UPDATED_AT"
)

var AllSsoConnectionSortField = []SsoConnectionSortField{
	SsoConnectionSortFieldID,
	SsoConnectionSortFieldWorkspaceID,
	SsoConnectionSortFieldProvider,
	SsoConnectionSortFieldConfig,
	SsoConnectionSortFieldEnabled,
	SsoConnectionSortFieldCreatedAt,
	SsoConnectionSortFieldUpdatedAt,
}

func (e SsoConnectionSortField) IsValid() bool {
	switch e {
	case SsoConnectionSortFieldID, SsoConnectionSortFieldWorkspaceID, SsoConnectionSortFieldProvider, SsoConnectionSortFieldConfig, SsoConnectionSortFieldEnabled, SsoConnectionSortFieldCreatedAt, SsoConnectionSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e SsoConnectionSortField) String() string {
	return string(e)
}

func (e *SsoConnectionSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SsoConnectionSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SsoConnectionSortField", str)
	}
	return nil
}

func (e SsoConnectionSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SsoConnectionSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SsoConnectionSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskAssigneeSortField string

const (
	TaskAssigneeSortFieldTaskID     TaskAssigneeSortField = "TASK_ID"
	TaskAssigneeSortFieldUserID     TaskAssigneeSortField = "USER_ID"
	TaskAssigneeSortFieldAssignedAt TaskAssigneeSortField = "ASSIGNED_AT"
)

var AllTaskAssigneeSortField = []TaskAssigneeSortField{
	TaskAssigneeSortFieldTaskID,
	TaskAssigneeSortFieldUserID,
	TaskAssigneeSortFieldAssignedAt,
}

func (e TaskAssigneeSortField) IsValid() bool {
	switch e {
	case TaskAssigneeSortFieldTaskID, TaskAssigneeSortFieldUserID, TaskAssigneeSortFieldAssignedAt:
		return true
	}
	return false
}

func (e TaskAssigneeSortField) String() string {
	return string(e)
}

func (e *TaskAssigneeSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskAssigneeSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskAssigneeSortField", str)
	}
	return nil
}

func (e TaskAssigneeSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskAssigneeSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskAssigneeSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskDependencySortField string

const (
	TaskDependencySortFieldTaskID          TaskDependencySortField = "TASK_ID"
	TaskDependencySortFieldDependsOnTaskID TaskDependencySortField = "DEPENDS_ON_TASK_ID"
	TaskDependencySortFieldType            TaskDependencySortField = "TYPE"
	TaskDependencySortFieldCreatedAt       TaskDependencySortField = "CREATED_AT"
)

var AllTaskDependencySortField = []TaskDependencySortField{
	TaskDependencySortFieldTaskID,
	TaskDependencySortFieldDependsOnTaskID,
	TaskDependencySortFieldType,
	TaskDependencySortFieldCreatedAt,
}

func (e TaskDependencySortField) IsValid() bool {
	switch e {
	case TaskDependencySortFieldTaskID, TaskDependencySortFieldDependsOnTaskID, TaskDependencySortFieldType, TaskDependencySortFieldCreatedAt:
		return true
	}
	return false
}

func (e TaskDependencySortField) String() string {
	return string(e)
}

func (e *TaskDependencySortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskDependencySortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskDependencySortField", str)
	}
	return nil
}

func (e TaskDependencySortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskDependencySortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskDependencySortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskLabelSortField string

const (
	TaskLabelSortFieldTaskID  TaskLabelSortField = "TASK_ID"
	TaskLabelSortFieldLabelID TaskLabelSortField = "LABEL_ID"
)

var AllTaskLabelSortField = []TaskLabelSortField{
	TaskLabelSortFieldTaskID,
	TaskLabelSortFieldLabelID,
}

func (e TaskLabelSortField) IsValid() bool {
	switch e {
	case TaskLabelSortFieldTaskID, TaskLabelSortFieldLabelID:
		return true
	}
	return false
}

func (e TaskLabelSortField) String() string {
	return string(e)
}

func (e *TaskLabelSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskLabelSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskLabelSortField", str)
	}
	return nil
}

func (e TaskLabelSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskLabelSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskLabelSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskSortField string

const (
	TaskSortFieldID           TaskSortField = "ID"
	TaskSortFieldWorkspaceID  TaskSortField = "WORKSPACE_ID"
	TaskSortFieldProjectID    TaskSortField = "PROJECT_ID"
	TaskSortFieldParentTaskID TaskSortField = "PARENT_TASK_ID"
	TaskSortFieldReporterID   TaskSortField = "REPORTER_ID"
	TaskSortFieldTitle        TaskSortField = "TITLE"
	TaskSortFieldDescription  TaskSortField = "DESCRIPTION"
	TaskSortFieldStatus       TaskSortField = "STATUS"
	TaskSortFieldPriority     TaskSortField = "PRIORITY"
	TaskSortFieldCustomFields TaskSortField = "CUSTOM_FIELDS"
	TaskSortFieldDueAt        TaskSortField = "DUE_AT"
	TaskSortFieldCreatedAt    TaskSortField = "CREATED_AT"
	TaskSortFieldUpdatedAt    TaskSortField = "UPDATED_AT"
	TaskSortFieldDeletedAt    TaskSortField = "DELETED_AT"
	TaskSortFieldCycleID      TaskSortField = "CYCLE_ID"
)

var AllTaskSortField = []TaskSortField{
	TaskSortFieldID,
	TaskSortFieldWorkspaceID,
	TaskSortFieldProjectID,
	TaskSortFieldParentTaskID,
	TaskSortFieldReporterID,
	TaskSortFieldTitle,
	TaskSortFieldDescription,
	TaskSortFieldStatus,
	TaskSortFieldPriority,
	TaskSortFieldCustomFields,
	TaskSortFieldDueAt,
	TaskSortFieldCreatedAt,
	TaskSortFieldUpdatedAt,
	TaskSortFieldDeletedAt,
	TaskSortFieldCycleID,
}

func (e TaskSortField) IsValid() bool {
	switch e {
	case TaskSortFieldID, TaskSortFieldWorkspaceID, TaskSortFieldProjectID, TaskSortFieldParentTaskID, TaskSortFieldReporterID, TaskSortFieldTitle, TaskSortFieldDescription, TaskSortFieldStatus, TaskSortFieldPriority, TaskSortFieldCustomFields, TaskSortFieldDueAt, TaskSortFieldCreatedAt, TaskSortFieldUpdatedAt, TaskSortFieldDeletedAt, TaskSortFieldCycleID:
		return true
	}
	return false
}

func (e TaskSortField) String() string {
	return string(e)
}

func (e *TaskSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskSortField", str)
	}
	return nil
}

func (e TaskSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskWatcherSortField string

const (
	TaskWatcherSortFieldTaskID    TaskWatcherSortField = "TASK_ID"
	TaskWatcherSortFieldUserID    TaskWatcherSortField = "USER_ID"
	TaskWatcherSortFieldCreatedAt TaskWatcherSortField = "CREATED_AT"
)

var AllTaskWatcherSortField = []TaskWatcherSortField{
	TaskWatcherSortFieldTaskID,
	TaskWatcherSortFieldUserID,
	TaskWatcherSortFieldCreatedAt,
}

func (e TaskWatcherSortField) IsValid() bool {
	switch e {
	case TaskWatcherSortFieldTaskID, TaskWatcherSortFieldUserID, TaskWatcherSortFieldCreatedAt:
		return true
	}
	return false
}

func (e TaskWatcherSortField) String() string {
	return string(e)
}

func (e *TaskWatcherSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskWatcherSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskWatcherSortField", str)
	}
	return nil
}

func (e TaskWatcherSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskWatcherSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskWatcherSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TeamMemberSortField string

const (
	TeamMemberSortFieldTeamID  TeamMemberSortField = "TEAM_ID"
	TeamMemberSortFieldUserID  TeamMemberSortField = "USER_ID"
	TeamMemberSortFieldAddedAt TeamMemberSortField = "ADDED_AT"
)

var AllTeamMemberSortField = []TeamMemberSortField{
	TeamMemberSortFieldTeamID,
	TeamMemberSortFieldUserID,
	TeamMemberSortFieldAddedAt,
}

func (e TeamMemberSortField) IsValid() bool {
	switch e {
	case TeamMemberSortFieldTeamID, TeamMemberSortFieldUserID, TeamMemberSortFieldAddedAt:
		return true
	}
	return false
}

func (e TeamMemberSortField) String() string {
	return string(e)
}

func (e *TeamMemberSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamMemberSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamMemberSortField", str)
	}
	return nil
}

func (e TeamMemberSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TeamMemberSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TeamMemberSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TeamSortField string

const (
	TeamSortFieldID          TeamSortField = "ID"
	TeamSortFieldWorkspaceID TeamSortField = "WORKSPACE_ID"
	TeamSortFieldName        TeamSortField = "NAME"
	TeamSortFieldSlug        TeamSortField = "SLUG"
	TeamSortFieldDescription TeamSortField = "DESCRIPTION"
	TeamSortFieldCreatedAt   TeamSortField = "CREATED_AT"
	TeamSortFieldUpdatedAt   TeamSortField = "UPDATED_AT"
)

var AllTeamSortField = []TeamSortField{
	TeamSortFieldID,
	TeamSortFieldWorkspaceID,
	TeamSortFieldName,
	TeamSortFieldSlug,
	TeamSortFieldDescription,
	TeamSortFieldCreatedAt,
	TeamSortFieldUpdatedAt,
}

func (e TeamSortField) IsValid() bool {
	switch e {
	case TeamSortFieldID, TeamSortFieldWorkspaceID, TeamSortFieldName, TeamSortFieldSlug, TeamSortFieldDescription, TeamSortFieldCreatedAt, TeamSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e TeamSortField) String() string {
	return string(e)
}

func (e *TeamSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamSortField", str)
	}
	return nil
}

func (e TeamSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TeamSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TeamSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimeEntrySortField string

const (
	TimeEntrySortFieldID          TimeEntrySortField = "ID"
	TimeEntrySortFieldWorkspaceID TimeEntrySortField = "WORKSPACE_ID"
	TimeEntrySortFieldTaskID      TimeEntrySortField = "TASK_ID"
	TimeEntrySortFieldUserID      TimeEntrySortField = "USER_ID"
	TimeEntrySortFieldHours       TimeEntrySortField = "HOURS"
	TimeEntrySortFieldBillable    TimeEntrySortField = "BILLABLE"
	TimeEntrySortFieldNotes       TimeEntrySortField = "NOTES"
	TimeEntrySortFieldSpentOn     TimeEntrySortField = "SPENT_ON"
	TimeEntrySortFieldCreatedAt   TimeEntrySortField = "CREATED_AT"
)

var AllTimeEntrySortField = []TimeEntrySortField{
	TimeEntrySortFieldID,
	TimeEntrySortFieldWorkspaceID,
	TimeEntrySortFieldTaskID,
	TimeEntrySortFieldUserID,
	TimeEntrySortFieldHours,
	TimeEntrySortFieldBillable,
	TimeEntrySortFieldNotes,
	TimeEntrySortFieldSpentOn,
	TimeEntrySortFieldCreatedAt,
}

func (e TimeEntrySortField) IsValid() bool {
	switch e {
	case TimeEntrySortFieldID, TimeEntrySortFieldWorkspaceID, TimeEntrySortFieldTaskID, TimeEntrySortFieldUserID, TimeEntrySortFieldHours, TimeEntrySortFieldBillable, TimeEntrySortFieldNotes, TimeEntrySortFieldSpentOn, TimeEntrySortFieldCreatedAt:
		return true
	}
	return false
}

func (e TimeEntrySortField) String() string {
	return string(e)
}

func (e *TimeEntrySortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimeEntrySortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimeEntrySortField", str)
	}
	return nil
}

func (e TimeEntrySortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimeEntrySortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimeEntrySortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserSortField string

const (
	UserSortFieldID          UserSortField = "ID"
	UserSortFieldEmail       UserSortField = "EMAIL"
	UserSortFieldDisplayName UserSortField = "DISPLAY_NAME"
	UserSortFieldCreatedAt   UserSortField = "CREATED_AT"
	UserSortFieldUpdatedAt   UserSortField = "UPDATED_AT"
)

var AllUserSortField = []UserSortField{
	UserSortFieldID,
	UserSortFieldEmail,
	UserSortFieldDisplayName,
	UserSortFieldCreatedAt,
	UserSortFieldUpdatedAt,
}

func (e UserSortField) IsValid() bool {
	switch e {
	case UserSortFieldID, UserSortFieldEmail, UserSortFieldDisplayName, UserSortFieldCreatedAt, UserSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e UserSortField) String() string {
	return string(e)
}

func (e *UserSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserSortField", str)
	}
	return nil
}

func (e UserSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceSettingSortField string

const (
	WorkspaceSettingSortFieldID          WorkspaceSettingSortField = "ID"
	WorkspaceSettingSortFieldWorkspaceID WorkspaceSettingSortField = "WORKSPACE_ID"
	WorkspaceSettingSortFieldSettings    WorkspaceSettingSortField = "SETTINGS"
	WorkspaceSettingSortFieldCreatedAt   WorkspaceSettingSortField = "CREATED_AT"
	WorkspaceSettingSortFieldUpdatedAt   WorkspaceSettingSortField = "UPDATED_AT"
)

var AllWorkspaceSettingSortField = []WorkspaceSettingSortField{
	WorkspaceSettingSortFieldID,
	WorkspaceSettingSortFieldWorkspaceID,
	WorkspaceSettingSortFieldSettings,
	WorkspaceSettingSortFieldCreatedAt,
	WorkspaceSettingSortFieldUpdatedAt,
}

func (e WorkspaceSettingSortField) IsValid() bool {
	switch e {
	case WorkspaceSettingSortFieldID, WorkspaceSettingSortFieldWorkspaceID, WorkspaceSettingSortFieldSettings, WorkspaceSettingSortFieldCreatedAt, WorkspaceSettingSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e WorkspaceSettingSortField) String() string {
	return string(e)
}

func (e *WorkspaceSettingSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceSettingSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceSettingSortField", str)
	}
	return nil
}

func (e WorkspaceSettingSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceSettingSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceSettingSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceSortField string

const (
	WorkspaceSortFieldID        WorkspaceSortField = "ID"
	WorkspaceSortFieldName      WorkspaceSortField = "NAME"
	WorkspaceSortFieldSlug      WorkspaceSortField = "SLUG"
	WorkspaceSortFieldCreatedAt WorkspaceSortField = "CREATED_AT"
	WorkspaceSortFieldUpdatedAt WorkspaceSortField = "UPDATED_AT"
)

var AllWorkspaceSortField = []WorkspaceSortField{
	WorkspaceSortFieldID,
	WorkspaceSortFieldName,
	WorkspaceSortFieldSlug,
	WorkspaceSortFieldCreatedAt,
	WorkspaceSortFieldUpdatedAt,
}

func (e WorkspaceSortField) IsValid() bool {
	switch e {
	case WorkspaceSortFieldID, WorkspaceSortFieldName, WorkspaceSortFieldSlug, WorkspaceSortFieldCreatedAt, WorkspaceSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e WorkspaceSortField) String() string {
	return string(e)
}

func (e *WorkspaceSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceSortField", str)
	}
	return nil
}

func (e WorkspaceSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
