package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// CreateActivity is the resolver for the createActivity field.
func (r *mutationResolver) CreateActivity(ctx context.Context, input gqlmodel.CreateActivityInput) (*database.Activity, error) {
	return r.M.CreateActivity(ctx, translateCreateActivityInput(input))
}

// CreateActivities is the resolver for the createActivities field.
func (r *mutationResolver) CreateActivities(ctx context.Context, inputs []*gqlmodel.CreateActivityInput) ([]*database.Activity, error) {
	xs := make([]*database.CreateActivityInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateActivityInput(*in))
	}
	return r.M.CreateActivities(ctx, xs)
}

// UpdateActivity is the resolver for the updateActivity field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateActivity(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateActivityInput) (*database.Activity, error) {
	setIn := translateUpdateActivityInput(input)
	hasSet := hasUpdateActivitySetFields(input)
	return r.M.UpdateActivity(ctx, id, setIn, hasSet)
}

// UpdateActivities is the resolver for the updateActivities field.
func (r *mutationResolver) UpdateActivities(ctx context.Context, filter gqlmodel.ActivityFilter, input gqlmodel.UpdateActivityInput) ([]*database.Activity, error) {
	return r.M.UpdateActivities(ctx, translateActivityFilter(&filter), translateUpdateActivityInput(input))
}

// UpsertActivity is the resolver for the upsertActivity field.
func (r *mutationResolver) UpsertActivity(ctx context.Context, input gqlmodel.CreateActivityInput) (*database.Activity, error) {
	return r.M.UpsertActivity(ctx, translateCreateActivityInput(input))
}

// DeleteActivity is the resolver for the deleteActivity field.
func (r *mutationResolver) DeleteActivity(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.DeleteActivity(ctx, id)
}

// Activity is the resolver for the activity field.
func (r *queryResolver) Activity(ctx context.Context, id uuid1.UUID) (*database.Activity, error) {
	return r.Q.Activity(ctx, id)
}

// Activities is the resolver for the activities field.
func (r *queryResolver) Activities(ctx context.Context, filter *gqlmodel.ActivityFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.Activity], error) {
	return r.Q.Activities(ctx, translateActivityFilter(filter), first, after, last, before)
}

// ActivityList is the resolver for the activityList field.
func (r *queryResolver) ActivityList(ctx context.Context, filter *gqlmodel.ActivityFilter, sort []*gqlmodel.ActivitySort, limit *int, offset *int) (*database.PaginateResult[database.Activity], error) {
	return r.Q.ActivityList(ctx, translateActivityFilter(filter), translateActivitySort(sort), limit, offset)
}
