package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// APIToken is the resolver for the apiToken field.
func (r *queryResolver) APIToken(ctx context.Context, id uuid1.UUID) (*database.APIToken, error) {
	return r.Q.APIToken(ctx, id)
}

// APITokens is the resolver for the apiTokens field.
func (r *queryResolver) APITokens(ctx context.Context, filter *gqlmodel.APITokenFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.APIToken], error) {
	return r.Q.APITokens(ctx, translateAPITokenFilter(filter), first, after, last, before)
}

// APITokenList is the resolver for the apiTokenList field.
func (r *queryResolver) APITokenList(ctx context.Context, filter *gqlmodel.APITokenFilter, sort []*gqlmodel.APITokenSort, limit *int, offset *int) (*database.PaginateResult[database.APIToken], error) {
	return r.Q.APITokenList(ctx, translateAPITokenFilter(filter), translateAPITokenSort(sort), limit, offset)
}
