package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/teandresmith/sqlgen-example/internal/auth"
	"github.com/teandresmith/sqlgen-example/internal/database"
	"github.com/teandresmith/sqlgen-example/internal/graph/model"
	"github.com/teandresmith/sqlgen/comparator"
)

// Register is the resolver for the register field. It hashes the password,
// creates the global (untenanted) User, and returns a signed JWT. created_at /
// updated_at / id are DB-defaulted, so only the credential fields are supplied.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	hash, err := r.Auth.HashPassword(input.Password)
	if err != nil {
		return nil, err
	}
	user, err := r.Client.Users().Create(ctx, &database.CreateUserInput{
		Email:        input.Email,
		DisplayName:  input.DisplayName,
		PasswordHash: hash,
	})
	if err != nil {
		return nil, err
	}
	return r.authPayload(user)
}

// Login is the resolver for the login field. It looks the User up by email and
// verifies the password against the stored hash; both an unknown email and a
// bad password surface as the same opaque error so callers cannot enumerate
// registered accounts.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	email := input.Email
	limit := 1
	users, err := r.Client.Users().GetMany(ctx, &database.GetUsersInput{
		Filter: &database.UserFilter{Email: &comparator.String{Eq: &email}},
		Limit:  &limit,
	})
	if err != nil {
		return nil, err
	}
	if len(users) == 0 {
		// Burn the same bcrypt time a real check would, so response timing
		// does not reveal whether the email is registered.
		r.Auth.EqualizeCompareCost(input.Password)
		return nil, auth.ErrInvalidCredentials
	}
	user := users[0]
	if err := r.Auth.CheckPassword(user.PasswordHash, input.Password); err != nil {
		return nil, err
	}
	return r.authPayload(user)
}

// Me is the resolver for the me field — an authenticated operation. It reads
// the User id the bearer-token middleware placed in the request context and
// rejects the request when none is present.
func (r *queryResolver) Me(ctx context.Context) (*database.User, error) {
	userID, ok := auth.UserID(ctx)
	if !ok {
		return nil, errors.New("unauthenticated: a valid bearer token is required")
	}
	return r.Client.Users().Get(ctx, userID)
}
