package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// UpdateComment is the resolver for the updateComment field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateComment(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateCommentInput) (*database.Comment, error) {
	setIn := translateUpdateCommentInput(input)
	hasSet := hasUpdateCommentSetFields(input)
	return r.M.UpdateComment(ctx, id, setIn, hasSet)
}

// UpdateComments is the resolver for the updateComments field.
func (r *mutationResolver) UpdateComments(ctx context.Context, filter gqlmodel.CommentFilter, input gqlmodel.UpdateCommentInput) ([]*database.Comment, error) {
	return r.M.UpdateComments(ctx, translateCommentFilter(&filter), translateUpdateCommentInput(input))
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.DeleteComment(ctx, id)
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id uuid1.UUID) (*database.Comment, error) {
	return r.Q.Comment(ctx, id)
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, filter *gqlmodel.CommentFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.Comment], error) {
	return r.Q.Comments(ctx, translateCommentFilter(filter), first, after, last, before)
}

// CommentList is the resolver for the commentList field.
func (r *queryResolver) CommentList(ctx context.Context, filter *gqlmodel.CommentFilter, sort []*gqlmodel.CommentSort, limit *int, offset *int) (*database.PaginateResult[database.Comment], error) {
	return r.Q.CommentList(ctx, translateCommentFilter(filter), translateCommentSort(sort), limit, offset)
}
