// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package graph

import (
	"time"

	"github.com/teandresmith/sqlgen/comparator"

	database "github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// Per-family comparator translators. These are shared across
// the whole project (one impl per family variant, regardless of how many
// tables reference it) and are dispatched into by the per-table filter
// translators in filter_translate_gen.go.
//
// Numeric variants are emitted per Go T parameter (e.g.
// translateNumericComparatorInt32, translateNumericComparatorFloat64). The
// gqlgen-generated NumericComparator carries float64-typed fields (the
// GraphQL `Float` scalar binds to Go `float64`); each variant casts to its
// underlying T so the resulting *comparator.Number[T] matches the model
// filter's column type exactly.
//
// Nullable variants take their own Nullable<X>Comparator input, not the base
// one — GraphQL input types are global, so `isNull` cannot be a conditional
// field on a shared input and nullability has to be a separate type.
// They therefore copy the operands themselves rather than
// delegating to the base translator: the two functions no longer accept the
// same Go type. The operand block is identical text either way because
// comparator.Nullable<X> embeds <X>, so Go promotes the field assignments.
// `isNull` lands in the wrapper's `Null *bool`, giving IS NULL / IS NOT NULL
// a reachable path from the API surface.
//
// The `Custom []sql.Condition` field every family carries is deliberately
// never populated here — it is a raw-SQL escape hatch, and exposing it over
// HTTP would be an injection surface.

// translateAttachmentEntityTypeComparator translates a GraphQL AttachmentEntityTypeComparator into a
// *comparator.Enum[database.AttachmentEntityType] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to database.AttachmentEntityType itself, so the values arrive as
// the model comparator's own type parameter.
func translateAttachmentEntityTypeComparator(in *gqlmodel.AttachmentEntityTypeComparator) *comparator.Enum[database.AttachmentEntityType] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[database.AttachmentEntityType]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]database.AttachmentEntityType(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]database.AttachmentEntityType(nil), in.Nin...)
	}
	return out
}

// translateBooleanComparator translates a GraphQL BooleanComparator into a
// *comparator.Bool for the model layer's filter struct.
func translateBooleanComparator(in *gqlmodel.BooleanComparator) *comparator.Bool {
	if in == nil {
		return nil
	}
	out := &comparator.Bool{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	return out
}

// translateCycleStatusComparator translates a GraphQL CycleStatusComparator into a
// *comparator.Enum[database.CycleStatus] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to database.CycleStatus itself, so the values arrive as
// the model comparator's own type parameter.
func translateCycleStatusComparator(in *gqlmodel.CycleStatusComparator) *comparator.Enum[database.CycleStatus] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[database.CycleStatus]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]database.CycleStatus(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]database.CycleStatus(nil), in.Nin...)
	}
	return out
}

// translateDecimalComparator translates a GraphQL DecimalComparator into a
// *comparator.String for the model layer's filter struct.
//
// Decimal columns filter through comparator.String on the canonical string
// form — decimal.Decimal does not satisfy comparator.Numeric — so
// each Decimal-typed operand is rendered with String(). The ordered
// operators stay numerically correct because the parameter is compared
// against a numeric column: the database coerces it, rather than collating
// it as text.
func translateDecimalComparator(in *gqlmodel.DecimalComparator) *comparator.String {
	if in == nil {
		return nil
	}
	out := &comparator.String{}
	if in.Eq != nil {
		v := in.Eq.String()
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq.String()
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt.String()
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte.String()
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt.String()
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte.String()
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]string, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]string, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.Nin = xs
	}
	return out
}

// translateDependencyTypeComparator translates a GraphQL DependencyTypeComparator into a
// *comparator.Enum[database.DependencyType] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to database.DependencyType itself, so the values arrive as
// the model comparator's own type parameter.
func translateDependencyTypeComparator(in *gqlmodel.DependencyTypeComparator) *comparator.Enum[database.DependencyType] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[database.DependencyType]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]database.DependencyType(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]database.DependencyType(nil), in.Nin...)
	}
	return out
}

// translateIDComparator translates a GraphQL IDComparator into a
// *comparator.ID for the model layer's filter struct.
func translateIDComparator(in *gqlmodel.IDComparator) *comparator.ID {
	if in == nil {
		return nil
	}
	out := &comparator.ID{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	return out
}

// translateInvitationStatusComparator translates a GraphQL InvitationStatusComparator into a
// *comparator.Enum[database.InvitationStatus] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to database.InvitationStatus itself, so the values arrive as
// the model comparator's own type parameter.
func translateInvitationStatusComparator(in *gqlmodel.InvitationStatusComparator) *comparator.Enum[database.InvitationStatus] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[database.InvitationStatus]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]database.InvitationStatus(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]database.InvitationStatus(nil), in.Nin...)
	}
	return out
}

// translateJSONBComparator translates a GraphQL JSONBComparator into a
// *comparator.JSONB for the model layer's filter struct.
//
// PostgreSQL-only, which needs no switch here:
// resolveSimpleComparator resolves a column to comparator.JSONB only under the
// postgres dialect, so nothing off it can reach this translator. The document
// operands are typed with the `JSON` scalar, as the JSON family's are.
func translateJSONBComparator(in *gqlmodel.JSONBComparator) *comparator.JSONB {
	if in == nil {
		return nil
	}
	out := &comparator.JSONB{}
	if in.HasKey != nil {
		out.HasKey = in.HasKey
	}
	if len(in.HasAnyKey) > 0 {
		out.HasAnyKey = append([]string(nil), in.HasAnyKey...)
	}
	if len(in.HasAllKeys) > 0 {
		out.HasAllKeys = append([]string(nil), in.HasAllKeys...)
	}
	if in.Contains != nil {
		v := any(string(in.Contains))
		out.Contains = &v
	}
	if in.ContainedBy != nil {
		v := any(string(in.ContainedBy))
		out.ContainedBy = &v
	}
	if in.PathExists != nil {
		out.PathExists = in.PathExists
	}
	return out
}

// translateMembershipRoleComparator translates a GraphQL MembershipRoleComparator into a
// *comparator.Enum[database.MembershipRole] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to database.MembershipRole itself, so the values arrive as
// the model comparator's own type parameter.
func translateMembershipRoleComparator(in *gqlmodel.MembershipRoleComparator) *comparator.Enum[database.MembershipRole] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[database.MembershipRole]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]database.MembershipRole(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]database.MembershipRole(nil), in.Nin...)
	}
	return out
}

// translateNullableIDComparator translates a GraphQL NullableIDComparator into a
// *comparator.NullableID for the model layer's filter struct.
func translateNullableIDComparator(in *gqlmodel.NullableIDComparator) *comparator.NullableID {
	if in == nil {
		return nil
	}
	out := &comparator.NullableID{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableStringComparator translates a GraphQL NullableStringComparator into a
// *comparator.NullableString for the model layer's filter struct.
func translateNullableStringComparator(in *gqlmodel.NullableStringComparator) *comparator.NullableString {
	if in == nil {
		return nil
	}
	out := &comparator.NullableString{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if in.Contains != nil {
		out.Contains = in.Contains
	}
	if in.StartsWith != nil {
		out.StartsWith = in.StartsWith
	}
	if in.EndsWith != nil {
		out.EndsWith = in.EndsWith
	}
	if in.Like != nil {
		out.Like = in.Like
	}
	if in.Nlike != nil {
		out.NLike = in.Nlike
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableTimeComparator translates a GraphQL NullableTimeComparator into a
// *comparator.NullableTime for the model layer's filter struct.
func translateNullableTimeComparator(in *gqlmodel.NullableTimeComparator) *comparator.NullableTime {
	if in == nil {
		return nil
	}
	out := &comparator.NullableTime{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		xs := make([]time.Time, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]time.Time, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[time.Time]{Start: in.Between.From, End: in.Between.To}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[time.Time]{Start: in.Nbetween.From, End: in.Nbetween.To}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNumericComparatorInt64 translates a GraphQL NumericComparator into a
// *comparator.Number[int64] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int64 so the
// result matches the model filter's column type exactly.
func translateNumericComparatorInt64(in *gqlmodel.NumericComparator) *comparator.Number[int64] {
	if in == nil {
		return nil
	}
	out := &comparator.Number[int64]{}
	if in.Eq != nil {
		v := int64(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int64(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int64(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int64(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int64(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int64(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int64, len(in.In))
		for i, v := range in.In {
			xs[i] = int64(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int64, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int64(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int64]{
			Start: int64(in.Between.From),
			End:   int64(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int64]{
			Start: int64(in.Nbetween.From),
			End:   int64(in.Nbetween.To),
		}
	}
	return out
}

// translateSsoProviderComparator translates a GraphQL SsoProviderComparator into a
// *comparator.Enum[database.SsoProvider] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to database.SsoProvider itself, so the values arrive as
// the model comparator's own type parameter.
func translateSsoProviderComparator(in *gqlmodel.SsoProviderComparator) *comparator.Enum[database.SsoProvider] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[database.SsoProvider]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]database.SsoProvider(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]database.SsoProvider(nil), in.Nin...)
	}
	return out
}

// translateStringComparator translates a GraphQL StringComparator into a
// *comparator.String for the model layer's filter struct.
func translateStringComparator(in *gqlmodel.StringComparator) *comparator.String {
	if in == nil {
		return nil
	}
	out := &comparator.String{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if in.Contains != nil {
		out.Contains = in.Contains
	}
	if in.StartsWith != nil {
		out.StartsWith = in.StartsWith
	}
	if in.EndsWith != nil {
		out.EndsWith = in.EndsWith
	}
	if in.Like != nil {
		out.Like = in.Like
	}
	if in.Nlike != nil {
		out.NLike = in.Nlike
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	return out
}

// translateStringSliceComparator translates a GraphQL StringSliceComparator into a
// *comparator.Slice[string] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// No conversion is needed: gqlgen's element type for
// `[String!]` is already string.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateStringSliceComparator(in *gqlmodel.StringSliceComparator) *comparator.Slice[string] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[string]{}
	if len(in.ContainsAny) > 0 {
		out.ContainsAny = append([]string(nil), in.ContainsAny...)
	}
	if len(in.ContainsAll) > 0 {
		out.ContainsAll = append([]string(nil), in.ContainsAll...)
	}
	if len(in.ContainedBy) > 0 {
		out.ContainedBy = append([]string(nil), in.ContainedBy...)
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateTaskPriorityComparator translates a GraphQL TaskPriorityComparator into a
// *comparator.Enum[database.TaskPriority] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to database.TaskPriority itself, so the values arrive as
// the model comparator's own type parameter.
func translateTaskPriorityComparator(in *gqlmodel.TaskPriorityComparator) *comparator.Enum[database.TaskPriority] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[database.TaskPriority]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]database.TaskPriority(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]database.TaskPriority(nil), in.Nin...)
	}
	return out
}

// translateTaskStatusComparator translates a GraphQL TaskStatusComparator into a
// *comparator.Enum[database.TaskStatus] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to database.TaskStatus itself, so the values arrive as
// the model comparator's own type parameter.
func translateTaskStatusComparator(in *gqlmodel.TaskStatusComparator) *comparator.Enum[database.TaskStatus] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[database.TaskStatus]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]database.TaskStatus(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]database.TaskStatus(nil), in.Nin...)
	}
	return out
}

// translateTimeComparator translates a GraphQL TimeComparator into a
// *comparator.Time for the model layer's filter struct.
func translateTimeComparator(in *gqlmodel.TimeComparator) *comparator.Time {
	if in == nil {
		return nil
	}
	out := &comparator.Time{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		xs := make([]time.Time, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]time.Time, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[time.Time]{Start: in.Between.From, End: in.Between.To}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[time.Time]{Start: in.Nbetween.From, End: in.Nbetween.To}
	}
	return out
}
