package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// CreateCycle is the resolver for the createCycle field.
func (r *mutationResolver) CreateCycle(ctx context.Context, input gqlmodel.CreateCycleInput) (*database.Cycle, error) {
	return r.M.CreateCycle(ctx, translateCreateCycleInput(input))
}

// CreateCycles is the resolver for the createCycles field.
func (r *mutationResolver) CreateCycles(ctx context.Context, inputs []*gqlmodel.CreateCycleInput) ([]*database.Cycle, error) {
	xs := make([]*database.CreateCycleInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateCycleInput(*in))
	}
	return r.M.CreateCycles(ctx, xs)
}

// UpdateCycle is the resolver for the updateCycle field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateCycle(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateCycleInput) (*database.Cycle, error) {
	setIn := translateUpdateCycleInput(input)
	hasSet := hasUpdateCycleSetFields(input)
	return r.M.UpdateCycle(ctx, id, setIn, hasSet)
}

// UpdateCycles is the resolver for the updateCycles field.
func (r *mutationResolver) UpdateCycles(ctx context.Context, filter gqlmodel.CycleFilter, input gqlmodel.UpdateCycleInput) ([]*database.Cycle, error) {
	return r.M.UpdateCycles(ctx, translateCycleFilter(&filter), translateUpdateCycleInput(input))
}

// UpsertCycle is the resolver for the upsertCycle field.
func (r *mutationResolver) UpsertCycle(ctx context.Context, input gqlmodel.CreateCycleInput) (*database.Cycle, error) {
	return r.M.UpsertCycle(ctx, translateCreateCycleInput(input))
}

// DeleteCycle is the resolver for the deleteCycle field.
func (r *mutationResolver) DeleteCycle(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.DeleteCycle(ctx, id)
}

// UpdateCycleWithRelated is the resolver for the updateCycleWithRelated field.
func (r *mutationResolver) UpdateCycleWithRelated(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateCycleWithRelatedInput) (*database.Cycle, error) {
	return r.M.UpdateCycleWithRelated(ctx, id, translateUpdateCycleWithRelatedInput(input))
}

// Cycle is the resolver for the cycle field.
func (r *queryResolver) Cycle(ctx context.Context, id uuid1.UUID) (*database.Cycle, error) {
	return r.Q.Cycle(ctx, id)
}

// Cycles is the resolver for the cycles field.
func (r *queryResolver) Cycles(ctx context.Context, filter *gqlmodel.CycleFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.Cycle], error) {
	return r.Q.Cycles(ctx, translateCycleFilter(filter), first, after, last, before)
}

// CycleList is the resolver for the cycleList field.
func (r *queryResolver) CycleList(ctx context.Context, filter *gqlmodel.CycleFilter, sort []*gqlmodel.CycleSort, limit *int, offset *int) (*database.PaginateResult[database.Cycle], error) {
	return r.Q.CycleList(ctx, translateCycleFilter(filter), translateCycleSort(sort), limit, offset)
}
