package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// DeleteInvitation is the resolver for the deleteInvitation field.
func (r *mutationResolver) DeleteInvitation(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.DeleteInvitation(ctx, id)
}

// Invitation is the resolver for the invitation field.
func (r *queryResolver) Invitation(ctx context.Context, id uuid1.UUID) (*database.Invitation, error) {
	return r.Q.Invitation(ctx, id)
}

// Invitations is the resolver for the invitations field.
func (r *queryResolver) Invitations(ctx context.Context, filter *gqlmodel.InvitationFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.Invitation], error) {
	return r.Q.Invitations(ctx, translateInvitationFilter(filter), first, after, last, before)
}

// InvitationList is the resolver for the invitationList field.
func (r *queryResolver) InvitationList(ctx context.Context, filter *gqlmodel.InvitationFilter, sort []*gqlmodel.InvitationSort, limit *int, offset *int) (*database.PaginateResult[database.Invitation], error) {
	return r.Q.InvitationList(ctx, translateInvitationFilter(filter), translateInvitationSort(sort), limit, offset)
}
