package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input gqlmodel.CreateLabelInput) (*database.Label, error) {
	return r.M.CreateLabel(ctx, translateCreateLabelInput(input))
}

// CreateLabels is the resolver for the createLabels field.
func (r *mutationResolver) CreateLabels(ctx context.Context, inputs []*gqlmodel.CreateLabelInput) ([]*database.Label, error) {
	xs := make([]*database.CreateLabelInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateLabelInput(*in))
	}
	return r.M.CreateLabels(ctx, xs)
}

// UpdateLabel is the resolver for the updateLabel field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateLabel(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateLabelInput) (*database.Label, error) {
	setIn := translateUpdateLabelInput(input)
	hasSet := hasUpdateLabelSetFields(input)
	return r.M.UpdateLabel(ctx, id, setIn, hasSet)
}

// UpdateLabels is the resolver for the updateLabels field.
func (r *mutationResolver) UpdateLabels(ctx context.Context, filter gqlmodel.LabelFilter, input gqlmodel.UpdateLabelInput) ([]*database.Label, error) {
	return r.M.UpdateLabels(ctx, translateLabelFilter(&filter), translateUpdateLabelInput(input))
}

// UpsertLabel is the resolver for the upsertLabel field.
func (r *mutationResolver) UpsertLabel(ctx context.Context, input gqlmodel.CreateLabelInput) (*database.Label, error) {
	return r.M.UpsertLabel(ctx, translateCreateLabelInput(input))
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.DeleteLabel(ctx, id)
}

// Label is the resolver for the label field.
func (r *queryResolver) Label(ctx context.Context, id uuid1.UUID) (*database.Label, error) {
	return r.Q.Label(ctx, id)
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context, filter *gqlmodel.LabelFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.Label], error) {
	return r.Q.Labels(ctx, translateLabelFilter(filter), first, after, last, before)
}

// LabelList is the resolver for the labelList field.
func (r *queryResolver) LabelList(ctx context.Context, filter *gqlmodel.LabelFilter, sort []*gqlmodel.LabelSort, limit *int, offset *int) (*database.PaginateResult[database.Label], error) {
	return r.Q.LabelList(ctx, translateLabelFilter(filter), translateLabelSort(sort), limit, offset)
}
