package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/teandresmith/sqlgen-example/internal/auth"
	"github.com/teandresmith/sqlgen-example/internal/authz"
	"github.com/teandresmith/sqlgen-example/internal/database"
	"github.com/teandresmith/sqlgen-example/internal/graph/model"
	"github.com/teandresmith/sqlgen/comparator"
	"github.com/teandresmith/sqlgen/omittable"
)

// InviteToWorkspace is the resolver for the inviteToWorkspace field. It creates
// a pending Invitation in the caller's Active Workspace (PRD story 5).
//
// workspace_id is auto-injected from the Active Workspace by sqlgen's tenant
// scoping, and status/created_at/updated_at fall to their DB defaults (pending,
// now, now) — so the client controls only who is invited and to what Role. The
// server owns the token, issuer, and expiry. The create runs on the guarded
// `invitations` table, so the authz hook rejects a caller whose Active-Workspace
// Role is below owner/admin before the row is written.
func (r *mutationResolver) InviteToWorkspace(ctx context.Context, input model.InviteToWorkspaceInput) (*database.Invitation, error) {
	userID, ok := auth.UserID(ctx)
	if !ok {
		return nil, errors.New("unauthenticated: a valid bearer token is required to invite")
	}
	token, err := newInvitationToken()
	if err != nil {
		return nil, err
	}
	inv, err := r.Client.Invitations().Create(ctx, &database.CreateInvitationInput{
		Email:     input.Email,
		Role:      omittable.Set(input.Role),
		Token:     token,
		InvitedBy: userID,
		ExpiresAt: time.Now().Add(invitationTTL),
	})
	if err != nil {
		return nil, fmt.Errorf("inviting to workspace: %w", err)
	}
	return inv, nil
}

// AcceptInvitation is the resolver for the acceptInvitation field. It turns a
// pending Invitation into the caller's Membership and marks the Invitation
// `accepted`, atomically (PRD story 6).
//
// The acceptor is authenticated but is not yet a Member, so no Active Workspace
// rode in on the request — the token, which only the invited party holds, is the
// authorization. The invitation lookup (by token, across Workspaces) bypasses
// tenancy. The two writes instead name their tenant explicitly via
// CallOptions.Tenant (inv.WorkspaceID — where both rows belong), so they are
// tenant-scoped (filter + auto-set) and their cache entries invalidate under the
// right per-tenant key. A trusted system grant on the transaction context lets
// the authz hook pass the guarded-table writes through in place of the
// Active-Workspace manager Role the acceptor doesn't have; only server code can
// set it, so it is as unforgeable as SkipTenancy. The two writes run in one
// transaction so a failure to record acceptance rolls back the Membership rather
// than leaving a consumed invitation with no membership (or vice versa).
func (r *mutationResolver) AcceptInvitation(ctx context.Context, token string) (*database.Membership, error) {
	userID, ok := auth.UserID(ctx)
	if !ok {
		return nil, errors.New("unauthenticated: a valid bearer token is required to accept an invitation")
	}

	skipInvitationTenancy := func(o *database.CallOptions[database.InvitationFieldOptions]) { o.SkipTenancy = true }
	limit := 1
	invs, err := r.Client.Invitations().GetMany(ctx, &database.GetInvitationsInput{
		Filter: &database.InvitationFilter{Token: &comparator.String{Eq: &token}},
		Limit:  &limit,
	}, skipInvitationTenancy)
	if err != nil {
		return nil, err
	}
	if len(invs) == 0 {
		return nil, errors.New("invitation not found")
	}
	inv := invs[0]

	if inv.Status != database.InvitationStatusPending {
		return nil, fmt.Errorf("invitation is no longer acceptable (status %q)", inv.Status)
	}
	if time.Now().After(inv.ExpiresAt) {
		return nil, errors.New("invitation has expired")
	}

	// Only the invited email may accept — bind the offer to its addressee so a
	// leaked token can't be redeemed by an unrelated account.
	user, err := r.Client.Users().Get(ctx, userID)
	if err != nil {
		return nil, err
	}
	if !strings.EqualFold(user.Email, inv.Email) {
		return nil, errors.New("invitation is addressed to a different email")
	}

	// The acceptor is authorized by the invitation token (verified above), not by
	// an existing Membership, so mark the transaction a trusted system grant: it
	// lets the authz hook pass these guarded-table writes through without the
	// Active-Workspace manager Role the acceptor doesn't have. Only server code
	// can set it, so it is as unforgeable as SkipTenancy.
	txCtx := authz.WithSystemGrant(ctx)

	// Both rows belong to inv.WorkspaceID. Name that tenant explicitly per write
	// (CallOptions.Tenant) rather than resolving it from context: the acceptor is
	// not a Member, so no Active Workspace was validated onto the request. This
	// scopes the writes to inv.WorkspaceID (filter + auto-set) and, crucially,
	// gives the cache hook the tenant it needs to invalidate the Invitation entry
	// cached when it was sent — under the same per-tenant key.
	ws := inv.WorkspaceID
	explicitMembershipTenant := func(o *database.CallOptions[database.MembershipFieldOptions]) { o.Tenant = &ws }
	explicitInvitationTenant := func(o *database.CallOptions[database.InvitationFieldOptions]) { o.Tenant = &ws }

	var membership *database.Membership
	err = r.Client.WithTx(txCtx, "accept_invitation", func(ctx context.Context) error {
		var err error
		membership, err = r.Client.Memberships().Create(ctx, &database.CreateMembershipInput{
			WorkspaceID: inv.WorkspaceID,
			UserID:      userID,
			Role:        omittable.Set(inv.Role),
		}, explicitMembershipTenant)
		if err != nil {
			return err
		}
		_, err = r.Client.Invitations().Update(ctx, inv.ID, &database.UpdateInvitationInput{
			Status: omittable.Set(database.InvitationStatusAccepted),
		}, explicitInvitationTenant)
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("accepting invitation: %w", err)
	}
	return membership, nil
}

// RevokeInvitation is the resolver for the revokeInvitation field. It flips a
// pending Invitation to `revoked` so it can no longer be accepted (PRD story 7).
//
// Both the read and the write are tenant-scoped, so an Invitation in another
// Workspace is invisible here (a cross-tenant revoke returns "not found"), and
// the update on the guarded `invitations` table makes the authz hook require an
// owner/admin Role. Only a pending Invitation may be revoked — revoking an
// already-accepted one would not un-make the Membership, so it is refused.
func (r *mutationResolver) RevokeInvitation(ctx context.Context, id uuid.UUID) (*database.Invitation, error) {
	inv, err := r.Client.Invitations().Get(ctx, id)
	if errors.Is(err, database.ErrNotFound) {
		return nil, errors.New("invitation not found")
	}
	if err != nil {
		return nil, err
	}
	if inv.Status != database.InvitationStatusPending {
		return nil, fmt.Errorf("only a pending invitation can be revoked (status %q)", inv.Status)
	}
	revoked, err := r.Client.Invitations().Update(ctx, id, &database.UpdateInvitationInput{
		Status: omittable.Set(database.InvitationStatusRevoked),
	})
	if err != nil {
		return nil, fmt.Errorf("revoking invitation: %w", err)
	}
	return revoked, nil
}
