package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input gqlmodel.CreateProjectInput) (*database.Project, error) {
	return r.M.CreateProject(ctx, translateCreateProjectInput(input))
}

// CreateProjects is the resolver for the createProjects field.
func (r *mutationResolver) CreateProjects(ctx context.Context, inputs []*gqlmodel.CreateProjectInput) ([]*database.Project, error) {
	xs := make([]*database.CreateProjectInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateProjectInput(*in))
	}
	return r.M.CreateProjects(ctx, xs)
}

// UpdateProject is the resolver for the updateProject field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateProject(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateProjectInput) (*database.Project, error) {
	setIn := translateUpdateProjectInput(input)
	hasSet := hasUpdateProjectSetFields(input)
	return r.M.UpdateProject(ctx, id, setIn, hasSet)
}

// UpdateProjects is the resolver for the updateProjects field.
func (r *mutationResolver) UpdateProjects(ctx context.Context, filter gqlmodel.ProjectFilter, input gqlmodel.UpdateProjectInput) ([]*database.Project, error) {
	return r.M.UpdateProjects(ctx, translateProjectFilter(&filter), translateUpdateProjectInput(input))
}

// UpsertProject is the resolver for the upsertProject field.
func (r *mutationResolver) UpsertProject(ctx context.Context, input gqlmodel.CreateProjectInput) (*database.Project, error) {
	return r.M.UpsertProject(ctx, translateCreateProjectInput(input))
}

// HardDeleteProject is the resolver for the hardDeleteProject field.
func (r *mutationResolver) HardDeleteProject(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.HardDeleteProject(ctx, id)
}

// SoftDeleteProject is the resolver for the softDeleteProject field.
func (r *mutationResolver) SoftDeleteProject(ctx context.Context, id uuid1.UUID) (*database.Project, error) {
	return r.M.SoftDeleteProject(ctx, id)
}

// RestoreProject is the resolver for the restoreProject field.
func (r *mutationResolver) RestoreProject(ctx context.Context, id uuid1.UUID) (*database.Project, error) {
	return r.M.RestoreProject(ctx, id)
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id uuid1.UUID) (*database.Project, error) {
	return r.Q.Project(ctx, id)
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, filter *gqlmodel.ProjectFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.Project], error) {
	return r.Q.Projects(ctx, translateProjectFilter(filter), first, after, last, before)
}

// ProjectList is the resolver for the projectList field.
func (r *queryResolver) ProjectList(ctx context.Context, filter *gqlmodel.ProjectFilter, sort []*gqlmodel.ProjectSort, limit *int, offset *int) (*database.PaginateResult[database.Project], error) {
	return r.Q.ProjectList(ctx, translateProjectFilter(filter), translateProjectSort(sort), limit, offset)
}
