package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// ProjectStat is the resolver for the projectStat field.
func (r *queryResolver) ProjectStat(ctx context.Context, projectID uuid1.UUID) (*database.ProjectStat, error) {
	return r.Q.ProjectStat(ctx, projectID)
}

// ProjectStats is the resolver for the projectStats field.
func (r *queryResolver) ProjectStats(ctx context.Context, filter *gqlmodel.ProjectStatFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.ProjectStat], error) {
	return r.Q.ProjectStats(ctx, translateProjectStatFilter(filter), first, after, last, before)
}

// ProjectStatList is the resolver for the projectStatList field.
func (r *queryResolver) ProjectStatList(ctx context.Context, filter *gqlmodel.ProjectStatFilter, sort []*gqlmodel.ProjectStatSort, limit *int, offset *int) (*database.PaginateResult[database.ProjectStat], error) {
	return r.Q.ProjectStatList(ctx, translateProjectStatFilter(filter), translateProjectStatSort(sort), limit, offset)
}
