// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package graph

import (
	"fmt"
	"io"
	"strconv"
	"uuid"

	"github.com/99designs/gqlgen/graphql"
	"github.com/shopspring/decimal"
)

// MarshalDecimal marshals a decimal.Decimal into a JSON-quoted string for GraphQL.
func MarshalDecimal(v decimal.Decimal) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		_, _ = io.WriteString(w, strconv.Quote(v.String()))
	})
}

// UnmarshalDecimal parses a decimal.Decimal from a GraphQL input value.
func UnmarshalDecimal(v any) (decimal.Decimal, error) {
	s, ok := v.(string)
	if !ok {
		return decimal.Decimal{}, fmt.Errorf("Decimal must be a string, got %T", v)
	}
	return decimal.NewFromString(s)
}

// MarshalUUID marshals a uuid.UUID into a JSON-quoted string for GraphQL.
//
// Unlike gqlgen's bundled MarshalUUID (which silently emits `null` when the
// value equals uuid.Nil), this marshaler writes the underlying string
// unconditionally — a non-null field holding the Go zero value is a model-
// layer bug, and silently emitting null would mask it. Consumers that need
// null semantics should use the paired NullUUID scalar.
func MarshalUUID(v uuid.UUID) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		_, _ = io.WriteString(w, strconv.Quote(v.String()))
	})
}

// UnmarshalUUID parses a uuid.UUID from a GraphQL input value.
func UnmarshalUUID(v any) (uuid.UUID, error) {
	s, ok := v.(string)
	if !ok {
		return uuid.UUID{}, fmt.Errorf("UUID must be a string, got %T", v)
	}
	return uuid.Parse(s)
}
