// Code generated by sqlgen 0.1.0. DO NOT EDIT.
package graph

import (
	"github.com/teandresmith/sqlgen/sql"

	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// Per-table GraphQL→sql.Sort translators. Each function maps
// the gqlgen-generated `[]*<Table>Sort` slice into the runtime's
// `[]sql.Sort` representation, looking up SQL column names through a
// generated <table>SortFieldToColumn switch.
//
// Direction translation is shared across all tables — `directionToSortDirection`
// maps the gqlgen `SortDirection` enum to `sql.SortDirection`. Switch cases
// compare on the raw enum string (DESC / ASC) rather than the gqlgen-generated
// Go const so the generator does not need to mirror gqlgen's PascalCase
// conventions for enum constants.

// directionToSortDirection maps the gqlgen-generated SortDirection enum to
// the runtime sql.SortDirection. ASC is the default for any unrecognised
// value so a missing direction (impossible with a non-null GraphQL field)
// still produces a usable sort.
func directionToSortDirection(d gqlmodel.SortDirection) sql.SortDirection {
	if string(d) == "DESC" {
		return sql.Desc
	}
	return sql.Asc
}

// translateAPITokenSort converts a gqlgen-generated
// []*APITokenSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateAPITokenSort(in []*gqlmodel.APITokenSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    apiTokenSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// apiTokenSortFieldToColumn resolves a gqlgen
// APITokenSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func apiTokenSortFieldToColumn(f gqlmodel.APITokenSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "USER_ID":
		return "user_id"
	case "NAME":
		return "name"
	case "SCOPES":
		return "scopes"
	case "LAST_USED_AT":
		return "last_used_at"
	case "EXPIRES_AT":
		return "expires_at"
	case "CREATED_AT":
		return "created_at"
	}
	return ""
}

// translateActivitySort converts a gqlgen-generated
// []*ActivitySort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateActivitySort(in []*gqlmodel.ActivitySort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    activitySortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// activitySortFieldToColumn resolves a gqlgen
// ActivitySortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func activitySortFieldToColumn(f gqlmodel.ActivitySortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "ACTOR_ID":
		return "actor_id"
	case "ENTITY_TABLE":
		return "entity_table"
	case "ENTITY_ID":
		return "entity_id"
	case "ACTION":
		return "action"
	case "PAYLOAD":
		return "payload"
	case "CREATED_AT":
		return "created_at"
	}
	return ""
}

// translateAttachmentSort converts a gqlgen-generated
// []*AttachmentSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateAttachmentSort(in []*gqlmodel.AttachmentSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    attachmentSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// attachmentSortFieldToColumn resolves a gqlgen
// AttachmentSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func attachmentSortFieldToColumn(f gqlmodel.AttachmentSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "ENTITY_TYPE":
		return "entity_type"
	case "ENTITY_ID":
		return "entity_id"
	case "UPLOADED_BY":
		return "uploaded_by"
	case "FILE_NAME":
		return "file_name"
	case "CONTENT_TYPE":
		return "content_type"
	case "SIZE_BYTES":
		return "size_bytes"
	case "STORAGE_URL":
		return "storage_url"
	case "CREATED_AT":
		return "created_at"
	}
	return ""
}

// translateCommentSort converts a gqlgen-generated
// []*CommentSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateCommentSort(in []*gqlmodel.CommentSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    commentSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// commentSortFieldToColumn resolves a gqlgen
// CommentSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func commentSortFieldToColumn(f gqlmodel.CommentSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "TASK_ID":
		return "task_id"
	case "AUTHOR_ID":
		return "author_id"
	case "BODY":
		return "body"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}

// translateCycleSort converts a gqlgen-generated
// []*CycleSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateCycleSort(in []*gqlmodel.CycleSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    cycleSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// cycleSortFieldToColumn resolves a gqlgen
// CycleSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func cycleSortFieldToColumn(f gqlmodel.CycleSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "TEAM_ID":
		return "team_id"
	case "NAME":
		return "name"
	case "STATUS":
		return "status"
	case "STARTS_ON":
		return "starts_on"
	case "ENDS_ON":
		return "ends_on"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}

// translateInvitationSort converts a gqlgen-generated
// []*InvitationSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateInvitationSort(in []*gqlmodel.InvitationSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    invitationSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// invitationSortFieldToColumn resolves a gqlgen
// InvitationSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func invitationSortFieldToColumn(f gqlmodel.InvitationSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "EMAIL":
		return "email"
	case "ROLE":
		return "role"
	case "TOKEN":
		return "token"
	case "STATUS":
		return "status"
	case "INVITED_BY":
		return "invited_by"
	case "EXPIRES_AT":
		return "expires_at"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}

// translateLabelSort converts a gqlgen-generated
// []*LabelSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateLabelSort(in []*gqlmodel.LabelSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    labelSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// labelSortFieldToColumn resolves a gqlgen
// LabelSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func labelSortFieldToColumn(f gqlmodel.LabelSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "NAME":
		return "name"
	case "COLOR":
		return "color"
	case "CREATED_AT":
		return "created_at"
	}
	return ""
}

// translateMembershipSort converts a gqlgen-generated
// []*MembershipSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateMembershipSort(in []*gqlmodel.MembershipSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    membershipSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// membershipSortFieldToColumn resolves a gqlgen
// MembershipSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func membershipSortFieldToColumn(f gqlmodel.MembershipSortField) string {
	switch string(f) {
	case "WORKSPACE_ID":
		return "workspace_id"
	case "USER_ID":
		return "user_id"
	case "ROLE":
		return "role"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}

// translateProjectSort converts a gqlgen-generated
// []*ProjectSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateProjectSort(in []*gqlmodel.ProjectSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    projectSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// projectSortFieldToColumn resolves a gqlgen
// ProjectSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func projectSortFieldToColumn(f gqlmodel.ProjectSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "NAME":
		return "name"
	case "DESCRIPTION":
		return "description"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	case "DELETED_AT":
		return "deleted_at"
	case "TEAM_ID":
		return "team_id"
	}
	return ""
}

// translateProjectStatSort converts a gqlgen-generated
// []*ProjectStatSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateProjectStatSort(in []*gqlmodel.ProjectStatSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    projectStatSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// projectStatSortFieldToColumn resolves a gqlgen
// ProjectStatSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func projectStatSortFieldToColumn(f gqlmodel.ProjectStatSortField) string {
	switch string(f) {
	case "PROJECT_ID":
		return "project_id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "TOTAL_TASKS":
		return "total_tasks"
	case "DONE_TASKS":
		return "done_tasks"
	case "OPEN_TASKS":
		return "open_tasks"
	}
	return ""
}

// translateSsoConnectionSort converts a gqlgen-generated
// []*SsoConnectionSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateSsoConnectionSort(in []*gqlmodel.SsoConnectionSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    ssoConnectionSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// ssoConnectionSortFieldToColumn resolves a gqlgen
// SsoConnectionSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func ssoConnectionSortFieldToColumn(f gqlmodel.SsoConnectionSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "PROVIDER":
		return "provider"
	case "CONFIG":
		return "config"
	case "ENABLED":
		return "enabled"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}

// translateTaskSort converts a gqlgen-generated
// []*TaskSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateTaskSort(in []*gqlmodel.TaskSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    taskSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// taskSortFieldToColumn resolves a gqlgen
// TaskSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func taskSortFieldToColumn(f gqlmodel.TaskSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "PROJECT_ID":
		return "project_id"
	case "PARENT_TASK_ID":
		return "parent_task_id"
	case "REPORTER_ID":
		return "reporter_id"
	case "TITLE":
		return "title"
	case "DESCRIPTION":
		return "description"
	case "STATUS":
		return "status"
	case "PRIORITY":
		return "priority"
	case "CUSTOM_FIELDS":
		return "custom_fields"
	case "DUE_AT":
		return "due_at"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	case "DELETED_AT":
		return "deleted_at"
	case "CYCLE_ID":
		return "cycle_id"
	}
	return ""
}

// translateTaskAssigneeSort converts a gqlgen-generated
// []*TaskAssigneeSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateTaskAssigneeSort(in []*gqlmodel.TaskAssigneeSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    taskAssigneeSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// taskAssigneeSortFieldToColumn resolves a gqlgen
// TaskAssigneeSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func taskAssigneeSortFieldToColumn(f gqlmodel.TaskAssigneeSortField) string {
	switch string(f) {
	case "TASK_ID":
		return "task_id"
	case "USER_ID":
		return "user_id"
	case "ASSIGNED_AT":
		return "assigned_at"
	}
	return ""
}

// translateTaskDependencySort converts a gqlgen-generated
// []*TaskDependencySort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateTaskDependencySort(in []*gqlmodel.TaskDependencySort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    taskDependencySortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// taskDependencySortFieldToColumn resolves a gqlgen
// TaskDependencySortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func taskDependencySortFieldToColumn(f gqlmodel.TaskDependencySortField) string {
	switch string(f) {
	case "TASK_ID":
		return "task_id"
	case "DEPENDS_ON_TASK_ID":
		return "depends_on_task_id"
	case "TYPE":
		return "type"
	case "CREATED_AT":
		return "created_at"
	}
	return ""
}

// translateTaskLabelSort converts a gqlgen-generated
// []*TaskLabelSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateTaskLabelSort(in []*gqlmodel.TaskLabelSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    taskLabelSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// taskLabelSortFieldToColumn resolves a gqlgen
// TaskLabelSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func taskLabelSortFieldToColumn(f gqlmodel.TaskLabelSortField) string {
	switch string(f) {
	case "TASK_ID":
		return "task_id"
	case "LABEL_ID":
		return "label_id"
	}
	return ""
}

// translateTaskWatcherSort converts a gqlgen-generated
// []*TaskWatcherSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateTaskWatcherSort(in []*gqlmodel.TaskWatcherSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    taskWatcherSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// taskWatcherSortFieldToColumn resolves a gqlgen
// TaskWatcherSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func taskWatcherSortFieldToColumn(f gqlmodel.TaskWatcherSortField) string {
	switch string(f) {
	case "TASK_ID":
		return "task_id"
	case "USER_ID":
		return "user_id"
	case "CREATED_AT":
		return "created_at"
	}
	return ""
}

// translateTeamSort converts a gqlgen-generated
// []*TeamSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateTeamSort(in []*gqlmodel.TeamSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    teamSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// teamSortFieldToColumn resolves a gqlgen
// TeamSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func teamSortFieldToColumn(f gqlmodel.TeamSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "NAME":
		return "name"
	case "SLUG":
		return "slug"
	case "DESCRIPTION":
		return "description"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}

// translateTeamMemberSort converts a gqlgen-generated
// []*TeamMemberSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateTeamMemberSort(in []*gqlmodel.TeamMemberSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    teamMemberSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// teamMemberSortFieldToColumn resolves a gqlgen
// TeamMemberSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func teamMemberSortFieldToColumn(f gqlmodel.TeamMemberSortField) string {
	switch string(f) {
	case "TEAM_ID":
		return "team_id"
	case "USER_ID":
		return "user_id"
	case "ADDED_AT":
		return "added_at"
	}
	return ""
}

// translateTimeEntrySort converts a gqlgen-generated
// []*TimeEntrySort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateTimeEntrySort(in []*gqlmodel.TimeEntrySort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    timeEntrySortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// timeEntrySortFieldToColumn resolves a gqlgen
// TimeEntrySortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func timeEntrySortFieldToColumn(f gqlmodel.TimeEntrySortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "TASK_ID":
		return "task_id"
	case "USER_ID":
		return "user_id"
	case "HOURS":
		return "hours"
	case "BILLABLE":
		return "billable"
	case "NOTES":
		return "notes"
	case "SPENT_ON":
		return "spent_on"
	case "CREATED_AT":
		return "created_at"
	}
	return ""
}

// translateUserSort converts a gqlgen-generated
// []*UserSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateUserSort(in []*gqlmodel.UserSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    userSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// userSortFieldToColumn resolves a gqlgen
// UserSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func userSortFieldToColumn(f gqlmodel.UserSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "EMAIL":
		return "email"
	case "DISPLAY_NAME":
		return "display_name"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}

// translateWorkspaceSort converts a gqlgen-generated
// []*WorkspaceSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateWorkspaceSort(in []*gqlmodel.WorkspaceSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    workspaceSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// workspaceSortFieldToColumn resolves a gqlgen
// WorkspaceSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func workspaceSortFieldToColumn(f gqlmodel.WorkspaceSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "NAME":
		return "name"
	case "SLUG":
		return "slug"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}

// translateWorkspaceSettingSort converts a gqlgen-generated
// []*WorkspaceSettingSort into a []sql.Sort. nil / empty input returns nil
// so the caller's "no sort" path is preserved.
func translateWorkspaceSettingSort(in []*gqlmodel.WorkspaceSettingSort) []sql.Sort {
	if len(in) == 0 {
		return nil
	}
	out := make([]sql.Sort, 0, len(in))
	for _, s := range in {
		if s == nil {
			continue
		}
		out = append(out, sql.Sort{
			Column:    workspaceSettingSortFieldToColumn(s.Field),
			Direction: directionToSortDirection(s.Direction),
		})
	}
	return out
}

// workspaceSettingSortFieldToColumn resolves a gqlgen
// WorkspaceSettingSortField value to the SQL column it sorts on. Returns an
// empty string for unrecognised values so the caller can decide whether to
// surface a validation error or silently drop the entry.
func workspaceSettingSortFieldToColumn(f gqlmodel.WorkspaceSettingSortField) string {
	switch string(f) {
	case "ID":
		return "id"
	case "WORKSPACE_ID":
		return "workspace_id"
	case "SETTINGS":
		return "settings"
	case "CREATED_AT":
		return "created_at"
	case "UPDATED_AT":
		return "updated_at"
	}
	return ""
}
