package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/teandresmith/sqlgen-example/internal/database"
	"github.com/teandresmith/sqlgen-example/internal/graph/model"
	"github.com/teandresmith/sqlgen/omittable"
)

// ConfigureSSOConnection is the resolver for the configureSSOConnection field. A
// Workspace owner/admin configures single sign-on for a provider (PRD story 12).
//
// A Workspace has at most one connection per provider (UNIQUE (workspace_id,
// provider)), so configuration is an upsert on that pair: the first call inserts,
// a later call for the same provider updates the stored config/enabled. The
// tenant (workspace_id) is auto-injected, and the write lands on sso_connections
// — an authz guarded table — so the hook rejects a caller below owner/admin
// before any row is written. Only the configuration is stored; the SAML/OIDC
// handshake is out of scope.
func (r *mutationResolver) ConfigureSSOConnection(ctx context.Context, input model.ConfigureSSOConnectionInput) (*database.SsoConnection, error) {
	in := &database.CreateSsoConnectionInput{
		Provider: input.Provider,
		Config:   omittable.Set(input.Config),
	}
	if input.Enabled != nil {
		in.Enabled = omittable.Set(*input.Enabled)
	}

	conn, err := r.Client.SsoConnections().Upsert(ctx, in, database.SsoConnectionConflictWorkspaceIDProvider)
	if err != nil {
		return nil, fmt.Errorf("configuring sso connection: %w", err)
	}
	return conn, nil
}
