package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// UpdateTaskAssignee is the resolver for the updateTaskAssignee field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateTaskAssignee(ctx context.Context, taskID uuid1.UUID, userID uuid1.UUID, input gqlmodel.UpdateTaskAssigneeInput) (*database.TaskAssignee, error) {
	setIn := translateUpdateTaskAssigneeInput(input)
	hasSet := hasUpdateTaskAssigneeSetFields(input)
	return r.M.UpdateTaskAssignee(ctx, taskID, userID, setIn, hasSet)
}

// UpdateTaskAssignees is the resolver for the updateTaskAssignees field.
func (r *mutationResolver) UpdateTaskAssignees(ctx context.Context, filter gqlmodel.TaskAssigneeFilter, input gqlmodel.UpdateTaskAssigneeInput) ([]*database.TaskAssignee, error) {
	return r.M.UpdateTaskAssignees(ctx, translateTaskAssigneeFilter(&filter), translateUpdateTaskAssigneeInput(input))
}

// DeleteTaskAssignee is the resolver for the deleteTaskAssignee field.
func (r *mutationResolver) DeleteTaskAssignee(ctx context.Context, taskID uuid1.UUID, userID uuid1.UUID) (bool, error) {
	return r.M.DeleteTaskAssignee(ctx, taskID, userID)
}

// TaskAssignee is the resolver for the taskAssignee field.
func (r *queryResolver) TaskAssignee(ctx context.Context, taskID uuid1.UUID, userID uuid1.UUID) (*database.TaskAssignee, error) {
	return r.Q.TaskAssignee(ctx, taskID, userID)
}

// TaskAssignees is the resolver for the taskAssignees field.
func (r *queryResolver) TaskAssignees(ctx context.Context, filter *gqlmodel.TaskAssigneeFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.TaskAssignee], error) {
	return r.Q.TaskAssignees(ctx, translateTaskAssigneeFilter(filter), first, after, last, before)
}

// TaskAssigneeList is the resolver for the taskAssigneeList field.
func (r *queryResolver) TaskAssigneeList(ctx context.Context, filter *gqlmodel.TaskAssigneeFilter, sort []*gqlmodel.TaskAssigneeSort, limit *int, offset *int) (*database.PaginateResult[database.TaskAssignee], error) {
	return r.Q.TaskAssigneeList(ctx, translateTaskAssigneeFilter(filter), translateTaskAssigneeSort(sort), limit, offset)
}
