package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input gqlmodel.CreateTaskInput) (*database.Task, error) {
	return r.M.CreateTask(ctx, translateCreateTaskInput(input))
}

// CreateTasks is the resolver for the createTasks field.
func (r *mutationResolver) CreateTasks(ctx context.Context, inputs []*gqlmodel.CreateTaskInput) ([]*database.Task, error) {
	xs := make([]*database.CreateTaskInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateTaskInput(*in))
	}
	return r.M.CreateTasks(ctx, xs)
}

// UpdateTask is the resolver for the updateTask field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateTask(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateTaskInput) (*database.Task, error) {
	setIn := translateUpdateTaskInput(input)
	hasSet := hasUpdateTaskSetFields(input)
	return r.M.UpdateTask(ctx, id, setIn, hasSet)
}

// UpdateTasks is the resolver for the updateTasks field.
func (r *mutationResolver) UpdateTasks(ctx context.Context, filter gqlmodel.TaskFilter, input gqlmodel.UpdateTaskInput) ([]*database.Task, error) {
	return r.M.UpdateTasks(ctx, translateTaskFilter(&filter), translateUpdateTaskInput(input))
}

// UpsertTask is the resolver for the upsertTask field.
func (r *mutationResolver) UpsertTask(ctx context.Context, input gqlmodel.CreateTaskInput) (*database.Task, error) {
	return r.M.UpsertTask(ctx, translateCreateTaskInput(input))
}

// HardDeleteTask is the resolver for the hardDeleteTask field.
func (r *mutationResolver) HardDeleteTask(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.HardDeleteTask(ctx, id)
}

// SoftDeleteTask is the resolver for the softDeleteTask field.
func (r *mutationResolver) SoftDeleteTask(ctx context.Context, id uuid1.UUID) (*database.Task, error) {
	return r.M.SoftDeleteTask(ctx, id)
}

// RestoreTask is the resolver for the restoreTask field.
func (r *mutationResolver) RestoreTask(ctx context.Context, id uuid1.UUID) (*database.Task, error) {
	return r.M.RestoreTask(ctx, id)
}

// UpdateTaskWithRelated is the resolver for the updateTaskWithRelated field.
func (r *mutationResolver) UpdateTaskWithRelated(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateTaskWithRelatedInput) (*database.Task, error) {
	return r.M.UpdateTaskWithRelated(ctx, id, translateUpdateTaskWithRelatedInput(input))
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id uuid1.UUID) (*database.Task, error) {
	return r.Q.Task(ctx, id)
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, filter *gqlmodel.TaskFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.Task], error) {
	return r.Q.Tasks(ctx, translateTaskFilter(filter), first, after, last, before)
}

// TaskList is the resolver for the taskList field.
func (r *queryResolver) TaskList(ctx context.Context, filter *gqlmodel.TaskFilter, sort []*gqlmodel.TaskSort, limit *int, offset *int) (*database.PaginateResult[database.Task], error) {
	return r.Q.TaskList(ctx, translateTaskFilter(filter), translateTaskSort(sort), limit, offset)
}
