package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// UpdateTaskWatcher is the resolver for the updateTaskWatcher field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateTaskWatcher(ctx context.Context, taskID uuid1.UUID, userID uuid1.UUID, input gqlmodel.UpdateTaskWatcherInput) (*database.TaskWatcher, error) {
	setIn := translateUpdateTaskWatcherInput(input)
	hasSet := hasUpdateTaskWatcherSetFields(input)
	return r.M.UpdateTaskWatcher(ctx, taskID, userID, setIn, hasSet)
}

// UpdateTaskWatchers is the resolver for the updateTaskWatchers field.
func (r *mutationResolver) UpdateTaskWatchers(ctx context.Context, filter gqlmodel.TaskWatcherFilter, input gqlmodel.UpdateTaskWatcherInput) ([]*database.TaskWatcher, error) {
	return r.M.UpdateTaskWatchers(ctx, translateTaskWatcherFilter(&filter), translateUpdateTaskWatcherInput(input))
}

// DeleteTaskWatcher is the resolver for the deleteTaskWatcher field.
func (r *mutationResolver) DeleteTaskWatcher(ctx context.Context, taskID uuid1.UUID, userID uuid1.UUID) (bool, error) {
	return r.M.DeleteTaskWatcher(ctx, taskID, userID)
}

// TaskWatcher is the resolver for the taskWatcher field.
func (r *queryResolver) TaskWatcher(ctx context.Context, taskID uuid1.UUID, userID uuid1.UUID) (*database.TaskWatcher, error) {
	return r.Q.TaskWatcher(ctx, taskID, userID)
}

// TaskWatchers is the resolver for the taskWatchers field.
func (r *queryResolver) TaskWatchers(ctx context.Context, filter *gqlmodel.TaskWatcherFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.TaskWatcher], error) {
	return r.Q.TaskWatchers(ctx, translateTaskWatcherFilter(filter), first, after, last, before)
}

// TaskWatcherList is the resolver for the taskWatcherList field.
func (r *queryResolver) TaskWatcherList(ctx context.Context, filter *gqlmodel.TaskWatcherFilter, sort []*gqlmodel.TaskWatcherSort, limit *int, offset *int) (*database.PaginateResult[database.TaskWatcher], error) {
	return r.Q.TaskWatcherList(ctx, translateTaskWatcherFilter(filter), translateTaskWatcherSort(sort), limit, offset)
}
