package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"uuid"

	"github.com/teandresmith/sqlgen-example/internal/auth"
	"github.com/teandresmith/sqlgen-example/internal/database"
	"github.com/teandresmith/sqlgen-example/internal/graph/sqlgenresolver"
)

// AssignUserToTask assigns a User to a Task within the Active Workspace (story
// 25). The Task is resolved tenant-scoped so a Task in another Workspace is
// invisible ("not found"), and the User is resolved so a dangling assignee is
// rejected with a clear message before the FK check. assigned_at is left to its
// DB default (now()).
func (r *mutationResolver) AssignUserToTask(ctx context.Context, taskID uuid.UUID, userID uuid.UUID) (*database.TaskAssignee, error) {
	if _, err := r.Client.Tasks().Get(ctx, taskID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return nil, errors.New("task not found in the active workspace")
		}
		return nil, err
	}
	// Users are global (not tenant-scoped); resolve for a clean not-found error
	// instead of a raw foreign-key violation.
	if _, err := r.Client.Users().Get(ctx, userID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return nil, errors.New("user not found")
		}
		return nil, err
	}

	assignee, err := r.Client.TaskAssignees().Create(ctx, &database.CreateTaskAssigneeInput{
		TaskID: taskID,
		UserID: userID,
	}, func(o *database.CallOptions[database.TaskAssigneeFieldOptions]) {
		for _, apply := range sqlgenresolver.CallOptionsFromHTTP[database.TaskAssigneeFieldOptions](ctx) {
			apply(o)
		}
	})
	if err != nil {
		return nil, fmt.Errorf("assigning user to task: %w", err)
	}
	return assignee, nil
}

// WatchTask records the authenticated caller as a Watcher of a Task (story 26),
// so a member follows updates without being an Assignee. The watcher is never
// client-supplied — it is the bearer-token identity. created_at is left to its
// DB default (now()).
func (r *mutationResolver) WatchTask(ctx context.Context, taskID uuid.UUID) (*database.TaskWatcher, error) {
	userID, ok := auth.UserID(ctx)
	if !ok {
		return nil, errors.New("unauthenticated: a valid bearer token is required to watch a task")
	}
	if _, err := r.Client.Tasks().Get(ctx, taskID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return nil, errors.New("task not found in the active workspace")
		}
		return nil, err
	}

	watcher, err := r.Client.TaskWatchers().Create(ctx, &database.CreateTaskWatcherInput{
		TaskID: taskID,
		UserID: userID,
	}, func(o *database.CallOptions[database.TaskWatcherFieldOptions]) {
		for _, apply := range sqlgenresolver.CallOptionsFromHTTP[database.TaskWatcherFieldOptions](ctx) {
			apply(o)
		}
	})
	if err != nil {
		return nil, fmt.Errorf("watching task: %w", err)
	}
	return watcher, nil
}
