package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/shopspring/decimal"
	"github.com/teandresmith/sqlgen-example/internal/auth"
	"github.com/teandresmith/sqlgen-example/internal/database"
	"github.com/teandresmith/sqlgen-example/internal/graph/sqlgenresolver"
	"github.com/teandresmith/sqlgen/omittable"
)

// CommentOnTask is the resolver for the commentOnTask field. A member comments on
// a Task within the Active Workspace (PRD story 29).
//
// author_id is the bearer-token identity, never the input, so a client cannot
// falsify who wrote a comment. workspace_id is omitted and auto-injected from the
// Active Workspace by tenant scoping. The Task is resolved tenant-scoped first:
// comments.task_id has no Workspace constraint of its own, so without this a
// caller could comment on a Task in another Workspace (the row would land in the
// caller's tenant pointing at a foreign Task). Resolving it closes that hole with
// a clean "not found".
func (r *mutationResolver) CommentOnTask(ctx context.Context, taskID uuid.UUID, body string) (*database.Comment, error) {
	authorID, ok := auth.UserID(ctx)
	if !ok {
		return nil, errors.New("unauthenticated: a valid bearer token is required to comment on a task")
	}
	if _, err := r.Client.Tasks().Get(ctx, taskID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return nil, errors.New("task not found in the active workspace")
		}
		return nil, err
	}

	comment, err := r.Client.Comments().Create(ctx, &database.CreateCommentInput{
		TaskID:   taskID,
		AuthorID: authorID,
		Body:     body,
	}, func(o *database.CallOptions[database.CommentFieldOptions]) {
		for _, apply := range sqlgenresolver.CallOptionsFromHTTP[database.CommentFieldOptions](ctx) {
			apply(o)
		}
	})
	if err != nil {
		return nil, fmt.Errorf("commenting on task: %w", err)
	}
	return comment, nil
}

// AttachToTask is the resolver for the attachToTask field. A member attaches a
// file to a Task within the Active Workspace (PRD story 33).
//
// attachments is polymorphic: entity_id has no foreign key, so a raw create could
// point it at any UUID in any Workspace. This resolver resolves the Task
// tenant-scoped first (invisible → "not found"), then sets the discriminator and
// entity id itself, so the binding can never be forged. uploaded_by is the
// authenticated caller (server-owned), and workspace_id is auto-injected by
// tenant scoping.
func (r *mutationResolver) AttachToTask(ctx context.Context, taskID uuid.UUID, fileName string, contentType string, sizeBytes int, storageURL string) (*database.Attachment, error) {
	if _, err := r.Client.Tasks().Get(ctx, taskID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return nil, errors.New("task not found in the active workspace")
		}
		return nil, err
	}
	return r.createAttachment(ctx, database.AttachmentEntityTypeTask, taskID, fileName, contentType, sizeBytes, storageURL)
}

// AttachToComment is the resolver for the attachToComment field. A member
// attaches a file to a Comment within the Active Workspace (PRD story 33).
//
// The same polymorphic guard as AttachToTask applies: the Comment is resolved
// tenant-scoped first so a Comment in another Workspace is invisible, then the
// server sets entity_type = comment and entity_id itself.
func (r *mutationResolver) AttachToComment(ctx context.Context, commentID uuid.UUID, fileName string, contentType string, sizeBytes int, storageURL string) (*database.Attachment, error) {
	if _, err := r.Client.Comments().Get(ctx, commentID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return nil, errors.New("comment not found in the active workspace")
		}
		return nil, err
	}
	return r.createAttachment(ctx, database.AttachmentEntityTypeComment, commentID, fileName, contentType, sizeBytes, storageURL)
}

// LogTime is the resolver for the logTime field. A member logs a Time Entry
// against a Task in decimal hours (PRD story 34).
//
// user_id is the bearer-token identity, never the input, so effort is always
// attributed to the caller. workspace_id is auto-injected by tenant scoping, and
// the Task is resolved tenant-scoped first so time cannot be logged against a
// Task in another Workspace. billable defaults to true and notes is optional.
func (r *mutationResolver) LogTime(ctx context.Context, taskID uuid.UUID, hours decimal.Decimal, spentOn time.Time, billable *bool, notes *string) (*database.TimeEntry, error) {
	userID, ok := auth.UserID(ctx)
	if !ok {
		return nil, errors.New("unauthenticated: a valid bearer token is required to log time")
	}
	if _, err := r.Client.Tasks().Get(ctx, taskID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return nil, errors.New("task not found in the active workspace")
		}
		return nil, err
	}

	in := &database.CreateTimeEntryInput{
		TaskID:  taskID,
		UserID:  userID,
		Hours:   hours,
		SpentOn: spentOn,
	}
	if billable != nil {
		in.Billable = omittable.Set(*billable)
	}
	if notes != nil {
		in.Notes = omittable.Set(notes)
	}

	entry, err := r.Client.TimeEntries().Create(ctx, in, func(o *database.CallOptions[database.TimeEntryFieldOptions]) {
		for _, apply := range sqlgenresolver.CallOptionsFromHTTP[database.TimeEntryFieldOptions](ctx) {
			apply(o)
		}
	})
	if err != nil {
		return nil, fmt.Errorf("logging time: %w", err)
	}
	return entry, nil
}
