package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	"github.com/teandresmith/sqlgen-example/internal/graph/sqlgenresolver"
	"github.com/teandresmith/sqlgen/comparator"
)

// AddUserToTeam adds a User to a Team within the Active Workspace (story 17).
// team_members carries no workspace_id, so the Team is resolved through the
// tenant-scoped client first: a Team in another Workspace is invisible ("not
// found") and cross-tenant membership writes are refused before any row is
// written. A Team is "a group of Users within a Workspace" (CONTEXT.md), so the
// User must hold a Membership in the Active Workspace — checked via the
// tenant-scoped Memberships client, whose rows are already confined to the
// Active Workspace, so a global identity that belongs to no/another Workspace
// cannot be added and Team membership can't diverge from the Workspace roster.
// The write hits team_members, a guarded table, so the authz hook rejects a
// caller below owner/admin. added_at is left to its DB default (now()).
func (r *mutationResolver) AddUserToTeam(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) (*database.TeamMember, error) {
	if _, err := r.Client.Teams().Get(ctx, teamID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return nil, errors.New("team not found in the active workspace")
		}
		return nil, err
	}
	// The User must be a Member of the Active Workspace. Memberships is
	// tenant-scoped, so this filter only matches a Membership in the Active
	// Workspace — a User from another (or no) Workspace is rejected here rather
	// than silently joining a Team they do not belong to.
	userIDStr := userID.String()
	isMember, err := r.Client.Memberships().ExistsWhere(ctx, &database.MembershipFilter{
		UserID: &comparator.ID{Eq: &userIDStr},
	})
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, errors.New("user is not a member of the active workspace")
	}

	member, err := r.Client.TeamMembers().Create(ctx, &database.CreateTeamMemberInput{
		TeamID: teamID,
		UserID: userID,
	}, func(o *database.CallOptions[database.TeamMemberFieldOptions]) {
		for _, apply := range sqlgenresolver.CallOptionsFromHTTP[database.TeamMemberFieldOptions](ctx) {
			apply(o)
		}
	})
	if err != nil {
		return nil, fmt.Errorf("adding user to team: %w", err)
	}
	return member, nil
}

// RemoveUserFromTeam removes a User from a Team within the Active Workspace
// (story 17). The Team is resolved tenant-scoped first, closing the cross-tenant
// hole a raw team_members delete (a composite PK with no Workspace to scope)
// would otherwise leave open. The delete hits team_members, a guarded table, so
// the authz hook rejects a caller below owner/admin. Idempotent: removing a User
// who is not on the Team is not an error.
func (r *mutationResolver) RemoveUserFromTeam(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) (bool, error) {
	if _, err := r.Client.Teams().Get(ctx, teamID); err != nil {
		if errors.Is(err, database.ErrNotFound) {
			return false, errors.New("team not found in the active workspace")
		}
		return false, err
	}

	err := r.Client.TeamMembers().HardDelete(ctx, database.TeamMemberPK{
		TeamID: teamID,
		UserID: userID,
	}, func(o *database.CallOptions[database.TeamMemberFieldOptions]) {
		for _, apply := range sqlgenresolver.CallOptionsFromHTTP[database.TeamMemberFieldOptions](ctx) {
			apply(o)
		}
	})
	if err != nil {
		return false, fmt.Errorf("removing user from team: %w", err)
	}
	return true, nil
}
