package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"

	"github.com/teandresmith/sqlgen-example/internal/auth"
	"github.com/teandresmith/sqlgen-example/internal/database"
	"github.com/teandresmith/sqlgen-example/internal/graph/model"
	"github.com/teandresmith/sqlgen/omittable"
)

// BootstrapWorkspace is the resolver for the bootstrapWorkspace field. It
// founds a Workspace on behalf of the authenticated caller and records that
// caller as the Workspace's `owner`, atomically: both inserts run in one
// transaction, so a failure to record ownership rolls the Workspace back rather
// than leaving an unreachable, ownerless tenant.
//
// The Workspace is shared (untenanted), so its create needs no Active
// Workspace. The Membership insert bypasses tenancy (SkipTenancy): no Active
// Workspace is established for this request, and the workspace_id it writes is
// the row just created in the same transaction.
func (r *mutationResolver) BootstrapWorkspace(ctx context.Context, input model.BootstrapWorkspaceInput) (*database.Workspace, error) {
	userID, ok := auth.UserID(ctx)
	if !ok {
		return nil, errors.New("unauthenticated: a valid bearer token is required to create a workspace")
	}

	var workspace *database.Workspace
	err := r.Client.WithTx(ctx, "bootstrap_workspace", func(ctx context.Context) error {
		var err error
		workspace, err = r.Client.Workspaces().Create(ctx, &database.CreateWorkspaceInput{
			Name: input.Name,
			Slug: input.Slug,
		})
		if err != nil {
			return err
		}
		_, err = r.Client.Memberships().Create(ctx, &database.CreateMembershipInput{
			WorkspaceID: workspace.ID,
			UserID:      userID,
			Role:        omittable.Set(database.MembershipRoleOwner),
		}, func(o *database.CallOptions[database.MembershipFieldOptions]) {
			o.SkipTenancy = true
		})
		return err
	})
	if err != nil {
		return nil, fmt.Errorf("bootstrapping workspace: %w", err)
	}
	return workspace, nil
}
