package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
	"github.com/teandresmith/sqlgen-example/internal/graph/sqlgenresolver"
)

// UpdateTimeEntry is the resolver for the updateTimeEntry field.
func (r *mutationResolver) UpdateTimeEntry(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateTimeEntryInput) (*database.TimeEntry, error) {
	if input.Hours != nil && input.HoursInc != nil {
		return nil, sqlgenresolver.InvalidInputError("update time_entries: column \"hours\" cannot be both set and incremented in one mutation")
	}
	if input.HoursInc != nil && input.HoursDec != nil {
		return nil, sqlgenresolver.InvalidInputError("update time_entries: column \"hours\" cannot be both incremented and decremented in one mutation")
	}
	setIn := translateUpdateTimeEntryInput(input)
	hasSet := hasUpdateTimeEntrySetFields(input)
	var incOps []sqlgenresolver.IncrementOp[database.TimeEntryIncrementColumn]
	if input.HoursInc != nil {
		incOps = append(incOps, sqlgenresolver.IncrementOp[database.TimeEntryIncrementColumn]{
			Column: database.TimeEntryIncrementHours,
			Amount: int(*input.HoursInc),
		})
	}
	if input.HoursDec != nil {
		incOps = append(incOps, sqlgenresolver.IncrementOp[database.TimeEntryIncrementColumn]{
			Column: database.TimeEntryIncrementHours,
			Amount: -int(*input.HoursDec),
		})
	}
	return r.M.UpdateTimeEntry(ctx, id, setIn, hasSet, incOps)
}

// UpdateTimeEntries is the resolver for the updateTimeEntries field.
func (r *mutationResolver) UpdateTimeEntries(ctx context.Context, filter gqlmodel.TimeEntryFilter, input gqlmodel.UpdateTimeEntryInput) ([]*database.TimeEntry, error) {
	if input.Hours != nil && input.HoursInc != nil {
		return nil, sqlgenresolver.InvalidInputError("update time_entries: column \"hours\" cannot be both set and incremented in one mutation")
	}
	if input.HoursInc != nil && input.HoursDec != nil {
		return nil, sqlgenresolver.InvalidInputError("update time_entries: column \"hours\" cannot be both incremented and decremented in one mutation")
	}
	return r.M.UpdateTimeEntries(ctx, translateTimeEntryFilter(&filter), translateUpdateTimeEntryInput(input))
}

// DeleteTimeEntry is the resolver for the deleteTimeEntry field.
func (r *mutationResolver) DeleteTimeEntry(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.DeleteTimeEntry(ctx, id)
}

// TimeEntry is the resolver for the timeEntry field.
func (r *queryResolver) TimeEntry(ctx context.Context, id uuid1.UUID) (*database.TimeEntry, error) {
	return r.Q.TimeEntry(ctx, id)
}

// TimeEntries is the resolver for the timeEntries field.
func (r *queryResolver) TimeEntries(ctx context.Context, filter *gqlmodel.TimeEntryFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.TimeEntry], error) {
	return r.Q.TimeEntries(ctx, translateTimeEntryFilter(filter), first, after, last, before)
}

// TimeEntryList is the resolver for the timeEntryList field.
func (r *queryResolver) TimeEntryList(ctx context.Context, filter *gqlmodel.TimeEntryFilter, sort []*gqlmodel.TimeEntrySort, limit *int, offset *int) (*database.PaginateResult[database.TimeEntry], error) {
	return r.Q.TimeEntryList(ctx, translateTimeEntryFilter(filter), translateTimeEntrySort(sort), limit, offset)
}
