package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen-example/internal/database"
	gqlmodel "github.com/teandresmith/sqlgen-example/internal/graph/model"
)

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, input gqlmodel.CreateWorkspaceInput) (*database.Workspace, error) {
	return r.M.CreateWorkspace(ctx, translateCreateWorkspaceInput(input))
}

// CreateWorkspaces is the resolver for the createWorkspaces field.
func (r *mutationResolver) CreateWorkspaces(ctx context.Context, inputs []*gqlmodel.CreateWorkspaceInput) ([]*database.Workspace, error) {
	xs := make([]*database.CreateWorkspaceInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateWorkspaceInput(*in))
	}
	return r.M.CreateWorkspaces(ctx, xs)
}

// UpdateWorkspace is the resolver for the updateWorkspace field.
// FIX-066: no numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateWorkspace(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateWorkspaceInput) (*database.Workspace, error) {
	setIn := translateUpdateWorkspaceInput(input)
	hasSet := hasUpdateWorkspaceSetFields(input)
	return r.M.UpdateWorkspace(ctx, id, setIn, hasSet)
}

// UpdateWorkspaces is the resolver for the updateWorkspaces field.
func (r *mutationResolver) UpdateWorkspaces(ctx context.Context, filter gqlmodel.WorkspaceFilter, input gqlmodel.UpdateWorkspaceInput) ([]*database.Workspace, error) {
	return r.M.UpdateWorkspaces(ctx, translateWorkspaceFilter(&filter), translateUpdateWorkspaceInput(input))
}

// UpsertWorkspace is the resolver for the upsertWorkspace field.
func (r *mutationResolver) UpsertWorkspace(ctx context.Context, input gqlmodel.CreateWorkspaceInput) (*database.Workspace, error) {
	return r.M.UpsertWorkspace(ctx, translateCreateWorkspaceInput(input))
}

// DeleteWorkspace is the resolver for the deleteWorkspace field.
func (r *mutationResolver) DeleteWorkspace(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.DeleteWorkspace(ctx, id)
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context, id uuid1.UUID) (*database.Workspace, error) {
	return r.Q.Workspace(ctx, id)
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context, filter *gqlmodel.WorkspaceFilter, first *int, after *string, last *int, before *string) (*database.Connection[database.Workspace], error) {
	return r.Q.Workspaces(ctx, translateWorkspaceFilter(filter), first, after, last, before)
}

// WorkspaceList is the resolver for the workspaceList field.
func (r *queryResolver) WorkspaceList(ctx context.Context, filter *gqlmodel.WorkspaceFilter, sort []*gqlmodel.WorkspaceSort, limit *int, offset *int) (*database.PaginateResult[database.Workspace], error) {
	return r.Q.WorkspaceList(ctx, translateWorkspaceFilter(filter), translateWorkspaceSort(sort), limit, offset)
}
